### ISSUE TITLE
Incomplete CSV/Excel rows downloaded from DT buttons through RMarkdown-Shiny-Flexdashboard

### ISSUE THREAD

**Issue by gundalav** [rstudio/rmarkdown#1018]
I have the following **[RMarkdown Shiny][1]** document:

    ---
    title: "Title"
    runtime: shiny
    output: 
      flexdashboard::flex_dashboard:
        vertical_layout: scroll
        theme:  bootstrap
        orientation: rows
    ---
    
    ```{r setup, include=FALSE}
    library(flexdashboard)
    ```
    
    
    
    Rows {data-height=400}
    -----------------------------------------------------------------------
    
    ### Table
    
    ``` {r show_table}
    library(DT)
    library(ggplot2)
    renderDataTable( {
      dat  <- diamonds
       },
       extensions = c('Scroller','Buttons'),
        class = 'compact cell-border stripe',  rownames = FALSE,
        filter = list( position = 'top', clear = FALSE, plain =TRUE ),
        options = list(
            deferRender = FALSE,
            scrollY = 200,
            scroller = TRUE,
            dom = 'Bfrtip',
            buttons = c('csv', 'excel')
          )
      )
    ```

Which produces this document:

[![enter image description here][2]][2]

After I download the Excel file, the number of rows is just ~90 lines
not complete 53,940 entries. Why is that and how can I fix it?

  [1]: http://rmarkdown.rstudio.com/authoring_shiny.html
  [2]: https://i.stack.imgur.com/jVpCK.jpg

**Comment by yihui** [comment]
If I remember correctly, the download buttons in DataTables can only let you download the current page of data, so I'm surprised that you actually got 90 rows of data instead of 7 (as shown in your screenshot).

Anyway, this is a question about the DT package, not directly relevant to rmarkdown. You can file it to https://github.com/rstudio/DT/issues/ but I probably won't have time to process it until next year, so I recommend you to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead to see if you have any luck there (judging from the URL of your image, you probably have already posted on StackOverflow but I don't know the URL of your post). Thanks!
