### ISSUE TITLE
Equations in Rmd not rendering in word document

### ISSUE THREAD

**Issue by rdabbler** [rstudio/rmarkdown#103]
If I write a equation in Rmd of the form $$ x^2+y^2=z^2 $$ and use knit word, it only shows the + and = sign but not the rest of the expression. I will appreciate any guidance on this.

Regards

**Comment by algarsal** [comment]
I had the same problem and it solved adding more brackets. 

May be someone have the same issue. 
* With $$\chi^2_{n-1} = \sum^n_{i=1} { \frac{ ( O_i - E_i ) ^2} {E_i} }$$ it displayed right into html, but not in pdf nor docx (at first I though it was because LibreOffice.

It solved adding more brackets: 
$$\chi^2_{n-1} = \sum^n_{i=1} { \frac{ {( {O_i} - {E_i} )} ^2} {E_i} }$$
Now it displays perfect even with LibreOffice 

But your equation worked right for me.
