### ISSUE TITLE
consider expanding Markdown image paths for Pandoc

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#1053]
Currently, image links of the form

    ![alt](~/path/to/file.png)

won't be handled by Pandoc, as the `~` prefix is not expanded:

```
pandoc: Could not fetch ~/scratch/plot.png
~/scratch/plot.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
```

We might consider solving this with the use of a custom Pandoc filter, as described in http://pandoc.org/scripting.html

(previous discussion here: https://github.com/rstudio/rmarkdown/pull/1052)

**Comment by yihui** [comment]
This would resolve #811, but since (1) it is typically a bad idea to use absolute paths (2) it is more of a Pandoc issue (3) Pandoc has no interest in "fixing" it (https://github.com/jgm/pandoc/issues/3135) and (4) the fix is not trivial, my conclusion is that we will just educate users on a case by case basis when this problem arises.
