### ISSUE TITLE
Is it possible to avoid C stack usage is too close to the limit on macOS?

### ISSUE THREAD

**Issue by gurol** [rstudio/rmarkdown#1058]
I got the following error `C stack usage  8024819 is too close to the limit` in RStudio.

After I rendered .R script (output file: X.knit.md is produced and /usr/local/bin/pandoc started)

The system's stack size is increased (15938355).

**Comment by yihui** [comment]
This sounds like a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) with a reproducible example. Thanks!

FYI, if you google the error message, this is the first result (not sure if it is helpful): https://stackoverflow.com/q/14719349/559676

**Comment by lfaino** [comment]
@yihui,
I have the same problem but after changing the ulimit for the system, Rstudio does not pick the change. 
Any idea on how to fix it?
Cheers
Luigi
