### ISSUE TITLE
html_notebook ignores global chunk options

### ISSUE THREAD

**Issue by sbliven** [rstudio/rmarkdown#1077]
Global options are ignored when using the 'Preview notebook' engine.

Example:

    ---
    title: "Test"
    output:
      html_notebook: default
      html_document: default
    ---
    
    ```{r setup, echo=FALSE}     
    library(knitr)
    opts_chunk$set(echo=FALSE,results='hide',fig.keep='none')
    ```
    
    ```{r hidden}        
    1+1
    plot(1:5, 1:5)
    ```

The `html_document` renders only the title, with no output from the "hidden" chunk (as expected). However, in the `html_notebook` rendering the code, results, and figure are all shown. These have to be disabled individually for each chunk.

**Comment by sbliven** [comment]
Note that this issue started as a SO question: https://stackoverflow.com/questions/41911487/html-notebook-ignores-global-chunk-options

**Comment by jmcphers** [comment]
This is an issue with the RStudio IDE rather than the rmarkdown package, and we've made a couple of improvements in respecting global chunk options in RStudio 1.1. You can try a daily build here to see if it behaves as you expect:

https://dailies.rstudio.com/

I think you'll find that `echo=FALSE` is now respected; the other two options won't as they also don't currently work even when set directly on the chunk (they are not supported in the notebook).
