### ISSUE TITLE
html_notebook documents execute in wrong environment

### ISSUE THREAD

**Issue by jbintz** [rstudio/rmarkdown#1137]
This is similar to #1124. Here is an R Notebook. The first chunk calls `x` in a "clean" local environment and throws an error-as it should. Then, before making and running the second chunk, I defined local variable `x` in the console `x <- 3`. I did not define `x` anywhere in the .Rmd file. Then I made the second chunk. The rendered document, shown below, returns `3`. This is not a desirable outcome.

````
---
title: "R Notebook"
output: html_notebook
---

```{r}
x
```

```{r}
x
```

````
<img width="934" alt="screen shot 2017-09-07 at 1 00 32 pm" src="https://user-images.githubusercontent.com/20375541/30175710-a9c115a8-93cd-11e7-9164-34a4309c0e4e.png">

**Comment by yihui** [comment]
Variables defined in the console are typically global instead of local variables as you described, and these variables will be available to code chunks in your notebook. I think we probably didn't emphasize enough in the documentation about the difference between notebooks and normal R Markdown documents: http://rmarkdown.rstudio.com/r_notebooks.html The former uses your current R session (for previewing) and the latter uses a new R session. Notebooks do not know whether a variable is defined in a code chunk or the R console.

To minimize surprises, you should use the menu "Restart R and Run All Chunks". That will recompile the notebook in a new R session.

![image](https://user-images.githubusercontent.com/163582/30194972-256f2606-941c-11e7-8d07-302b24b9eb74.png)

**Comment by jbintz** [comment]
Thank you for clarifying. I did search the documentation and did not pick up on that difference. It's still unclear to me, however, _why_ a notebook should be different in this way.

**Comment by yihui** [comment]
Perhaps one of @jjallaire @jmcphers @kevinushey can explain this better than me :)

**Comment by jmcphers** [comment]
Yes, this behavior is intentional. When you execute code in the notebook, it is practically the same as doing so at the R console (in fact you'll see the code echoed to the R console if it's open); R code is evaluated in the global environment, and sees anything defined there. The differences in execution behavior between notebook chunks and plain R console code are few, and are documented under [Executing Code](http://rmarkdown.rstudio.com/r_notebooks.html#executing_code) in the Notebook section of the R Markdown website. 

Imagine if this weren't the case -- you would need to have a private environment for each notebook, and a separate environment pane so you could see the values available to that notebook. It's not impossible, but it'd be significantly more complex!

There's a tension here between convenience and reproducibility. It's convenient to be able to run chunks in whatever order you want, and share objects and values from elsewhere. Notebooks give you more convenience at the cost of putting more of the burden on you to make sure things are reproducible. We've tried to give you lots of tools to maintain reproducibility (knitting, restart and run all chunks, etc.), without taking away the conveniences that allow you to iterate and experiment quickly. 

Hope that's helpful, and very open to your perspective if you have ideas on a better approach. We're always looking to make things more useful and better. :-)
