### ISSUE TITLE
[ioslides] Slides not changing properly while using incremental: true and bulleted content in slide notes

### ISSUE THREAD

**Issue by mikolajolszewski** [rstudio/rmarkdown#1147]
Hi there,

If you use ioslides and set up your markdown so that bullets show up one by one (incremental: true) and you put some slide notes that also use bulletting, the bullets in the notes also require clicks to show up. This might be desired in the presenter mode, but if you intend to share the presentation with others, they need to click more than one time (# of bullets in notes) to change the slide. I attached a minimal example that illustrates this behaviour.

I find bulleted notes very helpful but currently need to hack it by explicitly using the bullet character (•) instead of letting markdown create bullets for me.

````
---
title: "Incremening notes (issue?)"
author: "Mikołaj Olszewski"
output:
  ioslides_presentation:
    widescreen: true
    incremental: true
---

## Slide 1 with bulleted presenter notes

- Content bullet 1
- Content bullet 2

<div class="notes">
- Note 1
- Note 2
- Note 3
</div>

## Slide 2 with bulleted presenter notes

Some regular content...

<div class="notes">
- Note 1
- Note 2
- Note 3
</div>

## Slide 3 with bulleted presenter notes

Some regular content 2...

<div class="notes">
- Note 1
- Note 2
- Note 3
</div>
````

**Comment by yihui** [comment]
I'd say this is by design, and ioslides presentation in this package is pretty much feature-frozen. We are unlikely to change anything in this format. Personally I recommend you to take a look at other presentation frameworks like [xaringan](/yihui/xaringan) and [revealjs](/rstudio/revealjs), where most of these issues have been well solved. At least I know this problem does not exist in xaringan (of which I'm the author).

Thanks for the feedback!
