### ISSUE TITLE
rmarkdown::render() appears to interfere with utils::capture.output().

### ISSUE THREAD

**Issue by JohnMount** [rstudio/rmarkdown#1150]
`rmarkdown::render()` appears to interfere with utils::capture.output().

Expected behavior: a `rmarkdown::render()` run of a `R-mardown` document containing the code below works as in the R console, printing nothing nothing during the msg assignment and then storing the message "hi" into the msg variable.

Observed behavior (indicated below): the "hi" is instead printed early and the msg variable receives an empty string.

Code:

```{r}
# rmarkdown::render("q.Rmd")
packageVersion("knitr")
packageVersion("rmarkdown")

msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
print(paste('msg is:', msg))
```

Result:

-------------

`` r
# rmarkdown::render("q.Rmd")
packageVersion("knitr")
```

    ## [1] '1.17'

``` r
packageVersion("rmarkdown")
```

    ## [1] '1.6'

``` r
msg <- utils::capture.output(
  {
    message("hi")
  },
  type='message')
```

    ## hi

``` r
print(paste('msg is:', msg))
```

    ## [1] "msg is: "

-------------

Input `q.Rmd.txt` and result `q.md.txt` are attached to this issue.

[q.md.txt](https://github.com/rstudio/rmarkdown/files/1345326/q.md.txt)
[q.Rmd.txt](https://github.com/rstudio/rmarkdown/files/1345327/q.Rmd.txt)

**Comment by yihui** [comment]
Please read the issue template (the text you deleted before posint this issue) carefully the next time you file an issue to make sure your issue is correct formatted (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

rmarkdown is based on knitr, which is in turn based on the evaluate package, which uses `sink()` and `withCallingHandlers()` to capture output and messages. That might be the reason why you cannot capture messages by default.

Setting the chunk `message = FALSE` should work.
