### ISSUE TITLE
build_site resource copying reads through symlinks

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#1176]
Given a site containing a symlink:

```
touch index.Rmd
touch _site.yml
ln -s ~/lunch.txt .
```

Rendering this site creates a `_site` directory with the contents of `lunch.txt`, not the symlink.

```
rmarkdown::render_site()
```

```
$ ls _site
index.html lunch.txt  site_libs
```

Comparing the two files:
```
$ ls -l lunch.txt _site/lunch.txt
-rw-r--r--  1 aron  staff  86 Oct 25 19:53 _site/lunch.txt
lrwxr-xr-x  1 aron  staff  21 Oct 25 19:50 lunch.txt -> /Users/aron/lunch.txt
```

I discovered this when investigating an issue with rmarkdown prior to the fix for #946 - we were copying the whole `packrat/lib` tree and also reading through symlinks. The packrat tree was pointing to cached package contents; reading through symlinks copied the package contents into the `_site` directory.

Maybe this doesn't deserve fixing, but I wanted to at least file the issue to record the behavior.

**Comment by yihui** [comment]
This is because `file.copy()` in R cannot copy symlinks (at least it does not provide an option to do so), which is similar to the default behavior of the `cp` command. With `cp`, you have to `cp -P` to copy a symlink, otherwise it will resolve the symlink to the actual file.

Anyway, copying symlinks can be a tricky issue if the symlinks are relative, and that is probably why `file.copy()` and `cp` choose to copy the files instead by default.

I guess we cannot do anything about it, so I'm closing this issue. Thanks for the report!
