### ISSUE TITLE
Support an option to output word document with a Chinese table of contents

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rmarkdown#1214]
Here is a sample `.Rmd` source content.

````r
---
title: "无标题"
output:
  word_document:
    toc: true
---

## 标题1

这里是测试文本。

## 标题2

这里也是测试文本。
````

What it renders is as the following screenshot:

![image](https://user-images.githubusercontent.com/13306020/33793563-4407e0fa-dcf4-11e7-8572-4675c64c15e4.png)

The title of the table of contents should be "目录" instead, but I do not know how to change it.

**Comment by yihui** [comment]
This looks like a question instead of a bug report or feature request. Please do us a favor to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead in the future. This one has been asked before:

- https://stackoverflow.com/q/47290659/559676
- https://yihui.name/en/2017/11/thanks-tj-mahr/

**Comment by psychelzh** [comment]
@yihui Thank you, and I think I should really learn more about pandoc.
