### ISSUE TITLE
pgfplots doesn't work with r markdown?

### ISSUE THREAD

**Issue by shengxue** [rstudio/rmarkdown#1215]
```
! Undefined control sequence.
l.12     \addplot
                 3[surf,domain=0:360,samples=40]
```

````
---
title: "Hello World"
output:  
  pdf_document: default  
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
---

```{r,engine='tikz',fig.ext='svg',fig.width=5, fig.align='center', echo=FALSE}
\begin{tikzpicture}
    \begin{axis}
    \addplot3[surf,domain=0:360,samples=40] 
        {sin(x)*sin(y)};    
    \end{axis}
\end{tikzpicture}
```
````

**Comment by yihui** [comment]
You seem to have misunderstood the `tikz` engine in **knitr**. It is independent of **rmarkdown**, and does not know your `\usepackage{pgfplots}` specified in YAML. The tikz engine is a little complicated. The best way to understand it is to read the **knitr** book, and the second best is to read the source code: 
https://github.com/yihui/knitr/blob/73387d643a4e3c9a98d816ee9cd312353c84d80c/R/engine.R#L243-L291

Anyway, this is a question instead of a bug report. Please do me a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead. Thanks!

**Comment by shengxue** [comment]
It would be very nice to have an option to not clean temporary .tex file, so that we can check what's wrong with the tex file.

**Comment by yihui** [comment]
I agree.

**Comment by shengxue** [comment]
Any plan to add this option?

**Comment by yihui** [comment]
`keep_tex: true`? https://bookdown.org/yihui/rmarkdown/pdf-document.html

**Comment by shengxue** [comment]
My rmd file is 'tikz.rmd'. With that option, if the build succeeds,  the temporary .tex '--output tikz.tex' file is kept.   

while if the build fails, the temporary file '.\tikz39544ddf259f.tex' is gone.    This temporary file is more necessary for trouble shooting
> unable to run 'latex' on '.\tikz39544ddf259f.tex'
