### ISSUE TITLE
Using JavaScript Events with shiny_prerendered

### ISSUE THREAD

**Issue by Kvit** [rstudio/rmarkdown#1218]
`Is it possible to use the functionality of JavaScript Events https://shiny.rstudio.com/articles/js-events.html with shiny_prerendered runtime?  If so,  if there are any special rules?

**Comment by yihui** [comment]
I guess the answer would be yes, but I'm not 100% sure. You may test it and let us know if it does not work.

**Comment by Kvit** [comment]
My problem is that I don't know enough details about inner workings of rmd to test **correctly**.

**Comment by yihui** [comment]
A Shiny Rmd document is essentially a Shiny app, with the UI generated from R Markdown instead of the traditional ui.R. In theory, the JS events should also work in Shiny Rmd documents. To test them, you will almost surely need the Developer Tools of your browser.

Anyway, it is unclear to me what you actually want to do with these events. A minimal example helps.

**Comment by Kvit** [comment]
I'm trying to make spinners from package https://github.com/andrewsali/shinycssloaders work in Rmd. 
Here is a mimumum example:
`
---
title: "css loader test"
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(shinycssloaders)
test_table<-data.frame(A=rnorm(200), B=rnorm(200))
```


```{r}
# should load table with spinner
withSpinner(DT::dataTableOutput("table"))
```

```{r}
output$table<- DT::renderDataTable({
  Sys.sleep(2)
  return(test_table)
})
```

`

**Comment by Kvit** [comment]
actually, the final goal is to make spinners work in Flexdashboard with shiny_prerendered runtime.

**Comment by yihui** [comment]
I'm not familiar with the **shinycssloaders** package. I think you'll have better luck if you ask its author. I'm the pretty much the only person answering questions and processing issues in this rmarkdown repo, and I really don't have spare time for this particular issue, unless it turns out to be a bug of **rmarkdown**.

**Comment by Kvit** [comment]
thanks, I will try to find out
