### ISSUE TITLE
DT::datatable renders differently in r_notebook inline display and preview or html output

### ISSUE THREAD

**Issue by ethanyxu** [rstudio/rmarkdown#1220]
When specifying column width, the datatable in r notebook inline display correctly shows the adjusted columns. However, the preview in Rstudio, as well as html shown in new window still shows narrow columns. 

    DT::datatable(fp,
          rownames = FALSE,
          options = list(autoWidth=TRUE,
                                 columnDefs = list(list(width = '200px', targets = c(1))))
          )

**Comment by ethanyxu** [comment]
This is interesting: The column widths correctly changes when I select "show 100 entries" (vs. default "show 10 entries".

**Comment by rich-iannone** [comment]
@ethanyxu Thanks for posting an issue here. Unfortunately, I cannot reasonably reproduce what you've seen because the code you provided is not self-conained (e.g., we don't have the variable `fp`).

Below is an excerpt from the Issue Template doc. Please post an updated example after reading this: 

-----------

For bug reports, please provide a minimal, self-contained, and reproducible example by reducing your example as much as possible right before the problem goes away. By doing this, you may be able to figure out what the problem really is before reporting to us. You can attach your example as a zip file here along with `devtools::session_info('rmarkdown')`, and screenshots are often very helpful to illustrate your issues.

Please do install and test the development version here before you report a bug:

```r
devtools::install_github("rstudio/rmarkdown")
```

To include a verbatim chunk of arbitrary text, wrap it in a pair of three backticks. When any line of your text contains N backticks (N >= 3), use N + 1 backticks to wrap the text, e.g. use four backticks to wrap three:

````
---
title: Hello World
output: html_document
---

A sample document.

```{r}
1 + 1  # a line of code
```

Another paragraph.
````

If it is just a chunk of R code (or other languages) and you want syntax highlighting, you may use three backticks to format it, e.g.

```r
rnorm(10)
```
