### ISSUE TITLE
ioslides_presentation "Invalid UTF-8 stream" error with &nbsp;

### ISSUE THREAD

**Issue by jrowen** [rstudio/rmarkdown#134]
I'm using `render` to create an ioslides presentation with a table generated from `pandoc.table` and am running into the following error: 

*pandoc.exe: Cannot decode byte '\xa0': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream*

The error appears to be caused by `pandoc.table` returning `&nbsp;` for the first column header, as removing `&nbsp;` eliminates the error.  Below is an Rmd file that can be used to reproduce the error message.  The same error message occurs when using the *Knit HTML* button in RStudio.

    ---
    title: "Untitled"
    output: ioslides_presentation
    ---
    
    ## Slide
    
    ```{r, echo=FALSE, results='asis'}
    library(pander)
       
    m <- mtcars[1:2, 1:3]
    
    # error
    pandoc.table(m, style = "rmarkdown")
    
    # success
    ptable = function(...) {
      cat(paste0(gsub("&nbsp;", "      ",
                      pander.return(...)), collapse = "\n"))
    }
    # ptable(pandoc.table(m, style = "rmarkdown"))
    ```

**Comment by dmurdoch** [comment]
I get a similar error.  It appears my minimal example is as follows:

minimal.Rmd:
```
---
output: 
  ioslides_presentation
bibliography: reflist.bib
nocite: | 
  @rstudio
---

## Slide

Shiny [@shiny]
```

with reflist.bib:
```
 @Manual{rstudio,
    title = {RStudio: Integrated development environment for R},
    author = {{RStudio Inc.}},
    year = 2014,
    note = {version 0.99.152},
    url = {http://www.rstudio.org}
 }

 @Manual{shiny,
    title = {shiny: Web Application Framework for R},
    author = {{RStudio Inc.}},
    year = {2014},
    url = {http://shiny.rstudio.com}
  }
```
Running in Windows in a US locale, I get the following output messages when I try to compile:
```
  |.................................................................| 100%
  ordinary text without R code


"C:/Program Files/RStudio/bin/pandoc/pandoc" minimal.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output minimal.html --filter pandoc-citeproc --smart --email-obfuscation none --self-contained --variable transition=0.4 --template "F:\R\svn\R-3-1-branch\library\rmarkdown\rmd\ioslides\default.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --variable "ioslides-url=F:\R\svn\R-3-1-branch\library\rmarkdown\rmd\ioslides\ioslides-13.5.1" --bibliography reflist.bib 


processing file: minimal.Rmd
output file: minimal.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" minimal.utf8.md --to ioslides_presentation.lua --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output "C:\Users\murdoch\AppData\Local\Temp\RtmpYf4k13\ioslides-outpute28189a3a46.html" --filter pandoc-citeproc 
pandoc.exe: Cannot decode byte '\xe2': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" minimal.utf8.md --to ioslides_presentation.lua --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output "C:\Users\murdoch\AppData\Local\Temp\RtmpYf4k13\ioslides-outpute28189a3a46.html" --filter pandoc-citeproc' had status 1 
Execution halted
```

**Comment by lselzer** [comment]
I can confirm the issue with ES.AR locale (Spanish_Argentina.1252). 
My guess is that this in a pandoc issue. I tried and got the same error with other computers at work. However, when I raised the issue with the pandoc team they couldn't reproduce it. See
https://github.com/jgm/pandoc/issues/1634

**Comment by jjallaire** [comment]
@dmurdoch Thanks for reporting this. We've seen issues with UTF-8 characters and ioslides previously but this was related to the use of unicode characters (which pandoc doesn't like when passed through a custom lua markdown renderer like the one we use with ioslides). Your example however appears to only include ascii characters. We'll investigate and hopefully figure out the root cause soon.

**Comment by jmcphers** [comment]
@dmurdoch I spent some time looking into this. It turns out that this is indeed just another manifestation of the non-ASCII character problem; when the citations are injected this content enters the document:

———. 2014b. Shiny: Web Application Framework for R. http://shiny.rstudio.com.

The dashes are en dashes (not hyphens), which are not ASCII, and are translated to this internal Pandoc representation (note the `\8212` representation for the en dashes):

    Para [Str "\8212\8212\8212",Str ".",Space,Str "2014",Str "b",Str ".",Space,Emph [Str "Shiny",Str ":",Space,Str "Web",Space,Str "Application",Space,Str "Framework",Space,Str "for",Space,Str "R"]

To the best of my knowledge there's nothing we can do on the rmarkdown side to fix this. We tried a bunch of different input document encodings with and without BOMs; the problem seems not to be in the processing of the input document (which in this case doesn't even contain the offending characters) but in Pandoc's internal handoff from its native encoding format to its Lua interpreter, over which we don't have control.

As a workaround until the underlying Pandoc issue is fixed (and this does seem to be https://github.com/jgm/pandoc/issues/1634), you could use a CSL that doesn't write en dashes to the stream. For instance, this works for me, via small.csl from [here](https://github.com/citation-style-language/styles):

    ---
    output: 
      ioslides_presentation:
        self_contained: no
    bibliography: reflist.bib
    csl: small.csl
    nocite: | 
      @rstudio
    ---

**Comment by jmcphers** [comment]
Filed an updated bug for Pandoc here: https://github.com/jgm/pandoc/issues/2101

**Comment by dmurdoch** [comment]
On 20/04/2015 4:20 PM, Jonathan wrote:
> @dmurdoch <https://github.com/dmurdoch> I spent some time looking into
> this. It turns out that this is indeed just another manifestation of the
> non-ASCII character problem; when the citations are injected this
> content enters the document:

Thanks, this is really helpful.  I'm on the road right now and can't
check that it works, but it certainly looks like it should.

Duncan Murdoch
