### ISSUE TITLE
undesired effect of `'` in R outputs with `comment = "", collapse = TRUE` chunk options

### ISSUE THREAD

**Issue by choisy** [rstudio/rmarkdown#1349]
````
If I use the default chunk options, the output layout is great:

```{r}
fisher.test(matrix(c(3, 1, 1, 3), 2))
```

But if I decide to

* uncomment the output and
* collapse the source and output blocks into a single block,

potential `'` in the R output text may produce undesired effect:

```{r comment = "", collapse = TRUE}
fisher.test(matrix(c(3, 1, 1, 3), 2))
```

where whatever is after `'` is printed as if it were a character string.
````

**Comment by yihui** [comment]
That is expected. By `collapse = TRUE`, you indicate that your text output can be merged into the R source block, and by default, the source block will be syntax highlighted. The Markdown output is:

````
```r
fisher.test(matrix(c(3, 1, 1, 3), 2))

	Fisher's Exact Test for Count Data

data:  matrix(c(3, 1, 1, 3), 2)
p-value = 0.4857
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.2117329 621.9337505
sample estimates:
odds ratio 
  6.408309 
```
````

With syntax highlighting, the characters after the single quote will be treated as a character string in R.

You have to either use a `comment` option that starts with `#`, or disable syntax highlighting (chunk option `highlight = FALSE`).

This is a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead in the future instead, and let us know the link if you don't get an answer in a few days. Thanks!
