### ISSUE TITLE
Windows: Using python in Rmarkdown trouble: R6034 Runtime Error! / Rterm This application failed to start popups

### ISSUE THREAD

**Issue by mjbeyeler** [rstudio/rmarkdown#1352]
RStudio is causing me trouble when I want to use my Anaconda2 python distribution. I have some code that runs perfectly fine In my Jupyter notebook, but when I try to run it using the knit command, or even the "run current chunk" command, I get some weird popup errors.

One example looks like this: https://imgur.com/a/3e1Umwd

Another example: https://imgur.com/a/avr3Lob

From investigating, I get that this is usually a .dll conflict in the system path, or somewhere in the RStudio code.
https://support.esri.com/en/technical-article/000013127

**Minimal example**

> ---
> title: "R Notebook"
> output: html_document
> ---
> 
> This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you execute code within the notebook, the results appear beneath the code. 
> 
> Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 
> 
> ` ` `{r}
> knitr::opts_chunk$set(engine.path = list(python = file.path(Sys.getenv("USERPROFILE"),"Anaconda2\\python.exe", fsep="\\")))
> ```
> 
> 
> ` ` `{python}
> import matplotlib.pyplot as plt
> plt.plot([1, 2, 3, 4])
> plt.ylabel('some numbers')
> plt.show()
> ` ` `
> 

===========================================================

Weirdly enough, if I change the second chunk's header to

` ` `{python, engine.path="C:/Users/micha/Anaconda2/python.exe"}

and then click "run current chunk", then the code is able to run, and a popup of the figure is created

https://imgur.com/a/El3pgUh

This seems very weird behavior to me, and the simplest assumption is that there is a bug somewhere in the RSudio code.

Can anybody using Windows reproduce this?

**Comment by cderv** [comment]
Hi @mjbeyeler, sorry for the delay on this issue. 

For using python inside Rmd document we now recommand to use the `reticulate` package. 

See the documentation in here: https://rstudio.github.io/reticulate/articles/r_markdown.html

Can you try using **reticulate** ? 

I tried myself with this : 
````md
---
title: "R Notebook"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
use_virtualenv("r-reticulate")
```

```{python}
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```
````

It works correctly chunk by chunk, but does not knit correctly yet in RStudio due to a diferrent error (QT related  that needs to be fixed in **reticulate** not rmarkdown), unless you change the graphic device 

````md 
---
title: "R Notebook"
output: html_document
---

```{r setup, include=FALSE}
library(reticulate)
use_virtualenv("r-reticulate")
```

```{python}
import matplotlib as mp
mp.use("tkAgg")
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```
````

Can you check all that too ?

**Comment by cderv** [comment]
See also the comment for another solution setting tha QT env var https://github.com/rstudio/reticulate/issues/586#issuecomment-7171592

**Comment by cderv** [comment]
I am closing this here as things have evolved with **reticulate**. any related issue should be open in **reticulate** repo. Thanks!
