### ISSUE TITLE
Plots not generated in PowerPoint if no space between slide text and chunk

### ISSUE THREAD

**Issue by ronblum** [rstudio/rmarkdown#1363]
### Environment

    rmarkdown: version 1.9.17
    Tested using RStudio 1.2.672-1 on MacOS 10.12.6 and Windows 10 with R 3.5.0

### Details

For PowerPoint presentations: In a slide with a plot, if there's no space between the slide text and the chunk, the plot will not get rendered. Only the text will be displayed and anything in the chunk after the plot.
    
````
Some opening remarks with no space
```{r plotty_spaceless}
plot(pressure)
```
````

Output:

-------

<img width="450" alt="space" src="https://user-images.githubusercontent.com/31009952/40803240-21df5cae-64e6-11e8-8618-ff2d5c3ded96.png">

-------

This only seems to be an issue with PowerPoint. It works with Slidy, Beamer, and ioslides.

Here's a full .Rmd file that shows the example of the failure, as well as two comparison cases in which the plot is correctly generated:
- A blank line between the text and the chunk
- Text in the chunk before the plot code

(In both cases, the plot is on a separate slide, as in #1354.)

````
---
title: "Spaceless Plots"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plot and spaceless text

Some opening remarks with no space
```{r plotty_spaceless}
plot(pressure)
```

Some closing remarks below

## Plot and spaced out text

Some opening remarks with a space

```{r plotty_spaced}
plot(pressure)
```

Some closing remarks below

## Content and spaceless text

Some opening remarks with no space
```{r summy}
'Something in the chunk'
plot(pressure)
```

Some closing remarks below

````

**Comment by yihui** [comment]
Plots in PowerPoint are kind of special, as I mentioned in the documentation (#1354). They always appear on separate slides, so you'd better separate them from the rest of content with blank lines.

That said, this should be a Pandoc bug, but since the workaround is so simple, I suggest you just add a blank line. If you wish, you can report the bug to the Pandoc repo, although I doubt if it will be fixed soon (I know the developer of the PPT format has been busy these months).

Not using enough blank lines is a very common problem of Markdown users, as I mentioned in the end of Section 2.5.2 in the R Markdown book: https://bookdown.org/yihui/rmarkdown/markdown-syntax.html

Anyway, thanks a lot for the report!
