### ISSUE TITLE
Bibliography not rendered if given in YAML other than main header

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rmarkdown#1364]
My package includes a function to programmatically build and render an RMarkdown file, including a bibliography.

If I place the `bibliography: ` parameter in the main YAML header of the document, it renders correctly (see 
[rmarkdown_bib_header_test.zip](https://github.com/rstudio/rmarkdown/files/2065823/rmarkdown_bib_header_test.zip) for .R, .Rmd, and .bib files for this examples).

### Renders correctly:
```r
rmarkdown::render("bib_in_header.rmd")
```

However, if I place the `bibliography: ` parameter in a YAML block outside of the main header, rmarkdown doesn't pick this up and does not render the citations or bibliography.

### .bib file isn't found:
```r
rmarkdown::render("bib_not_in_header.rmd")
```

Other YAML metadata doesn't seem to behave like this (e.g., `nocite`, `csl`, and even `title` can all be placed in other YAML blocks and work correctly), so this seems like a bug. It would be really helpful if rmarkdown could be adjusted to accept `bibliography: ` metadata given outside the main header, as that would make it easier for users of my package to place the output of this function inside larger RMarkdown documents.

**Comment by cderv** [comment]
This issue is related to the way **rmarkdown** is getting the metadata: it uses a yaml frontmatter only . It will only read meta from a top yaml header, and not yaml chunk inside the document. 

Pandoc however can handle metadata provided in several yaml blocks. That is why it works for fields used only by Pandoc. It does not work for fields that **rmarkdown** will use itself, like `bibliography`

Related to https://github.com/rstudio/rmarkdown/issues/1891

**Comment by cderv** [comment]
@bwiernik we finally made a change that should answer your need. Pandoc citation processing will now be enable also if `bibliography:` is in another yaml block in the document in this form: 
```yaml
bibliography:
  - reference_list.bib
```

**Comment by bwiernik** [comment]
Awesome thank you!
