### ISSUE TITLE
Is it possible render Jupyter notebook?

### ISSUE THREAD

**Issue by Jiang-Li** [rstudio/rmarkdown#1370]
I tried to convert the Jupyter Notebook to markdown, but the RStudio Viewer cannot show the tables. The converted html has the same issue when it is opened by RStudio's Preview. Is there any way I can render the Jupyter notebook? I want to publish the document to RSconnect. 

I use the R 3.5 and RStudio 1.1.453.

Thanks!

**Comment by Jiang-Li** [comment]
Sure. 

1. Create a Jupyter Notebook, sample.ipynb, with the following code 
![image](https://user-images.githubusercontent.com/16505805/41423381-2fb05f8e-6fc9-11e8-8223-4dda99dbf419.png)

2. Convert the notebook to markdown by

```
jupyter nbconvert --to markdown sample.ipynb
```

3. Open the sample.md file in RStudio and Preview it
![image](https://user-images.githubusercontent.com/16505805/41423511-811fb5d6-6fc9-11e8-8c06-655b55bb1998.png)

**Comment by yihui** [comment]
So it seems the table generated in the Jupyter note book was actually an HTML table. [You only provided screenshots instead of actual reproducible examples](https://yihui.name/en/2018/01/screenshots-vs-text/) (files), and my guess is that the HTML code for the table was indented by at least four spaces. Pandoc treated the indented content as verbatim code blocks, so you see raw HTML code in the HTML output from Markdown.

That is not an issue of **rmarkdown**. The Markdown file was not generated from **rmarkdown** but `nbconvert`, so it is more of a `nbconvert` issue. It will work if the table is generated using the (Pandoc's) Markdown syntax instead of HTML, or if the HTML code is not indented.

**Comment by Jiang-Li** [comment]
Thanks, @yihui . It is good to know the indentation issue. I removed the leading space from md file and Preview works.

```
sed "s/^[ \t]*//" -i sample.md
```
