### ISSUE TITLE
`output:  powerpoint_presentation:` generates an unreadable pptx file when I use `reference_doc:` with my template

### ISSUE THREAD

**Issue by AndreaPi** [rstudio/rmarkdown#1371]
I'm using the new Powerpoint output feature of R Markdown, so I made sure to get all the latest versions of R Studio, R Markdown and Pandoc:

```r
> rstudioapi::versionInfo()
$citation

To cite RStudio in publications use:

  RStudio Team (2018). RStudio: Integrated Development for R. RStudio, Inc., Boston, MA URL http://www.rstudio.com/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{RStudio Team}},
    organization = {RStudio, Inc.},
    address = {Boston, MA},
    year = {2018},
    url = {http://www.rstudio.com/},
  }


$mode
[1] "desktop"

$version
[1] ‘1.2.735’

> 

> rmarkdown::pandoc_version()
[1] ‘2.2.1’
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] it_IT.UTF-8/it_IT.UTF-8/it_IT.UTF-8/C/it_IT.UTF-8/it_IT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     crayon_1.3.4     assertthat_0.2.0 withr_2.1.2      digest_0.6.15    rprojroot_1.3-2  R6_2.2.2        
 [8] backports_1.1.2  reprex_0.2.0     magrittr_1.5     evaluate_0.10.1  rlang_0.2.1      stringi_1.2.2    rstudioapi_0.7  
[15] callr_2.0.4      whisker_0.3-2    rmarkdown_1.10   devtools_1.13.5  tools_3.5.0      stringr_1.3.1    processx_3.1.0  
[22] compiler_3.5.0   clipr_0.4.0      memoise_1.1.0    htmltools_0.3.6  knitr_1.20      
```

However, when using my company reference template for Powerpoint presentations, pandoc throws an error. I'm not sure I can share the template here, since it's company IP (I can include the error code, though, if that helps). However, I managed to get a "nearly" reproducible error by using another template (a free one), with which Pandoc doesn't throw an error, but still the generated `.pptx` file is unreadable. Here's the MRE:

````
---
title: "test"
author: "Anonymous"
date: "`r Sys.Date()`"
output: 
  powerpoint_presentation:
    reference_doc: test.pptx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1
## R Markdown

This is an R Markdown document.

```{r cars}
summary(cars)
```

# Section 2
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
````
The `test.pptx` file is [here](https://github.com/rstudio/rmarkdown/files/2103619/test.pptx), while [these images](https://github.com/rstudio/rmarkdown/files/2103639/images.zip) show what happens when I try to open the generated `output.pptx` file.

**Comment by rich-iannone** [comment]
@AndreaPi I tried this out with your provided `test.pptx`. While I didn't see a Pandoc error, the resulting Powerpoint document was determined to be not openable and beyond any repair that MS could do:

<img width="504" alt="powerpoint_repair" src="https://user-images.githubusercontent.com/5612024/41561759-c3da7706-7318-11e8-8a36-496a15e0e54c.png">

I think the real issue here is that the template .pptx doesn't have master slides with at least these names:

  - Title
  - Section header
  - Title and content
  - Two Content

I know it's a custom template but you'll have to rename some of the master slides to get this to work (and possibly, the names have to `fit` with the elements of those master slides). FYI I was able to get the .Rmd to work with a .pptx that was derived from one of the included Powerpoint templates.

More information can be found here:

https://support.rstudio.com/hc/en-us/articles/360004672913-Rendering-PowerPoint-presentations-with-RStudio 

I'm going to close this issue but do let us know if there are further problems.

**Comment by AndreaPi** [comment]
@rich-iannone thanks a lot for the blog link, I hadn't seen it! You say

> you'll have to rename some of the master slides to get this to work (and possibly, the names have to fit with the elements of those master slides)

what do you mean when you say that the names have to fit with the elements of the master slides? Do you mean that, for example, the **Title** master slide should be called **Title** (of course), have a placeholder for title and placeholder for subtitle? I don't think I have to _name_ the single placeholders, right?

**Comment by rich-iannone** [comment]
@AndreaPi I don't think the placeholders need to be named (they just have placeholder text) but rather Pandoc's Powerpoint support uses simple logic to deduce where should be placed in those particular master slides.

My advice for using a custom template is to work with one of the shipping templates and modify to appearance while making periodic .Rmd tests.
