### ISSUE TITLE
Some Javascript (plotly) interactive elements not showing up once compiled

### ISSUE THREAD

**Issue by DominiqueMakowski** [rstudio/rmarkdown#1379]
My [website](https://dominiquemakowski.github.io/) is built using rmarkdown. Unfortunately, some of the plots were interactive (using `plotly::ggplotly`  on a ggplot plot), and I had a [slickR](https://github.com/metrumresearchgroup/slickR) carousel widget. They worked perfectly when compiled until a few months ago: when I rebuilt the website (using `rmarkdown::render_site(encoding = "UTF-8")`), they stopped showing (and I had to deactivate them). 

When I run them in Rstudio, they show correctly and no error is thrown upon compilation. 

I haven't made any major change that could have break it... Would you have any idea why these are not showing? Note that another "interactive" widget, done with [wordcloud2](https://github.com/Lchiffon/wordcloud2) works correctly.

**Comment by cderv** [comment]
This issue is quite old. Sorry for not answering earlier. 



As we don't have a clear reproducible example showing a potential issue, I'll close. If you still have some problems, you can ask for help on https://community.rstudio.com, and if you found an issue with rmarkdown, please reopen. 

Thank you !
