### ISSUE TITLE
rmarkdown Parametrized reports vignettes 

### ISSUE THREAD

**Issue by wolski** [rstudio/rmarkdown#1398]
Hello,

Me working on a package which does implement a few rmarkdown parametrized reports. I did wanted them easily checked when building the package and therefore included them into the vignette folder.

To this task I am initializing the parameters with default values in the YAML section by:
```
params:
  configuration:  !r get(data(skylineconfig))
  data: !r get(data(sample_analysis))
```

And everything seemed (see below) to work fine.
```
devtools::build_vignettes() 
```

builds the vignettes with NO error. The .Rmd file, html file and corresponding
.R files are being placed into the inst/doc directory.

However, when I did want to check the package by running `devtools::check(build_args="--no-build-vignettes")`

The following warning is shown:

Warning: parse error in file
```
'C:/Users/wolski/AppData/Local/Temp/Rtmp4QanHv/SRMService.Rcheck/SRMService/doc/tr_srm_summary.R':
/Users/wolski/AppData/Local/Temp/Rtmp4QanHv/SRMService.Rcheck/SRMService/doc/tr_srm_summary.R:2:22:
unexpected '<'
1: params <-
2: list(configuration = <
```
This is how the start of the .R file produced from the vignette looks like.
```
params <-
list(configuration = <environment>, data = structure(list(protein_Id =
c("CiRT standards",
```

I am worried that this is the end of my road with parameterized vignettes then?

regards
Witek

**Comment by yihui** [comment]
@dmurdoch has already been helping you in the mailing list (and I have been watching the thread): http://r.789695.n4.nabble.com/Parametrized-Vignettest-in-R-packages-td4750738.html When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread instead of keeping different people busy in different places. Thanks!

Anyway, please try the canonical package development approach, i.e. `R CMD build` and `R CMD check`. You shouldn't need `devtools::build_vignettes()`. If you have to call it anyway, you need to clean up the `*.R` and `*.html` by-products before checking the package.

**Comment by wolski** [comment]
Thank you, Talk to you on r-devel. Have a great evening.
