### ISSUE TITLE
Powerpoint bullets default as level 2

### ISSUE THREAD

**Issue by timdisher** [rstudio/rmarkdown#1418]
It looks as if the markdown powerpoint output defaults bullets as second level (i.e. indented) in powerpoint. I am trying to create templates for use for commonly used slide decks, but as it stands we would have to go back and manually indent bullets back to level 1

````
---
title: "Untitled"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

```{r pressure}
plot(pressure)
```
````

**Comment by rich-iannone** [comment]
You're right. It does indent to the second level and there is not currently a way to choose the indentation level or the type of bullet. This is something that may be addressed at a later time.

The Powerpoint support for R Markdown is for the most part handled by pandoc. There are a few open issues dealing with Powerpoint output at [`jgm/pandoc`](https://github.com/jgm/pandoc/issues). Could you file this issue there? I'll close the issue here since it cannot really be addressed.

**Comment by rich-iannone** [comment]
@timdisher I will transfer this issue (and the other one) myself. There needs to be a minimal code example that's suitable for an issue posted in `jgm/pandoc`.

**Comment by rich-iannone** [comment]
@timdisher This is now posted in https://github.com/jgm/pandoc/issues/4828.
