### ISSUE TITLE
Filtering admin docs to create custom recipes

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rmarkdown#1437]
In order to run R in production, it's important that IT/Ops departments have recipes (i.e. scripts) that describe how to install and configure R and RStudio. But IT/Ops doesn't know R and they don't invest much time reading our admin guides, so often these scripts do not get written. Furthermore, the admin guides have many sections that don't apply to individual customers. If IT departments had an easier way to grok our admin guide by focusing only on the sections that mattered to them, they would be able to write a recipe that was specific to their needs.

Today's admin guide is a bookdown document made up of 9 R Markdown docs. I would like an easy way to filter only the sections I choose and produce a new document specific to my interests. This filtered document will then be used to create recipes for installing and configuring RStudio.

**Comment by rich-iannone** [comment]
@yihui I pointed @nwstephens and @kellobri toward the idea of child documents (at https://yihui.name/knitr/demo/child/) but it's not quite what they're looking for. We wondering if you've given thought to something like per-section includes (so that an assembly script could build a bookdown book by chapter and also by section).

The other idea is to have a full bookdown document and some interface to filter content down to the section level and possibly re-build a book from the selection.

**Comment by nwstephens** [comment]
@yihui is it possible to select content by section header? One thought was to tag headers and then extract the sections we want. (Pandoc does uses `slide-level` with the PowerPoint output to structure the presentation and the IDE builds a navigation hierarchy based on headers, so there must be ways of navigating the document structure.)
