### ISSUE TITLE
support `html_preview` in `md_document()`

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/rmarkdown#1521]
`html_preview` is a very useful feature of `github_document()`, I hope `md_document()` can also support it.

**Comment by cderv** [comment]
I think `md_document` does not support html preview because it does not make assumption on what html rendering to do. It just does md document.
`github_document` has a html preview because github markdown has a markdown rendering system to html and rmarkdown is trying to reproduce the way github does. 

For `md_document` it would be required to choose an html rendering, with a css associated, one that is not github rendering but a more standard one maybe... 🤔 Do you have some hint on that ?

I suppose switching to `github_document` rendering when you want a html preview is not enough ? 
Has you can have several format in the same rmarkdown, it could be a way to have the preview when developing and switch to classic when final rendering.
```r
---
title: "My Doc"
date: "`r Sys.Date()`"
output:
  md_document: default
  github_document:
    html_preview: true
---
```

**Comment by cderv** [comment]
I wonder if maybe pandoc default conversion to html is enough for a preview. 
I think this should be something not so difficult to implement as an option.

**Comment by yihui** [comment]
Here is what I do personally:

```yaml
output:
  html_fragment: default
  md_document: default
  # other possible formats...
```

I'd use `xaringan::inf_mr()` to preview the document, so I don't need to click the Knit button. I use `html_fragment` because it generates the absolutely minimal HTML (no styling at all, hence gives the fastest preview).

I'm not really interested in adding `html_preview` to `md_document`. The gain seems to be too small compared to the potential effort (in particular, the various decisions to make).

Thanks!
