### ISSUE TITLE
Can't use classoption for beamer_presentation

### ISSUE THREAD

**Issue by MCM-Math** [rstudio/rmarkdown#1541]
The navigation bar for my beamer presentation is sprawling off the page, so I am trying to use "classoption: compress":

> output:
>   beamer_presentation:
>     keep_tex: true
>     theme: "Darmstadt"
>     colortheme: "orchid"
>     classoption: compress
>     slide_level: 3
>     fonttheme: "professionalfonts"

I gave up on keeping this thread from messing up the indentation of the code, as I have work to do, but you should get the idea.  Just please keep that in mind before you try to test it verbatim.

However, I get the error:

> Error in (function (toc = FALSE, slide_level = NULL, incremental = FALSE,  : 
>   unused argument (classoption = "compress")
> Calls: <Anonymous> -> create_output_format -> do.call
> Execution halted

**Comment by yihui** [comment]
Reasons why am I closing this issue:

1. Apparently you ignored the issue template when creating the issue, because I have explained clearly how to format your issue correct. You seem to simply deleted the template without reading it.
1. https://yihui.name/en/2018/05/github-issue-format/
1. https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-options
1. https://yihui.name/en/2017/11/thanks-tj-mahr/

You have reported many issues in several repositories that I maintain. I always appreciate bug reports and feature requests, but please take a minute to read the documentation. I really wish not to see reports that simply due to failure to read a help page. In this case, if you take a look at `?rmarkdown::beamer_presentation`, you will realize `classoption` is _not_ an argument of the output format `rmarkdown::beamer_presentation`. Please don't blindly try arbitrary options. If you have read the documentation, and confused by anything in the documentation, please let us know and we can try to clarify.

If you don't know which help page to look at, please also read the documentation on the basics of R Markdown: https://bookdown.org/yihui/rmarkdown/output-formats.html

**Comment by MCM-Math** [comment]
Okay, so can you add the option to beamer_presentation?  Also, where do you say what arguments there are for beamer_presentation?  I checked the web pages.

**Comment by yihui** [comment]
Beamer is a LaTeX format. Most Pandoc top-level YAML options for LaTeX apply to Beamer. See bullet 3 above, and then consult the Pandoc manual (as bullet 4 suggested).
