### ISSUE TITLE
Do not display “NULL” functions in Rmarkdown output

### ISSUE THREAD

**Issue by Biostat44** [rstudio/rmarkdown#1572]
I want to print the results of two functions with Rmarkdown. These functions operate under certain conditions. If the conditions are not satisfied, the function returns NULL, but I don't want NULL to be written in the output of Rmarkdown. Can you help with this?
The sample code is given below.

---
title: "Untitled"
author: "Biostat44"
date: "19 Nisan 2019"
output: word_document
---

```{r setup, include=T}
l=NROW(iris$Sepal.Length)

  
  if(l<=50){
    shapiro.test(x =iris$Sepal.Length )
  }else{
    return(NULL)
  }
  
  if(l>50){
   ks.test(x = iris$Sepal.Length,"pnorm")
  }else{
    return(NULL)
  }

```
l=NROW(iris$Sepal.Length)

  
  if(l<=50){
    shapiro.test(x =iris$Sepal.Length )
  }else{
    return(NULL)
  }
## NULL
  if(l>150){
   ks.test(x = iris$Sepal.Length,"pnorm")
  }else{
    return(NULL)
  }
## 
##

**Comment by cderv** [comment]
I think you can just to nothing
````
---
title: "Untitled"
author: "Biostat44"
date: "19 Nisan 2019"
output: html_document
---

```{r}
l = NROW(iris$Sepal.Length)


if(l <= 50){
  shapiro.test(x =iris$Sepal.Length )
}

if(l > 50){
  ks.test(x = iris$Sepal.Length,"pnorm")
}
```
```` 

This will only print the result of the second `if`. Rmarkdown will print everything that results of a chunk. You need to get a result in adequation with the printing part afterward. If results is `NULL`, it will print NULL, unless you deal with something like if is NULL then print nothing (`""` or like here nothing as no result at all)

Also, for this kind of question, do not hesitate to ask on https://community.rstudio.com instead of Github Issue. There is a large community ready to help there and Github issue are more suited for issues with the 📦  or feature request.  

Hope it helps.

**Comment by yihui** [comment]
@Biostat44 Please do not ignore the issue template next time. Thanks!
