### ISSUE TITLE
pagetitle metadata inserted as pandoc argument prevents setting title dynamically

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1607]
While working on this [community question](https://community.rstudio.com/t/use-r-object-in-title-of-flexdashboard/35847/2), it was discovered that a prior fix in rmarkdown was maybe a bit too strong. 

With pandoc, it is possible to use several yaml metadata blocs to define variables. Not only the one at the top. This [pandoc feature](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block)

However, if not title is set in the top header block, a `pagetitle` var is set to the name of the document
https://github.com/rstudio/rmarkdown/blob/227d2e15173e3e3b3f6eeb063bc17009253a2fb3/R/html_document_base.R#L112-L113
using `--metadata` overwrites any other definition in the document (in a later block)

That is causing a strange behavior :

This works 
````
---
output: html_document
---

```{r setup, include=FALSE}
my_title <- "I am the title"
```
---
title: '`r my_title`'
---

Test R Markdown HTML
```` 
but `pagetitle` variable is set anyway to the name of the document (and not the title)

This does not work 
````
---
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
my_title <- "I am the title"
```
---
title: '`r my_title`'
---

Test R Markdown flexdashboard
```` 
because flexdashboard currently use only `pagetitle`, that is set by Rmarkdown to the input utf8 filename. 
I opened rstudio/flexdashboard#226 to propose a more consistent use of `title` instead of `pagetitle`

Anyway, I think setting `--metadata pagetitle=` if no title is in the yaml header is a bit too strong as it overwrites. 

I would suggest two options
* use `--metadata-file` and a tmp yaml file to set this option because this does not overwrite any other definition (see [Pandoc Manual](https://pandoc.org/MANUAL.html#option--metadata-file))
* Change parsing in Rmardown to all yaml block to be correct with extension [yaml_metadata_block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) and get all the metadata define in a md document. 

First one seems easy. Second one could have more impact but would be more relevant to adjust pandoc behavior. 

What do you think ?

**Comment by pooranis** [comment]
I too am running into a similar problem just trying to render a regular Rmd file as a static `html_document`. Perhaps hardcoding the pagetitle in this fashion is too strong?   I did not set a title in my YAML metadata block, and instead tried to set the just the pagetitle in the `pandoc_args` parameter (`pandoc_args = c("--metadata", "pagetitle=My page title"`), but it did not work as expected.  Because the metadata is being passed twice to pandoc, I get an error:

```
/usr/local/bin/pandoc +RTS -K512m -RTS example.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output example.html --email-obfuscation none --self-contained --metadata 'pagetitle=My page title' --variable 'theme:NULL' --standalone --section-divs --template default.html --highlight-style tango --include-in-header /var/folders/77/jxdfj2654nb77n514r5kpj24wy7nnt/T//Rtmpfm1oeV/rmarkdown-strd5b915fb3d4d.html --metadata pagetitle=example.utf8.md --lua-filter /usr/local/lib/R/3.6/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/local/lib/R/3.6/site-library/rmarkdown/rmd/lua/latex-div.lua 
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'example.utf8'
```

Also, if you do not set the title in the YAML block, and instead pass the title as a pandoc metadata argument (`pandoc_args = c("--metadata", "title=My title")` , the default pandoc behavior of setting the title as the pagetitle is broken (this is kind of the problem @cderv has as well - the title is being set in a manner not seen by `render`, `parse_yaml_front_matter`, and by extension the output_format).

It's also confusing because you set some default metadata in a YAML block anyway (see below), and it appears @cderv second suggestion of parsing all yaml blocks already works (maybe not in flexdashboard, though???), so you wouldn't need to set the pagetitle anyway, since pandoc can use the title from this default metadata block, and the user can override according to the pandoc documentation using `--metadata` or their own YAML block  higher up in the file.
https://github.com/rstudio/rmarkdown/blob/1e0964cb7a690866699fd10b41f42b32ea7f32b3/R/render.R#L403-L414

**Comment by yihui** [comment]
@cderv I thought about this issue for an hour and decided to revert the PR #1355, so your PR #1608 will be unnecessary. I think the PR #1355 was indeed too aggressive. Thank you!

**Comment by cderv** [comment]
This is one of solution !  Glad my investigation and suggestion helped you decide.

**Comment by yihui** [comment]
It helped a lot---it made me see a deep rabbit hole (patch a patch / hack a hack), which I definitely do not want to step into :)

**Comment by atusy** [comment]
Just for a future reference, pandoc 2.8 has a support for default option settings via a YAML file.
If any subtle problem arise due to missing a title or a pagetitle, and if we can wait RStudio to bandle Pandoc 2.8 or later, then default option settings can be a solution.
https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L360-L372
