### ISSUE TITLE
Rendering html document with pkgdown template

### ISSUE THREAD

**Issue by maksymiuks** [rstudio/rmarkdown#1618]
Hi

I have following problem. My package is supppsoed to create html vignette. Preprocessed .Rmd file is included along with files of my package and i want to render it in my function. Is there a way to render that vignette with pkgdown template? If so, how should I pass the path to? I've tried to use html_document() but it didnt work out.

Issue posted here aswell https://github.com/r-lib/pkgdown/issues/1103

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I am not sure to get correctly what you want to do. Pkgdown should build the vignette for you for your website. Is that not working ? 

Otherwise, I understand also that you want to render a vignette in your 📦 like an article in a pkgdown website, but independently of the website ? is that so ?

In pkgdown, the vignettes are rendered with [`build_article`](https://pkgdown.r-lib.org/reference/build_articles.html).

You can look into those function to see how it is done. There is a special pandoc template and I think the theme is applied with the global css theme from pkgdown. 

Can you detailed more what you want to achieve ? 
I don't think this is a rmarkdown issue.
You could ask to https://community.rstudio.com, there is a broader audience there and people who know well pkgdown and rmarkdown. You could get some ideas there.

**Comment by cderv** [comment]
Also please cross link the issue when you are asking in several place. 
This is a duplicate of https://github.com/r-lib/pkgdown/issues/1103

**Comment by maksymiuks** [comment]
Nono. My issue is completly independent from building vignettes. One of the functions in my package creates report for the user, based on values he's passing. That report is being created  from preprocessed .Rmd file. Now I want to create that report using template form pkgdown, since my organisation does not have his own Rmarkdown theme, only tempalte dedicated for pkgdown.

**Comment by cderv** [comment]
In this case, this is a definitely a question for community.rstudio.com. 
Depending on how you build your company pkgdown template, you shoud be able to use a css and html template to build a vignette with the same look. 
`html_document` function as a `template` argument to change the default, and you can provide `css` argument also to customize the look. 
Maybe someone in the community has already done something like that, you should really ask there.

**Comment by maksymiuks** [comment]
Thanks You for your attention. Accrding to your advise, I've posted the question at community.rstudio.com. Will edit that comment with a solution if somone provide me one.

Here is the link in case someone gets there in the future.
https://community.rstudio.com/t/rendering-html-document-with-pkgdown-template/37122
