### ISSUE TITLE
PDF in R - R markdown

### ISSUE THREAD

**Issue by brunorf21** [rstudio/rmarkdown#1633]
I am new in R. I am trying to use R markdown to create a pdf file, but i have this message:
teste_2 is the .Rmd file that I am trying to create the pdf file.

processing file: teste_2_pdf.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: cars
  |..............................................                   |  71%
  ordinary text without R code

  |........................................................         |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code

output file: teste_2_pdf.knit.md

"C:/Program Files/RSTUDIO/bin/pandoc/pandoc" +RTS -K512m -RTS teste_2_pdf.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output teste_2_pdf.tex --template "C:\Users\u3xv\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" 
! Sorry, but C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\pdflatex.exe did not succeed.

! The log file hopefully contains the information to get MiKTeX going again:

!   C:/Users/u3xv/AppData/Local/MiKTeX/2.9/miktex/log/pdflatex.log

! You may want to visit the MiKTeX project page, if you need help.

Erro: Failed to compile teste_2_pdf.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See teste_2_pdf.log for more info.
Além disso: Warning message:
execução do comando '"pdflatex" -halt-on-error -interaction=batchmode "teste_2_pdf.tex"' teve status 1 
Execução interrompida

**Comment by cderv** [comment]
Hi, 
did you follow the debugging tips ? What is in the log ? 
 
There is something that could be not right in your latex compilation. I don't think this is an Rmardown issue. You can ask this kind of question on https://community.rstudio.com - there is a broader range of people ready to help you. 
Without log here, it is difficult to know what is happenning.

You could also be interested to use TinyTex distribution instead of MikTex
https://yihui.name/tinytex/
It is lighter and works quite fine with Rmarkdown.

**Comment by Nelson-Gon** [comment]
This is a rather common issue that has unfortunately not been solved. I have looked at several posts, tried TinyTex but couldn't get it to install. It complains about me having a second TeX engine although I actually don't. 
The only (auto)solved RStudio Community issue on the same also suggests installing TinyTex(suggestion also by [cderv](https://community.rstudio.com/t/miktex-2-9-installation-giving-errors/41432/3).  Perhaps there might be a way to detect 2.9 automatically instead of 1.9? It seems editing startup variables doesn't help either.

**Comment by RodrigoPLpz** [comment]
**I had the same problem:**
My version OS: windows 10
and RStudio: Version 1.2.1335

> I installed tinytext package and it was solved the issue:

```
install.packages('tinytex')
tinytex::install_tinytex()
```
