### ISSUE TITLE
Inserting a code chunk inside a table cell in a Rmd file?

### ISSUE THREAD

**Issue by jhelvy** [rstudio/rmarkdown#1655]
Hi, I'm trying to create a table in a RMarkdown document that has a code chunk in one of the table cells. To my knowledge, this is not possible, so I thought I'd put a request in to support this capability. It would be particularly nice for explanatory documents to be able to put a code chunk and text explaining it side-by-side in a tabular structure. 

I can certainly put inline code using the `` symbols inside a table cell, but not an entire, multi-line code chunk. For example, in-line code works fine to produce a markdown table:

```
header1 | header2
--------|--------
`code`  | text
```

But what if you want to put a code chunk in the lower-left corner instead of inline code? Say for example you have the following chunk and you want it in one of the table cells:

````
```{r}
2 + 2
3 + 3
```
````

I have no idea how to achieve this. I've also put this on [SO](https://stackoverflow.com/questions/58035899/is-it-possible-to-put-an-rmarkdown-chunk-inside-a-table-cell-in-a-rmd-file?noredirect=1#comment102473705_58035899)

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by atusy** [comment]
Use grid tables documented here https://pandoc.org/MANUAL.html#tables

**Comment by jhelvy** [comment]
Yeah, that looks promising, except that it won't work with a code chunk. For example, if I entered this: 

````
--------------------------------
    Code       Text block 
----------- --------------------
```{r}      Here's some text
2 + 2       explaining the code
3 + 3       chunk on the left
```
--------------------------------
````

I get this:

Code | Text 
------|-------
`{r} 2 + 2 3 + 3`| Here's some text explaining the code chunk on the left

But what I want is for the code chunk to execute as a chunk, so I want this:

Code |      Text block 
------|-----------------
`4`    | Here's some text explaining
`6`    |  the code chunk on the left

Except that I would expect the code chunk on the left to all be on the same row, as well as the text on the right. I don't think this is supported, but it would really great if it was. 

Even if the code chunk doesn't execute (i.e. it's just written with code formatting using the ``` symbols) that would be an improvement, but even that doesn't seem possible.

**Comment by atusy** [comment]
For code blocks, as I said, you need to use grid tables rather than multiline tables
e.g.,

````
+----+-----+
|col1|col2 |
+====+=====+
|``` |foo  |
|a   |     |
|b   |     |
|``` |     |
+----+-----+
````

For chunks, you are right it is not supported even by grid tables.
This is due to `knitr`'s parser, and I don't think it will be supported in the future because the update requires drastic change.

**Comment by jhelvy** [comment]
Ah, my mistake - I looked at the wrong thing. It's too bad code chunks aren't supported - it would be a really cool feature. 

But if a code block can be handled, then there does at least seem to be some potential to support r code chunks, albeit as you said probably after some drastic changes. If you can run the code chunk and then insert the results in a grid table as a code block, then that might work. In fact, for now that's what I'm going to do - I'll just use two code blocks: one for the r code, and then one showing the results of it. It's a hack, but it'll work. Like this:

```
+----+-------+
|col1|col2   |
+====+=======+
|``` |input  |
|2+2 |       |
|3+3 |       |
|``` |       |
+----+-------+
|``` |output |
|4   |       |
|6   |       |
|``` |       |
+----+-------+
```

**Comment by atusy** [comment]
If the output format is HTML, I'd recommend using CSS Flex Layout or CSS Grid Layout instead of table.
https://dr-harper.github.io/rmarkdown-cookbook/multi-column-layout.html

About the `knitr`'s support, it is not easy because `knitr` detects chunk based on regular expressions.
In addition, to be more consistent with Pandoc's Markdown, we have to consider chunk in other block elements.
For example, code blocks can be used with block quotes and lists like below, but chunks cannot be used there.

````md
- This is a list 
- ```
  This is a code block in the list
  ```

> This is a block quote
> 
> ```
  This is a code block in the block quote
  ```
````

**Comment by jhelvy** [comment]
I see...yeah, supporting code chunks would be pretty hard. 

Thanks for the suggestion about using CSS to create the side-by-side. I was trying to find a solution for a pdf output, but it might actually work to just use a html output and then "print" it from the browser to a pdf. Again, a hacky solution, but probably sufficient for my needs.

**Comment by atusy** [comment]
Ah hah PDF... that's quite tough... I am not familiar with TeX and have no good workarounds.
Anyway, good luck with your documentation!!

**Comment by yihui** [comment]
@atusy was correct that this feature would be too hard to implement in **knitr**, and we have decided not to support it due to our very limited resources.

@jhelvy Yes, if the HTML format works, one option to get PDF is to print from the browser. `pagedown::chrome_print()` can help you automate this job.

Thanks for the ideas anyway!
