### ISSUE TITLE
R Markdown Ioslides --- non-accessible HTML output

### ISSUE THREAD

**Issue by cgrudz** [rstudio/rmarkdown#1663]
### System details

RStudio Edition : Desktop
RStudio Version : 1.2.5001
OS Version      :  Ubuntu 18.04.3 LTS
R Version       :  3.4.4 (2018-03-15)

### Steps to reproduce the problem
Use the default Ioslides template as generated when opening a new R Markdown presentation.  Use the Knit to HMTL option.  I have used the WAVE (http://wave.webaim.org/) accessibility check to determine the following issues in the HTML output.

### Describe the problem in detail

1. By default, there is no ```lang``` attribute included in the opening ```<html>``` tag of the document.  This is an issue for screen readers. 

2.  On the title slide, in the absence of a sub-title, the template generates an empty ```<h2>``` tag of the form,
```{html}
<h2 data-config-subtitle><!-- populated from slide_config.json --></h2>
```
Empty headings cause issues for screen readers.

3. By default, plots generated by an R script do not include an ```alt``` attribute for the image automatically.  This can be seen in the slide with a plot of pressure versus temperature, which does not have an ```alt``` attribute when generated by Knitr from the default template.  The ```alt``` text is important for visually impaired; while it is difficult to automatically generate a relevant ```alt``` text for an arbitrary plot, it would be a useful addition if the user can define an ```alt``` attribute in the Markdown prior to rendering in HTML.

### Describe the behavior you expected

Fixing the above accessibility issues would be greatly helpful in making Ioslides a simple-to-use option for academic presentations and lectures which are to be shared with students.  Currently, making these presentations accessible requires manually adjusting the above in the HTML output.

**Comment by jooyoungseo** [comment]
Hello @cgrudz,

I am a blind R user and I would like to chime in if you don't mind.

> 1. By default, there is no lang attribute included in the opening <html> tag of the document. This is an issue for screen readers.

Actually, missing language tag does not necessarily cause accessibility issue. Assistive technology such as screen reading software uses lang tag as a semantic sign to switch between an appropriate speech synthesizer for a multi-lingual document.

When not assigned, screen reader utilizes a local language of the user by default which is no problem in most cases.

If your slides are multi-lingual, you can implement any native html code for that certain areas in your document.

> 2. On the title slide, in the absence of a sub-title, the template generates an empty <h2> tag of the form,
> 
> <h2 data-config-subtitle></h2>
> 
> Empty headings cause issues for screen readers.

I agree with you. This has to be fixed. When subtitle is not specified by user in YAML metadata, the `<h2>` tag should be ignored internally.

> 3. By default, plots generated by an R script do not include an alt attribute for the image automatically. This can be seen in the slide with a plot of pressure versus temperature, which does not have an alt attribute when generated by Knitr from the default template. The alt text is important for visually impaired; while it is difficult to automatically generate a relevant alt text for an arbitrary plot, it would be a useful addition if the user can define an alt attribute in the Markdown prior to rendering in HTML.

I totally understand your point; however, there is a way to provide an alt text for R-generated plots.

For example, you can provide an R plot chunk with `fig.cap` option like below:

````
```{r, fig.cap = "Histogram of Ozone in blue."}
hist(airquality$Ozone, col = "blue"}
```
````

As you pointed out, `knitr` does not auto-generate an alt text; however, I think human-generated alt text could give more contextual information rather than any machine-learning algorithm.

Furthremore, recently Google Chrome auto-generates an alt text for graphic elements for assistive technology, and popular screen readers such as JAWS and NVDA have their own ways to OCR graphic elements to address the situation where an alt text is not offered manually.

Thus, I do not think `knitr` needs to auto-generate alt text for R plots; rather, a creator of the R chuncks and plots should provide contextual alt text. That makes more sense.

**Comment by cgrudz** [comment]
@jooyoungseo, thanks!  The advice is really helpful.  At University Nevada we are trying to make all of our teaching content accessible and I have been pushing folks to adopt R Markdown for their mathematical typesetting.  I wasn't aware of the fig.cap keyword argument, that solves quite a bit.  Cheers!

**Comment by jooyoungseo** [comment]
My PR #1735 addresses the empty `<h2>` tag issue for empty subtitle. I am not convinced with other accessibility issues pointed out here, so I think we can close this issue if you (@yihui) find that my PR looks okay.

**Comment by yihui** [comment]
Sounds good. I just merged the PR. Thanks for the discussion and helpful tips!
