### ISSUE TITLE
“Not Found” error when deploying to shinyapps.io, whereas app deployed well hours ago, and still does locally

### ISSUE THREAD

**Issue by pablobernabeu** [rstudio/rmarkdown#1714]
[UPDATED: Please find comment below]

Hi all,

I would be very grateful if I could receive some help with a 'Not Found' error that I and another user have encountered, only over the last days, when deploying Flexdashboard-Shiny apps to the shinyapps.io server. Would you please find the **initial issue [on the community](https://community.rstudio.com/t/not-found-error-when-deploying-to-shinyapps-io-whereas-app-deployed-well-hours-ago-and-still-does-locally/46029/2)**.

**The error may be reproduced** by deploying a Flexdashboard-Shiny (`runtime: shiny`) app such as [this one](https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/) to the shinyapps.io server.

Since this error has emerged only over the last two days for myself, and I think it's the same for the other user who commented on my Community post, I've tried to spot any relevant, recent releases to CRAN. The RMarkdown package seems to have been updated these days, indeed with changes around Shiny (https://github.com/rstudio/rmarkdown/commit/d4d2a8fbc71c321baf55840e9967d438ab2f2c0a). I would be really grateful if someone could test this issue by deploying any Flexdashboard-Shiny app (e.g., from [the examples](https://rmarkdown.rstudio.com/flexdashboard/examples.html)) to the shinyapps.io server. 

Cross-posting: https://github.com/rstudio/shiny/issues/2715. I'll take care of updating and closing all posts as soon as the issue has been resolved.

Thank you very much!

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by pablobernabeu** [comment]
**Updated:**  I tried installing the previous version,

```require(devtools); install_version("rmarkdown", version = "1.17", repos = "http://cran.us.r-project.org")```

deployed my app, and the error vanished! 🎆

**Comment by cderv** [comment]
I can confirm this happened in this commit 5bb98e1ab0c1f305b9f796bbd8efe572b0a8f31c

When you install from the previous commit then deployed, the app works
```r
devtools::install_github("rstudio/rmarkdown@1e0964cb7a690866699fd10b41f42b32ea7f32b3")
```
But if you install the faulty commit, you get the error after deploy. 

This is a bug in Rmarkdown, but I don't know how shinyapps.io is running the dashboard  with `rmarkdown::run(...)`

Will try to investigate from the changes introduce in https://github.com/rstudio/rmarkdown/pull/1703 but it will be easier from someone from the shinyapps team I guess.

**Comment by pablobernabeu** [comment]
Thank you for the confirmation!

**Comment by everron** [comment]
Hello everyone, 

This issue seems to happen not only on shinyapps.io but also on a dockerised flexdashboard. 

Here are the steps to reproduce : 
I have saved this [flexdashoard](https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/) as test.Rmd and built a docker image using this Dockerfile : 

```
FROM rocker/r-ver:latest

RUN apt-get update \
  && apt-get install -y --no-install-recommends  \
  pandoc \
  && . /etc/environment \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/ \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

RUN install2.r --error \
    -r "https://cran.rstudio.com"\
    flexdashboard \
    shiny \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

COPY . /root

EXPOSE 3838

CMD ["R", "-e", "rmarkdown::run('/root/test.Rmd', shiny_args = list(port = 3838, host = '0.0.0.0'))"]
```
After saving the Dockerfile and the test.Rmd in the same folder, I am able to build the image using : 
`docker build -t flextest .` and running the container after the build  `docker run -d -p 3838:3838 flextest` 

The flexdashboard should be available at http://localhost:3838/ . You will see the "Not Found" error instead.

I can confirm than when installing the previous commit : `devtools::install_github("rstudio/rmarkdown@1e0964cb7a690866699fd10b41f42b32ea7f32b3")` 
(as a new docker image or inside the already existing container), fixes this problem.

**Comment by cderv** [comment]
Thanks @everron ! This will help a lot for debug.  👍

**Comment by aronatkins** [comment]
RStudio Connect and shinyapps.io use `rmarkdown::run(file = NULL, dir = "...content-location...", ...)` when executing R Markdown documents with `runtime: shiny`.

**Comment by aronatkins** [comment]
This problem is occurring because we are passing an absolute path to `rmarkdown:::rmarkdown_shiny_ui` in `rmarkdown::run`. 

https://github.com/rstudio/rmarkdown/blob/cf8e5df1b309edc9d75e610f9c52c451588c302b/R/shiny.R#L146-L150

When the `/` path is requested, we use the default file path and then attempt to resolve as a relative path to the application directory.

https://github.com/rstudio/rmarkdown/blob/cf8e5df1b309edc9d75e610f9c52c451588c302b/R/shiny.R#L315-L317

https://github.com/rstudio/rmarkdown/blob/cf8e5df1b309edc9d75e610f9c52c451588c302b/R/shiny.R#L327-L331

The `rmarkdown:::resolve_relative` function wants the "file" to be a relative path beneath the directory.
https://github.com/rstudio/rmarkdown/blob/cf8e5df1b309edc9d75e610f9c52c451588c302b/R/shiny.R#L454-L470

**Comment by yihui** [comment]
Thanks @cderv and @aronatkins! I'll investigate this issue and try to fix it today. Sorry for the trouble!

**Comment by aronatkins** [comment]
This logic is applied to `file` but probably should also be applied to `default_file`:
https://github.com/rstudio/rmarkdown/blob/cf8e5df1b309edc9d75e610f9c52c451588c302b/R/shiny.R#L106-L110

**Comment by yihui** [comment]
Should be fixed now. Thank you all!

**Comment by pablobernabeu** [comment]
Thank you!

**Comment by aronatkins** [comment]
@yihui Any thoughts about when this will land on CRAN? We continue to see folks hitting this "Not Found" error when deploying Shiny R Markdown documents.

**Comment by yihui** [comment]
@aronatkins I'll try this week. I'm close to the frequency limit of CRAN release now, so I need to be a little more careful this time (the fact that CRAN started to use Pandoc 2.8 has made it even more challenging).

**Comment by yihui** [comment]
FYI **rmarkdown** v2.0 is on CRAN now.

**Comment by slopp** [comment]
@aronatkins we still have customers complaining that this issue isn't resolved - were we able to validate a fix on Connect?

**Comment by aronatkins** [comment]
@slopp I have confirmed that documents using rmarkdown-2.0 (current CRAN release) successfully execute on shinyapps.io and RStudio Connect. Documents using rmarkdown-1.18 (prior CRAN release) deploy but encounter the "Not Found" error when executed.

There are many other reasons for an HTTP 404 Not Found error. Do you have example documents?

**Comment by slopp** [comment]
Phew! That is a relief @aronatkins, thank you! 

@rstub is in touch with the partner who reported the problem and may be able to dig up further details.

**Comment by melissagwolf** [comment]
I'm still running into the same Not Found issue.  If I want to make sure I pull a specific version of RMarkdown, would it be:

`RUN R -e devtools::install_version("rmarkdown", version = "2.0.0", repos = "http://cran.us.r-project.org")"`

In my Dockerfile?
