### ISSUE TITLE
header-includes may lead to `Error ...  invalid 'description' argument`

### ISSUE THREAD

**Issue by RLumSK** [rstudio/rmarkdown#1722]
## Observation

With 'rmarkdown' 1.18 (and also the newer version available via GitHub), running the following code (CV template using the package 'vitae') 

````rmd
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
email: "Marie.Curie@ens.fr"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
header-includes:
  - \usepackage{newunicodechar}
  - \newunicodechar{‑}{-} %this fixes wrong dash input inputs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(kableExtra)
``` 

# Test

* Test
````

drops the following error message:

```
Error in file(file, ifelse(append, "a", "w")) : 
  invalid 'description' argument
Calls: <Anonymous> -> <Anonymous> -> cat -> file
In addition: Warning messages:
1: In if (file == "") file <- stdout() else if (startsWith(file, "|")) { :
  the condition has length > 1 and only the first element will be used
2: In if (startsWith(file, "|")) { :
  the condition has length > 1 and only the first element will be used
Execution halted
```

The error is **not** observed if: 

1. 'rmarkdown' 1.17 is used 
2. `library(kableExtra)` is removed
3.  No header is included via `header-includes`

## Remarks

I've tried a couple of variants to understand the cause of this issue better, but I have to admit I do not fully understand what is going on. I think that it has something to do with changes introduced for `header-includes` in 'rmarkdown' 1.18 (since it works without any problem for version 1.17). I also looked up the source code, but I cannot see how things are connected. 

## Session info

```
R Under development (unstable) (2019-11-07 r77386)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6, RStudio 1.2.5019

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  base64enc_0.1.3 digest_0.6.23   evaluate_0.14   glue_1.3.1      graphics_4.0.0  grDevices_4.0.0 highr_0.8       htmltools_0.4.0
  jsonlite_1.6    knitr_1.26      magrittr_1.5    markdown_1.1    methods_4.0.0   mime_0.7        Rcpp_1.0.3      rlang_0.4.2    
  rmarkdown_1.18  stats_4.0.0     stringi_1.4.3   stringr_1.4.0   tinytex_0.17    tools_4.0.0     utils_4.0.0     xfun_0.11      
  yaml_2.2.0     

Pandoc version: 2.8.0.1

```

---

By filing an issue to this repo, I promise that

- [X] I have fully read the issue guide at https://yihui.org/issue/.
- [X] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for the report. Here are my steps of investigations

If I remove `library(kableExtra)` in your reprex, I do not get the error. So there is _thing_ between the interaction of `rmarkdown` 1.18, `vitae` and `kableExtra`

What happens when you load `kableExtra`  in a document that uses latex is that is load a set of latex packages . See in [onLoad](https://github.com/haozhu233/kableExtra/blob/master/R/zzz.R) and [`usepackage_latex`](https://github.com/haozhu233/kableExtra/blob/745e545d0c679013cda0d4b68a2df820287a9d52/R/util.R#L25). So `kableExtra` will add a few _latex dependency_ to be recognize as so by Rmarkdown. 

`rmarkdown` will found those dependencies and add them in the header. 
https://github.com/rstudio/rmarkdown/blob/07a0ca4c3b8a11cbaf3c8050fe2064b91de2f0b8/R/pdf_document.R#L172-L176
Recent changes in Rmarkdown will had those headers to include in a file, pass to pandoc through `--include-in-header"`. So basically in your example, there will be two files: 
* one with content from `header-includes` field in yaml
* another when you load kableExtra with the latex dependencies required. 

Here is the third interaction with `vitae` now. `cv_document` format (from which awesomecv is based upon) has a [`pre_processor` function](https://github.com/mitchelloharawild/vitae/blob/91ad4db8d947066bfd376f6e9c115a6625af1427/R/cv_document.R#L18). this fonction will also try to detect the latex dependencies and will try to append them to the file pass as `--include-in-header`. See this [lines](https://github.com/mitchelloharawild/vitae/blob/91ad4db8d947066bfd376f6e9c115a6625af1427/R/cv_document.R#L43-L56)
It will detect args with this : 
```r
 if ("--include-in-header" %in% args) {
      header_file <- args[which(args == "--include-in-header") + 1]
    }
```
and try to append new content using
```r
cat(header_contents, sep = "\n", file = header_file, append = TRUE)
```

The issue is that `header_file` can be of length > 1 when there is several `--include-in-header` args to pandoc call but `file` argument in `cat` can only deal with one file. 

I think the issue is in `vitae` 📦 mainly to adapt to new way of doing from Rmarkdown. The other way would be that Rmarkdown use only one `--include-in-header` file but technically someone can add some more as `pandoc_args` if required and the issue would still be there in `cv_document` pre processor. 

@mitchelloharawild, if I may ask, what do you think of this one ?

**Comment by RLumSK** [comment]
@cderv Wow, this is a very detailed investigation for a, probably, very rare effect. Thanks for it, it reads very interesting (I learnt a lot) and I am sure it will lead to a solution.

**Comment by yihui** [comment]
You are such an excellent sleuth, @cderv.

@mitchelloharawild The way you append to the `--include-in-header` file is not robust. Besides the possibility @cderv mentioned (there could be multiple `--include-in-header`), the file path could also be quoted when you retrieve it from the command-line arguments:

```r
if ("--include-in-header" %in% args) {
    header_file <- args[which(args == "--include-in-header") + 1]
 }
```

I have created a PR for your review: https://github.com/mitchelloharawild/vitae/pull/100

@RLumSK You may test it with `remotes::install_github('mitchelloharawild/vitae#100')`. Thanks!

**Comment by mitchelloharawild** [comment]
I agree that this is something that should be fixed in vitae.
Thanks for finding this and the PR @yihui.

**Comment by RLumSK** [comment]
@yihui @cderv @mitchelloharawild Thank you for all your efforts! I am sincerely impressed. I tested the new code and it works now with 'rmarkdown' 1.18. I had no doubt but after all your super fast responses the least I could to do was to test it again.
