### ISSUE TITLE
version 1.18 and 1.18.6 not knitting to PDF due to undefined control sequence

### ISSUE THREAD

**Issue by sjpierce** [rstudio/rmarkdown#1733]
After updating packages today, Rmd files that previously knitted properly to PDF files were no longer working because knitting ends up leading to an undefined control sequence in the .tex file:

>l.942   \file_get:nnN
{unicode-math-table.tex} {} \l__um_mathtable_tl 

My computer has MiKTeX 2.9 installed and fully updated. This behavior appears to be caused by changes made between rmarkdown version 1.17 and version 1.18. I have also tried using the latest development version (1.18.6), but that gives the same result as version 1.18. 

```
> library(rmarkdown)
> xfun::session_info()  # Under setup that fails
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362), RStudio 1.2.5019

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252   

Package version:
  base64enc_0.1.3  compiler_3.6.1   digest_0.6.23    evaluate_0.14    glue_1.3.1       graphics_3.6.1   grDevices_3.6.1 
  highr_0.8        htmltools_0.4.0  jsonlite_1.6     knitr_1.26       magrittr_1.5     markdown_1.1     methods_3.6.1   
  mime_0.7         Rcpp_1.0.3       rlang_0.4.2      rmarkdown_1.18.6 stats_3.6.1      stringi_1.4.3    stringr_1.4.0   
  tinytex_0.18     tools_3.6.1      utils_3.6.1      xfun_0.11        yaml_2.2.0
```

Uninstalling rmarkdown and reverting to the older version as shown below fixes the problem (knitting creates PDFs as expected). 

```
remove.packages("rmarkdown")
devtools::install_version("rmarkdown", version = "1.17", repos = "http://cran.us.r-project.org")
```

The following minimal Rmd code reproduces this problem on my computer. 

```
---
output:
 pdf_document:
   latex_engine: xelatex
---

Knitting this file produces a PDF file properly when rmarkdown 1.15 or 1.17 is 
installed, but fails when version 1.18 or 1.18.6 are installed instead. Then 
knitting generates an undefined control sequence.    
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
A change in rmarkdown 1.18 was the use of pandoc latex template instead of rmarkdown own template. pandoc templates are now patched as it was easier to maintain, and closer to pandoc features. You can generate the `tex` file and see what is inside. Have you already look at it ? 
You can use `keep_tex` argument in `pdf_document` or use `rmarkdown::latex_document()` to generate the tex file only as output. Then you'll be able to see if this tex file can correctly be rendered by your MikTex or not. 

From what I see, Pandoc latex template includes the use of unicode-math 
https://github.com/jgm/pandoc-templates/blob/8ece4d6de88408e8464ed245723cfda258b4fdc9/default.latex#L111
It may not have been present in Rmarkdown own template before. This latex package is required for building pdf with pandoc. See the requirements : https://pandoc.org/MANUAL.html#creating-a-pdf

Can you look at that in you MikTex installation ? 

And FWIW, TinyTex works really well with Rmarkdown !

**Comment by yihui** [comment]
I just installed MiKTeX on Windows and tested your example, but I was unable to reproduce the error with either v1.18 or the Github version. Then I searched for a while, but no one seems to have a solution:

- https://github.com/mitchelloharawild/vitae/issues/48
- https://github.com/mitchelloharawild/CV/issues/2
- https://stackoverflow.com/q/55137760/559676
- https://github.com/posquit0/Awesome-CV/issues/302

If it is not too much trouble for you, I'd suggest you install TinyTeX and retry:

```r
tinytex::install_tinytex()
```

**Comment by sjpierce** [comment]
Neither installing the unicode-math package in MiKTeX nor uninstalling and then re-installing MiKTeX from scratch solves the problem. I still see the same behavior under the same conditions. 

It looks like the pandoc requirements may include some packages that simply don't exist in MiKTeX. Or at least, they are not listed as available within its console package manager. Unless some of those requirements are recent changes to pandoc, it surprises me that I had things working fine before.  

I've tried removing MiKTeX and installing TinyTeX. That appears to be a viable solution. I can at least get the example above to compile. Another script I tried knitting had to be tweaked before it would work with TinyTeX (it had worked fine under MiKTeX). I'll try testing more of my Rmd files and see how that goes. 

Am I correct that developers of rmarkdown, knitr, and pandoc are largely using TeX Live (from which TinyTeX is derived) and thus those tools get tested with that setup more than other LaTeX distributions?

**Comment by yihui** [comment]
> Another script I tried knitting had to be tweaked before it would work with TinyTeX (it had worked fine under MiKTeX).

If possible, I'd like to figure out the cause of that problem and try to fix it on TinyTeX's side, so you won't need any tweaking.

> Am I correct that developers of rmarkdown, knitr, and pandoc are largely using TeX Live (from which TinyTeX is derived) and thus those tools get tested with that setup more than other LaTeX distributions?

I can't speak for other developers (in particular, Pandoc's authors), but I use TinyTeX myself. However, that doesn't mean we only support TinyTeX/TeX Live. We will always try our best to support other LaTeX distributions, including MiKTeX. In your case, if only I could reproduce the issue by myself, I'd try to figure out a fix. It is just that the problem is not reproducible on my Windows machine. If you want to help (I'll truly appreciate it), you can add the option `keep_tex: true` to the `pdf_document` output format in YAML. Then compile the document with rmarkdown 1.17 and 1.18, respectively, and compare the `.tex` files generated by the two versions of rmarkdown. See what the differences are. We might be able to figure out the cause of the failure in 1.18. Thank you!

**Comment by sjpierce** [comment]
I'll gather and share some materials to help, but it might be a few days due to some looming deadlines I can't put off. 

Support for other LaTeX distributions is appreciated and has worked smoothly for me quite a while. I was just speculating that in a probabilistic sense, switching to the distribution preferred by the developers of key packages seems like the best long-term bet for avoiding unpleasant surprises caused by package updates. Presumably, the developers will personally run into the most obvious/common/likely issues themselves during development and pre-release testing and just fix them before release... :)

In any case, I love the  combination of R, rmarkdown, knitr, pandoc, and LaTeX. It's made reproducible research much easier. Thanks for creating such fantastic tools.

**Comment by Flocksofseagull** [comment]
Thanks for posting this sjpierce. I think I encountered this issue while trying to generate a report that is run monthly, while using MikTeX 2.9 as well. If this needs a separate error report, please let me know.

Error:
> ! LaTeX Error: Command `\circ' already defined.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.36 ...MathSymbol{\circ}          {2}{matha}{"05}

Falling back from rmarkdown 1.18 to 1.17 resolved the issue. Installing TinyTex and going back to 1.18 still throws the same error. tlmgr did install unicode-math, to no effect. It doesn't seem to like: `(Temp,\(^\circ\)C)`. I am wondering if it is what is specified in the report document header for `usepackage{mathabx}`. While on 1.17 if I add `usepackage{unicode-math}` OR comment out the mathabx line, I get an error `! Package mathspec Error: 'amsmath' must be loaded earlier than `mathspec'.`. But if I comment out mathabx, it appears to create the pdf just fine on 1.18 with TinyTex. Unicode-math appears to not matter.

Doing this in my original document has some strange behavior though. My original document gives a new error, but the test document (which just has an excerpt of text that calls for that degree symbol) does not:
> ! xdvipdfmx:fatal: Unable to open "Nov_Quarterly.pdf".
> 
> ! No output PDF file written.
> 
> ! fwrite: Broken pipe
> 
> ! xelatex.exe: 
> 
> Error: Failed to compile Nov_Quarterly.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Nov_Quarterly.log for more info.
> Execution halted

And even stranger, this error followed when falling back to rmarkdown 1.17 and enabling `mathabx`. Trying to knit it a few times it finally worked for some reason. I don't know how replicate-able it is, since while trying to replicate it again with rmarkdown 1.18 gave another new error, instead of the broken pipe error (again looks related to the degree symbol, `Temp ($^\\degree$C)` is used in table headers, and `(Temp,$^\circ$C)` is used in table titles):
> ! Undefined control sequence.
> \degree ->\ERROR 

I have three tex files I can supply: 1) working on rmarkdown 1.17 with `mathabx` enabled and using TinyTex, 2) not working with \circ error, on 1.18 with `mathabx` enabled and using TinyTex, 3) working on 1.18 with `mathabx` disabled and using TinyTex, butt he .tex files for both 1.18 attempts look identical apart from mathabx missing, so I don't think you need 3. Thanks for what you've done with TinyTex, I haven't heard of it until now, but it looks great.


My session:
> > xfun::session_info('rmarkdown')
> R version 3.6.1 (2019-07-05)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 10 x64 (build 17134), RStudio 1.2.1568
> 
> Locale:
>   LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
>   LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> Package version:
>   base64enc_0.1.3 digest_0.6.23   evaluate_0.14   glue_1.3.1      graphics_3.6.1  grDevices_3.6.1 highr_0.8       htmltools_0.4.0
>   jsonlite_1.6    knitr_1.26      magrittr_1.5    markdown_1.1    methods_3.6.1   mime_0.7        Rcpp_1.0.3      rlang_0.4.2    
>   rmarkdown_1.18  stats_3.6.1     stringi_1.4.3   stringr_1.4.0   tinytex_0.18    tools_3.6.1     utils_3.6.1     xfun_0.11      
>   yaml_2.2.0     
> 
> Pandoc version: 2.7.2

**Comment by yihui** [comment]
@Flocksofseagull I added `(Temp,\(^\circ\)C)` to an Rmd document but was still unable to reproduce your problem. Do you have a minimal reproducible Rmd example? It will also be helpful if you could provide the .tex files you mentioned. Thank you!

**Comment by Flocksofseagull** [comment]
My reproducible rmd is below, and attached. And attached are the 2 tex files.
[test_circ.txt](https://github.com/rstudio/rmarkdown/files/3968671/test_circ.txt)

[test_circ_117.txt](https://github.com/rstudio/rmarkdown/files/3968658/test_circ_117.txt)
[test_circ_118_fail.txt](https://github.com/rstudio/rmarkdown/files/3968659/test_circ_118_fail.txt)

```
---
title: "test Report"


fontsize: 11.5pt
geometry: margin=2cm
output:
  pdf_document: 
    keep_tex: yes
    latex_engine: xelatex
  word_document: default
mainfont: Arial
header-includes:
- \usepackage{dcolumn}
- \usepackage{array}
- \usepackage{siunitx}
- \usepackage{fontspec}
- \usepackage{upgreek}
- \usepackage{mathabx}
- \setmainfont{Arial}
tables: yes
documentclass: article
---

\pagenumbering{gobble} 
\sisetup{%
  mode = text,
  detect-family = true,
  detect-weight = true,  
}

\newpage
\large
\textbf{\\
Table 3.8
}\par
Summary of water quality parameters for each sample date. Densities of total coliform (Total), fecal coliform (Fecal) and \emph{Enterococcus} (Entero) bacteria are reported as CFU/100 mL; the fecal:total coliform ratio (F:T) is unitless; values for temperature (Temp,$^\circ$C), transmissivity (XMS, $\%$), dissolved oxygen (DO, mg/L), salinity (Sal, ppt) and pH were extracted from CTD profile data for depths closest to those at which the bacteriological samples were collected.  Comments follow the data summary.
```

**Comment by sjpierce** [comment]
@yihui I created a set of four Rmd files, named reprex_a.Rmd through reprex_d.Rmd and knitted each of them on the same computer, varying only the version of rmarkdown installed (1.17 vs 1.18) and whether I am using MiKTeX or TinyTeX to compile the .tex file into a PDF. 

The only difference in the .Rmd files is the body text that tells you which scenario the file was compiled under and whether it works or fails at creating a PDF on my computer. 

- reprex_a.Rmd under rmarkdown 1.17 with MikTeX works properly. 
- reprex_b.Rmd under rmarkdown 1.17 with TinyTeX works properly.
- reprex_c.Rmd under rmarkdown 1.18 with MikTeX fails to create a PDF because of an undefined control sequence: l.942   \file_get:nnN  {unicode-math-table.tex} {} \l__um_mathtable_tl 
- reprex_d.Rmd under rmarkdown 1.18 with TinyTeX works properly.

I am attaching a ZIP file with the .Rmd, .tex, .log, and .pdf files associated with each of them. 
[reprex_files.zip](https://github.com/rstudio/rmarkdown/files/4022246/reprex_files.zip)

Hopefully these materials will help you identify what changes would make the software better work with MiKTeX.

**Comment by jaredlander** [comment]
Just got the same error using `{bookdown}` version 0.17 with `{rmarkdown}` version 2.0 and MikTeX. Previously I was on `{rmarkdown}` version 1.17 with no problems.

I tried knitting multiple individual chapters using both `rmarkdown::render_site()` and `bookdown::preview_chapter()` and am getting the same error. None of the chapters I tried to knit contained any math, however, in my LaTeX preamble I use the following LaTeX packages.

- booktabs
- imakeidx
- placeins

**Comment by yihui** [comment]
@jaredlander I have tried several times but haven't been able to reproduce the issue on my own machine using any of the examples above. If you are going to rstudio::conf next week, be sure to catch me there and I really want to fix this issue. BTW, please also make sure you have updated all packages in MiKTeX. Thanks!

**Comment by jaredlander** [comment]
I'll be there (speaking Wednesday I think) and I'll have a booth. You can use my laptop to see it in action.

I don't think I've ever manually updated MikTeX packages but I should be able to figure that out. On the other hand, if that solves the problem we won't be able to identify the culprit, so maybe I won't update yet.

I have a docker image for this repo (haven't rebuilt the image in months though). If I can recreate the problem in the image I'll give you access to that too.

**Comment by cderv** [comment]
@jaredlander did you see my earlier comment https://github.com/rstudio/rmarkdown/issues/1733#issuecomment-564431799 ? I would like to confirm or not the hint of being pandoc requirement related.

Your issue appears with Rmarkdown 2.0, and [in this version](https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-20) it starts using pandoc default template for pdf, and no more custom template. `unicode-math` is one of the [requirement for pandoc](https://pandoc.org/MANUAL.html#creating-a-pdf)  if you use `lualatex` or `xelatex`(even if you don't explicitly use math). Is it already available into your MikTex installation ? 

I am curious to verify this. Can you check that you have this package available in your set of Tex 📦 ? 

I use TinyTex and not MikTex. If I remove this package, it gets installed again automatically by tinytex 📦 when rendering the document. I guess it should do the same with MikTex too. Does it happens for you too ? 

Thank you very much.

**Comment by jaredlander** [comment]
@cderv Back when I was using `{knitr}` to generate PDF tomes, LaTeX packages would install automatically, but not with `{bookdown}`.

I just installed `unicode-math` using the MikTex package manager on my computer and am still getting the same error. So now it's getting weirder.

**Comment by yihui** [comment]
Okay. Now I'm back from the rstudio::conf and want to report my findings. @jaredlander showed me the error on his laptop, which was real and like this:

```tex
! Undefined control sequence.
l.942 \file_get:nnN
{unicode-math-table.tex} {} \l__um_mathtable_tl
```

All I did to solve the problem was updating all LaTeX packages in MiKTeX. This is usually the first thing I do before I debug issues ([when in doubt, upgrade](https://yihui.org/en/2017/05/when-in-doubt-upgrade/)). At that moment, [MiKTeX had a packaging error](https://tex.stackexchange.com/q/526260/9128), which seems to have been fixed now. Other than that, everything worked fine.

I'm not sure if it is relevant, but I also deleted this directory on his computer:

```
tinytex:::win_app_dir('MiKTeX')
```

BTW, I also tested TinyTeX (i.e. `tinytex::install_tinytex()`) secretly on his computer and verified that it worked well, too. I had uninstalled it immediately after my test.

So I guess you all have to either update MiKTeX packages, or switch to TinyTeX. Both ways should fix your issues. Please let me know if you have further issues.

**Comment by jaredlander** [comment]
I take the blame for not updating ___all___ of my MiKTeX packages but I live in fear of updating anything involving LaTeX. Perhaps this will encourage me to be less worried.

On my next computer I might just go with TinyTeX and forgo MiKTex.

Thanks for handling my poor setup @yihui.

**Comment by sjpierce** [comment]
At the time of my earlier post (Jan 4th), I had completely uninstalled and reinstalled MiKTeX and updated all MiKTeX packages. My setup is now working with both MiKTeX and TinyTeX (I'm using most recent versions of R and R packages).

**Comment by yihui** [comment]
Great. I'm glad that we have finally solved the mystery!
