### ISSUE TITLE
knit_print of tibble includes HTML <div> and is slightly different from kable output

### ISSUE THREAD

**Issue by chrisothal** [rstudio/rmarkdown#1748]
I'm noticing that when I print a tibble and generate a PDF output, the intermediate markdown file has `<div class="kable-table">` surrounding the table. This seems to be the result of `knit_print.R` [line 22](https://github.com/rstudio/rmarkdown/blob/7fa4eb4b7cbf60b35404c3ecf35dfe0730301a46/R/knit_print.R#L22)? Normally this doesn't affect my output, however I'm trying to "hack" in table captions (and also use pandoc-crossref down the line). I'm rendering with the following call: `render("test.Rmd", output_format = pdf_document(df_print = "kable", keep_md = T))`

**test.Rmd**

``````
---
title: "test"
output: pdf_document
---

```{r}
library(knitr)
opts_chunk$set(echo = F, message = F, warning = F)
test_tibble <- tibble(a = letters[1:5], b = 1:5)
```

# Using print

```{r}
test_tibble
```
Table: Table caption 1 {#tbl:first}

# Using kable() to print

```{r}
kable(test_tibble, format = "markdown")
```
Table: Table caption 2 {#tbl:second}
``````

**Comment by cderv** [comment]
I think if you use the `df.print = "kable"` argument, it will apply to all chunk outputs that will print à data.frame. If you use yourself `kable` inside chunk, `df.print` will not apply. I understand you want to use tibble in your chunks, but having them printed as kable using the `df_print` option. Is that so ? 

The div added when using `df_print = kable` is useful to add scrolling behavior to kable outputs. I think it was the default behavior for html_notebook format before `paged_table` was added. This scrolling behavior can still be activated when using `df_print = kable` in yaml by adding `kable-scroll: true` as first level in yaml header to be passed as pandoc argument.

````
---
title: "test"
output: 
  html_document:
    df_print: kable
kable-scroll: true
---
````

About the "slightly different from kable output", i think it is because of the `knitr::kable` default format. You explicitly use `format = "markdown"` but by default, in an Rmd, `df_print = "kable"` will use `format = "pandoc"`, which indeed is slightly different. 

This div part should not be an issue for pdf output, but maybe you are trying to do something with md output ?
I am not sure what is the issue you are block with during your "hack", but I hope this explanation helps a little understand how it works here.

**Comment by atusy** [comment]
Here's a trick for you, @chrisothal 

````md
---
output:
  html_document:
    df_print: !expr function(x, ...) knitr::knit_print(knitr::kable(x, format = "markdown", ...))
---

```{r}
tibble::as_tibble(iris[1:3, ])
```
````

**Comment by cderv** [comment]
I don't think there is anything to change / do in **rmarkdown** reagrding this, and you have a trick shared above. I'll close this old issue then. 

Please feel free to reopen if this is still something painful in your production. Thanks !
