### ISSUE TITLE
Passing all *.bib files of given path to bibliography field in Rmd YAML

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1763]
I wish we had a way to list all `*.bib` files of any given path in `bibliography` field of `rmarkdown` YAML without having to pass every single bib file names manually.

[This StackOverflow Question](https://stackoverflow.com/questions/54277774/using-list-files-for-bibliography-field-in-rmd-yaml/54278990#54278990) and [This GitHub issue](https://github.com/jgm/pandoc/issues/5955#issuecomment-560446701) are related to this need.

Any ideas or plans to address this request?

**Comment by cderv** [comment]
I don't think there is indeed an easy way to provide a list of bib files programmatically. 

Pandoc field would expect a vector of bib file that you could generated using 
``` r
sprintf("[%s]", knitr::combine_words(file.path("bib",  list.files("bib", pattern = "(*.bib)$")), sep = ",", before = "\'", and = ""))
#> [1] "['bib/bookdown.bib','bib/knitr.bib','bib/rmarkdown.bib']"
```

````yaml
bibliography: `r sprintf("[%s]", knitr::combine_words(file.path("bib",  list.files("bib", pattern = "(*.bib)$")), sep = ",", before = "\'", and = ""))`
````

However, this would not be parseable by `yaml::read_yaml()` which is used in `rmarkdown::render()` and adding some quotes around the R inline expression as it is usually done won't work here. 

list syntax using yaml dash like this 
``` r
glue::glue_collapse(c("", glue::glue("  - {bibfile}", bibfile = file.path("bib",  list.files("bib", pattern = "(*.bib)$")))), sep = "\n")
#> 
#>   - bib/bookdown.bib
#>   - bib/knitr.bib
#>   - bib/rmarkdown.bib
```

````yaml
bibliography: `r glue::glue_collapse(c("", glue::glue("  - {bibfile}", bibfile = file.path("bib",  list.files("bib", pattern = "(*.bib)$")))), sep = "\n")`
````

Would also not work because inline R expression needs to be quoted to **yaml** package to parse without error. 

I believe this is because YAML header is read at least once before knitting happens to replace the inline expression. 

So I don't think there is an easy solution for this without integrated support. 

Unfortunately we are not handling directly this variable yet. This is a Pandoc metadata provided at first level that Pandoc will read directly. We could start handling it and support wildcard for example as ask in the Pandoc issue but that would create a processing that does not exist yet that could be source of issue we need to assess. 

Merging the bibfiles as suggested in SO answer (https://stackoverflow.com/a/54278990/3436535) is a nice workaround for now. 

Workaround in https://github.com/jgm/pandoc/issues/5955#issuecomment-560447838 won't apply easily either as this is rmarkdown which is creating the command line and passing custom flags through YAML will face the same issue as above. 


We'll try to consider this in the future. Thanks !

**Comment by yihui** [comment]
Here is a hack that should work:

```
bibliography: ["`r paste(list.files('.', '[.]bib$', full.names = TRUE), collapse = '", "')`"]
```

It's valid YAML in `.Rmd`, and will generate a valid YAML array in the intermediate `.md`, too. It may not be easy to understand at the first glance, but it's not that complicated:

1. First you write a YAML array in Rmd that provides the outer double quotes, which quote the inline R expression: `["`r expr`"]`;
2. Then the inline R expression writes out a YAML array that does not contain the leftmost and rightmost quotes, e.g., only `a.bib", "b.bib", "c.bib`. That basically means you concatenate the file paths with `", "`.

After you combine 1 and 2, you'll get the YAML array that you desire.
