### ISSUE TITLE
[Bug] Rmarkdown not working with the DiagrammeR package

### ISSUE THREAD

**Issue by prdm0** [rstudio/rmarkdown#1768]
Dear,

I am noticing that the **rmarkdown** and **bookdown** packages are not working well with the **Diagrammer** package. It seems to me to be a recent problem, since the problem did not occur months ago.

The code below will compile without generating problems and the HTML will be generated. When I open it I realize that all the content is correct, including the diagram built by **Diagrammer**, however the generated page is erased (approaching a transparent tone).

Does anyone know why this problem?

**Minimum Example**:

```
---
title: "Untitled"
author: "Author"
date: "05/02/2020"
output: html_document
---


# SECTION

Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test.

```{r diagramafluxo, echo = FALSE}
library(DiagrammeR)
mermaid("
graph TD

A((fa:fa-database DADOS))-->B((R))
B-->C(ORGANIZACAO DOS DADOS)
D(ESCOLHA DAS METODOLOGIAS)
C-->|Implementar|E((R))
D-->|Implementar|E
E-->F(ORGANIZACAO DOS RESULTADOS)
F-->|Frequente|G((Documento))

style A fill:#ffe5cc
style B fill:#ffe5cc
style C fill:#ffe5cc
style D fill:#ffe5cc
style E fill:#ffe5cc
style F fill:#ffe5cc
style G fill:#ffe5cc
")

# NEW SECTION
```
Best regards,
prdm0

---

By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.org/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I think the issue is with `mermaid.css`. This file will have this css part
```css
.section {
  stroke: none;
  opacity: 0.2;
}
```
However, `rmardown` html document output has already a class section for the div containing the content. That means mermaid.css is applying to the all document. 

For now you can set the css yourself in your document to override by adding a css chunk at the top of your Rmd file after the yaml
````r
```{css, echo = FALSE}
.section {
  opacity: 1;
}
```
````

I am not sure why mermaid css as such a broad selector... FWIW, the changes happened in DiagrammR in the last update to mermaid components. See the [diff](https://github.com/rich-iannone/DiagrammeR/commit/71b399f0b2ee2120fd6a07a4b597161b8ebb500f#diff-13bfe8ee97638c806083b06a420809c5R169). You'll see that in `mermaid.css`, opacity was set for `.mermaid .section` selector, that is now a broader `.section` selector. 

I think it worth open an issue in DiagrammR to see if the css could be improved or if they now why this changes happened. 

Hope it helps

**Comment by prdm0** [comment]
Dear @cderv  thanks for the suggestion. I will test and see if it solves the problem temporarily. I will return to inform if it worked.

And yes, I believe that the error must be with the **DiagrammeR** package. I will open a discussion on the **DiagrammeR** project.

Best Regards.

**Comment by prdm0** [comment]
Dear @cderv, I created a file **style.css** and introduced the code:

```
.section {
  opacity: 100;
} 
```
My problem was solved but I don't think it would be necessary to do that. The introduction of diagrams using DiagrammeR should not cause profound changes in a project. I opened the topic in the DiagrammeR project and I hope that this will be resolved quickly by them.

Thanks.

**Comment by cderv** [comment]
FWIW, this has been fixed in DiagrammeR in last dev version.

**Comment by prdm0** [comment]
Less of a problem. 

Best,
prdm0.
