### ISSUE TITLE
Suggestion: drop the smart parameter from output formats

### ISSUE THREAD

**Issue by atusy** [rstudio/rmarkdown#1774]
The output formats have the `smart` parameter (e.g., `html_document`).
This parameter is passed to `smart_extension` and adds `+smart` when `TRUE` and adds nothing when `FALSE`.

https://github.com/rstudio/rmarkdown/blob/43def55d9001ced4526988cfd6feacb11fa6a7dc/R/output_format.R#L349-L351

However, the `smart` extension is enabled by default in the Pandoc's markdown.

https://github.com/jgm/pandoc/blob/9feefa39319358acc84811e6017aeea60f9140c3/MANUAL.txt#L2627-L2628

This means, the `smart` extension is enabled regardless of the `smart` parameter (i.e., `html_document(smart = TRUE)` and `html_document(smart = FALSE)` cause the same result).

Thus, I suggest to drop smart parameter from the output formats.
By doing this, the user-specified `smart` parameter will be silently ignored as ellipsis.
If users really have to toggle the `smart` extension, they can do so via the `md_extension` parameter (i.e., `md_extension = "-smart"` disables the smart extension).
Currently, users have to specify both `smart=FALSE` and `md_extension="-smart"` to disable the `smart` extension.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
This can be a breaking change, but the fewer arguments we have to maintain, the better. So I just removed it. I think I'll need to tweak some functions to add the `...` argument as you suggested after I run revdep checks of **rmarkdown**. Thanks!

BTW, this may also affect Pandoc 1.x users. I can't say for sure, but Pandoc 1.x probably didn't enable the smart option by default (and one needs to specify `--smart` in command line; cf https://github.com/rstudio/rmarkdown/pull/1168). Since [Pandoc 2.0](https://github.com/jgm/pandoc/releases/tag/2.0) has been released for more than two years, I think it's worth dropping the support for this tiny feature.
