### ISSUE TITLE
`bibliography` and `csl` are ignored when provided as `pandoc_args`

### ISSUE THREAD

**Issue by salim-b** [rstudio/rmarkdown#1786]
Consider a (shared) `print.yaml` file which contains metadata fields intended to be passed to Pandoc like:

```yaml
lang: de-CH
papersize: a4
```

and then setting the `pandoc_args` option in the YAML front matter of an R Markdown document to the path of this separate file:

```Rmd
---
output:
  pdf_document:
    pandoc_args: print.yaml
bibliography: my_refs.bib
csl: my_style.csl
---

...
```

This works just fine.

But when I also move the `csl` and `bibliography` options to the external `print.yaml`, **they are suddenly ignored**.

IMHO this should be considered a bug.

---

My system:

```
> xfun::session_info('rmarkdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS, RStudio 1.2.5033

Locale:
  LC_CTYPE=de_CH.UTF-8       LC_NUMERIC=C               LC_TIME=de_CH.UTF-8        LC_COLLATE=de_CH.UTF-8     LC_MONETARY=de_CH.UTF-8   
  LC_MESSAGES=de_CH.UTF-8    LC_PAPER=de_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.3.2      graphics_3.6.3  grDevices_3.6.3 highr_0.8       htmltools_0.4.0 jsonlite_1.6.1 
  knitr_1.28      magrittr_1.5    markdown_1.1    methods_3.6.3   mime_0.9        Rcpp_1.0.4      rlang_0.4.5     rmarkdown_2.1   stats_3.6.3    
  stringi_1.4.6   stringr_1.4.0   tinytex_0.20    tools_3.6.3     utils_3.6.3     xfun_0.12       yaml_2.2.1     

Pandoc version: 2.9.2
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

As I don't have your files, it is not an example I can directly reproduce. It would have been better to have one. So I try to build mine. 

First, let's see if I understand correctly. You want to pass a shared yaml file containing metadata for Pandoc. If you want to use `pandoc_args` to do that, you need to pass command line options [from the doc](https://pandoc.org/MANUAL.html#options) as you would use them at command line with `pandoc`. To pass metadata in a file, I read you need to use `--metadata-file=<yaml or json>`. I think you are missing this part. Your command line is equivalent to `pandoc (...) print.yaml` and I think you need `pandoc (...) --metadata-file=print.yaml`
That would be why when you put `bibliography` and `csl` in your file they are not used, because not read as metadata to be used. 

Here is the small test I made to confirm this

### Won't use authors as metadata, so it won't be used in template

pandoc will see the yaml as text content it seems

````r
---
title: Test shared yaml
output:
  html_document:
    pandoc_args: test.yaml
---

```{cat, engine.opts=list(file = "test.yaml")}
date: 27/03/2020
author: cderv
```
````

<details><summary> HTML result </summary>

![image](https://user-images.githubusercontent.com/6791940/77732110-7bf42780-7004-11ea-9c74-67f90fbfd515.png)

</details>

### Will read the file correctly and use authors in template


You'll get date and author set in the HTML result as the template will be filled

````r
---
title: Test shared yaml
output:
  html_document:
    pandoc_args: --metadata-file=test.yaml
---

```{cat, engine.opts=list(file = "test.yaml")}
date: 27/03/2020
author: cderv
```
```` 

<details><summary>HTML Results</summary>

![image](https://user-images.githubusercontent.com/6791940/77732029-57984b00-7004-11ea-908a-4ffd44734692.png)

</details>

Hope it helps.
