### ISSUE TITLE
.tabset in markdown shows undefined options when hosted using Plumber 

### ISSUE THREAD

**Issue by Anshumank399** [rstudio/rmarkdown#1788]
By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

.tabset in markdown shows undefined options when hosted using _plumber_ 
---
Markdown report when hosted using `rmarkdown::render("Error Simulation.Rmd")` in plumber gives the extra tab options as _undefined_ as shown in the example image below. 

The basic structure of the code is given below.

Link to Error Simulation Code: [https://github.com/Anshumank399/Markdown-Error-Simulation](https://github.com/Anshumank399/Markdown-Error-Simulation)

Run it using: 

> plumb("plumber.R")$run()

The hosted markdown then shows the undefined bug. 

_This issue does not arise when a markdown is _knit_ or _render_ directly but only on exposing using plumber._

![example](https://user-images.githubusercontent.com/21052254/78098180-e558a980-73fb-11ea-92e4-23c9abb0ec30.jpg)

**Comment by cderv** [comment]
Hello, 

Per the issue guide you already checked the boxes, can you provide a reproducible example for us ? 
Without it, it is not really possible for us to check your issue and understand what could go wrong. 
See https://yihui.org/issue/#bug-reports

Thank you very much.

**Comment by Anshumank399** [comment]
@cderv  I have updated the bug-report with the code structure.

**Comment by cderv** [comment]
Can you follow the guide about formatting please ? 
A screenshot does not help to reproduce by downloading or copying.

To make the example reproducible, it must be easy for us :
- to get your get code
- follow the steps you'll describe so that we can reproduce

Take into account that I will open RStudio in a new empty project and I need to be able to rerun exactly like you to reproduce the issue. Currently I can't do that easily. 

Thank you in advance for helping us help you.

**Comment by Anshumank399** [comment]
> Can you follow the guide about formatting please ?
> https://yihui.org/issue/#please-format-your-issue-correctly
> A screenshot does not help to reproduce by downloading or copying.
> 
> To make the example reproducible, it must be easy for us :
> 
> * to get your get code
> * to follow the steps you'll describe so that we can reproduce on our side
> 
> Take into account that I will open RStudio in a new empty project and I need to be able to rerun exactly like you to reproduce the issue. Currently I can't do that easily.
> 
> Thank you in advance for helping us help you.

**Link to Code:**
[https://github.com/Anshumank399/Markdown-Error-Simulation](https://github.com/Anshumank399/Markdown-Error-Simulation)

**Here is the exact code:** 

**Error Simulation.Rmd**
> ---
> title: "Simulate Error"
> author: "Anshuman Dey Kirty"
> date: "2 April 2020"
> output: html_document
> ---
> 
> <br />
> 
> ## Title {.tabset}
> 
> ### January,20
> ```{r error=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
> 
> print("abc")
> 
> ```
> ### February,20
> ```{r error=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
> 
> print("abc")
> 
> ```
> ##

**plumber.R**

> library(plumber)
> library(rmarkdown)
> library(htmltools)
> 
> #* @apiTitle Report
> #* @html
> #* @get /v1/report
> function(res){
>   include_rmd(render("Error Simulation.Rmd"), res=res)
> }

**Run it using :** 

> plumb("plumber.R")$run()

**Error/Bug Image:** 
![Example](https://user-images.githubusercontent.com/21052254/78209789-a131db80-74c5-11ea-9bfc-f04b95622fe6.PNG)

**Comment by Anshumank399** [comment]
@cderv Were you able to emulate the bug?

**Comment by yihui** [comment]
You have been reminded twice to read the issue guide, but your last post above (https://github.com/rstudio/rmarkdown/issues/1788#issuecomment-607610428) was still incorrectly formatted, which prevents others from copying and running your example.

Anyway, you have provided a Github repo, which is great, and thanks for that! I didn't run your example, but I don't think you should call `rmarkdown::render()` in `plumber::include_rmd()`, because the help page `?plumber::include_rmd` says the file will be rendered through `rmarkdown::render()`. If you render it by yourself, you are essentially passing a rendered file (an `.html` file) to `plumber::include_rmd()`.

If that's not the problem, I can reopen the issue.
