### ISSUE TITLE
isolate() not behaving as designed in RMarkdown Shiny

### ISSUE THREAD

**Issue by leungi** [rstudio/rmarkdown#1790]
By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.org/issue/.
- [x ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

----
Not sure if this is a `rmarkdown` issue, or `shiny`, so posting it here as first shot.

### System details
``` r
> xfun::session_info('rmarkdown')
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134), RStudio 1.2.5033

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3      digest_0.6.25        evaluate_0.14        glue_1.3.1          
  graphics_3.6.2       grDevices_3.6.2      highr_0.8            htmltools_0.4.0.9002
  jsonlite_1.6.1       knitr_1.28           magrittr_1.5         markdown_1.1        
  methods_3.6.2        mime_0.9             Rcpp_1.0.3           rlang_0.4.4         
  rmarkdown_2.1.1      stats_3.6.2          stringi_1.4.5        stringr_1.4.0       
  tinytex_0.21         tools_3.6.2          utils_3.6.2          xfun_0.12           
  yaml_2.2.1          

Pandoc version: 2.9.1.1
```

<sup>Created on 2020-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Example application *or* steps to reproduce the problem
````R
---
title: "Untitled"
author: "Ivan Leung"
date: "4/4/2020"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#### Input
textInput(
  "text_in",
  "Text In",
  "Initial Text",
  placeholder = "Type Something"
)
```

```{r}
#### Output
r_val <- reactiveValues(text = NULL)

r_val$text <- isolate(input$text_in)
```

```{r}
print(isolate(r_val$text))
#> NULL
```

```{r}
print(isolate(input$text_in))
#> NULL
```

```{r}
renderPrint({input$text_in})
#> Initial Text
```
````
### Describe the problem in detail
Expected: output to be ` Initial Text`

- `renderPrint()` output as expected
- `isolate()` output `NULL`
- `isolate()` with `reactiveValues()` output `NULL`

**Comment by cderv** [comment]
I believe this is the expected behavior with current desing of **rmarkdown** regarding shiny evaluation. This other comment for another issue provides some hints to understand 
https://github.com/rstudio/rmarkdown/issues/2045#issuecomment-1006006218

When running a shiny Rmd document two things will happend (kind of interleaved)
* rendering UI to create a HTML file from the Rmd content
* running an app (using `runApp` of a `shinApp()`) as you would run a shinyApp.

So, the Rmd document will be render as usual Rmd document creating a HTML file with the content produced by text and chunk into the document. 

As said by @gadenbuie,  in the context of RMarkdown with a Shiny runtime, a `render*` function in a chunk essentially returns:
*  A placeholder where Shiny will put the output
*  A function that should be called at runtime to generate the output
This is a special behavior for the shiny app

However, all your previous chunk containing non really specific R code will be evaluated once during the rendering and in that step the `input` is NULL and the reactive value won't be set to what you expect. `isolate()` can be used in console and does not produce a HTML element for shiny - my understanding is that it is just a way to execute something without a reactive scope. So that will be executed during the rendering. 

The execution model of shiny document is not straightforward I recognize that! 😅 

For that you would need to delay the execution of expression to shiny app run time. Here is a modified example using `rmarkdown::render_delayed()` that will make an expression to be evaluated at run time and not rendering time! 

Try this: 
````markdown
---
title: "Untitled"
author: "Ivan Leung"
date: "4/4/2020"
runtime: shiny
output: html_document
---

```{r}
#### Input
textInput(
  "text_in",
  "Text In",
  "Initial Text",
  placeholder = "Type Something"
)
```

```{r}
# will change value as input change
renderPrint({input$text_in})
```

```{r}
# contains initial value and won't change later
# because of isolate()
rmarkdown::render_delayed({
  isolate(input$text_in)
})
```
````

You'll see that 

* chunk with `renderPrint()` will get its output change in the app as you modify the input
* chunk with `isolate()` will have its output fixed to the initial value of `input$text_in`, which in this case will not be NULL because we delayed the evaluation to the running phase of the app. 

I hope this explanation will be enough clear. Thanks for opening the issue because it lead me to dig further in the understanding of shiny Rmd document.
