### ISSUE TITLE
Update jQuery or apply the fix?

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rmarkdown#1814]
https://github.com/jquery/jquery/security/advisories/GHSA-gxr4-xjj5-5px2

https://cve.circl.lu/cve/CVE-2020-11022

https://github.com/jquery/jquery/security/advisories/GHSA-gxr4-xjj5-5px2

![image](https://user-images.githubusercontent.com/509878/80698340-5b5a3a00-8aa8-11ea-8045-085bb1ee86aa.png)

https://twitter.com/hrbrmstr/status/1255796874877046784?s=20

**Comment by cpsievert** [comment]
`jQuery.htmlPrefilter` was [added in jQuery 2.2.0](https://github.com/jquery/jquery/commit/225bde37c997f5ddd9fe00fdfb8e9a43545cfbbc) and `html_document()` is [still on 1.11.3](https://github.com/rstudio/rmarkdown/blob/e2ceb35c/R/html_dependencies.R#L22), so this isn't an **rmarkdown** issue. 

It's worth noting that we will bump to jQuery 3.x as a part of #1688...it will do so via [jquerylib](https://github.com/rstudio/jquerylib) which has already been upgraded to 3.5.0 on Github and a CRAN update will soon follow.

This could, of course, still be an issue today if you have some other widget bringing in a vulnerable jQuery version. We'll do our part to make sure packages that we maintain (e.g., **crosstalk**) are up-to-date, but we can't necessarily control what 3rd party packages are doing. That concern should largely go away though once #1688 is done (implying that all `html_document()`s will be on >= 3.5.0).

**Comment by cpsievert** [comment]
(@yihui feel free to close this issue)

**Comment by apreshill** [comment]
@cderv I added the next label here (thanks @michaelquinn32) so we make sure this ends up in the next rmarkdown release.

**Comment by cderv** [comment]
Currently we need JQuery in **rmarkdown** in a few place specifically when using `toc_float`, or for tabsets, code folding and source embed features. This is also included for bootstrap when `theme != NULL`. 

Side note: This is kind of a duplication because the two first requires the `theme` argument to be not NULL which will trigger the inclusion of bootstrap and JQuery. 

A mentioned above, let's recall that when using `theme` to use **bslib**, then the JQuery version used will be the one imported from **bslib** which is already updated. 
Example of YAML:
````yaml
output:
  html_document:
    theme: 
      version: 4 # or 3
````

These can be used already without any change in **rmarkdown**

We'll make the update for when **bslib** is not used.
