### ISSUE TITLE
Using a LaTeX package in HTML document

### ISSUE THREAD

**Issue by abuegho** [rstudio/rmarkdown#1829]
I'm trying to use a LaTeX package, knitting an HTML document

```
---
title: "assignment"
author: "author"
output: html_document
header_includes:
 - \usepackage{cancel}
---

$$
    \cancel{x}
$$
```
But cancel package is not being used for some reason. The advice I got on Stack Exchange only seemed to pertain to PDF knitting, so I'm not sure how I can get this working on an HTML output.

I'm running rmarkdown 2.1.1

Thanks,

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
You just can't use an latex package with HTML document and the `html_document` format. Header like `\usepackage{cancel}` is for tex document, in latex preamble for example. It would work for PDF output. 

For html document, you can only use Latex Math because it is supported by Pandoc parser with an activated extension (`tex_math_dollars`) and rendered by default using Mathjax . 

See 
* https://bookdown.org/yihui/rmarkdown/markdown-syntax.html#math-expressions
* https://bookdown.org/yihui/rmarkdown/html-document.html#mathjax-equations
* https://pandoc.org/MANUAL.html#math-rendering-in-html
* https://pandoc.org/MANUAL.html#extension-tex_math_dollars
* http://docs.mathjax.org/en/latest/index.html

That means you need to see if MathJax support the Tex package as an extension. 
It happens that it supports its. See http://docs.mathjax.org/en/latest/input/tex/extensions/cancel.html

they say you can then load the `cancel` extension in your Math Expression directly. Try
```md
---
title: "assignment"
author: "author"
output: html_document
---

$$
  \require{cancel}
  \cancel{x}
$$
```
You'll get this
![image](https://user-images.githubusercontent.com/6791940/83348905-a9c15980-a330-11ea-8fa1-af77d87fd9c5.png)

This won't work with any Tex package, but anything that MathJax supports can be used in Rmarkdown I think. 

Hope it helps

**Comment by abuegho** [comment]
Christophe, Thank you so much!
This worked perfectly!!

Fadi.
