### ISSUE TITLE
untested windows version 6.2 detected!

### ISSUE THREAD

**Issue by feilx** [rstudio/rmarkdown#1830]
---
I used rmarkdown on win10. Get error message as following:

-  ! LaTeX Error: missing \begin{docment}.
-  ! Qt:  Untested windows version 6.2 detected !

I can't solve this problem,though I've tried many ways. Do you have good suggestion ?

**Comment by feilx** [comment]
By the way, to solve the problem of Chinese output @hadley

**Comment by cderv** [comment]
Hello, 

Please can you follow the issue guide that was there when you opened your issue and that you deleted ? 

There would a very wide range of scenario that could lead to error. It would help us help you to have more information on the step you took that result in this issue. 

Thank you

**Comment by cderv** [comment]
@feilx We are focusing on **rmarkdown** this month and I would like to know if this is still something to look into that we should try to reproduce on our side. 

> ! Qt: Untested windows version 6.2 detected !

`Qt` reminds me of a technology used in RStudio IDE, I believe. If this issue is still there for you, does it happens only when rendering from RStudio IDE or also at command line with `rmarkdown::render()`. 

Thank you!
