### ISSUE TITLE
Can't find tools::vignetteInfo() on R < 3.6

### ISSUE THREAD

**Issue by krlmlr** [rstudio/rmarkdown#1831]
https://github.com/tidyverse/dbplyr/runs/727729099#step:9:30

`tools::vignetteInfo()` is available as of R 3.6.

**Comment by lorenzwalthert** [comment]
Given that {backports} re-implemented `vignetteInfo()` in https://github.com/r-lib/backports/pull/36, is it worth restoring previous functionality? We could also just use a plain `getFromNamespace("vignetteInfo", ns = "tools")`, which is what's done in https://github.com/r-lib/backports/pull/36.

**Comment by yihui** [comment]
@lorenzwalthert `vignetteInfo()` is used for a rather trivial feature in `html_vignette()` (i.e. warn against differences between vignette index entry and title), so I tend not to consider R < 3.6 for this specific feature. Thanks a lot for your suggestion!

**Comment by yihui** [comment]
Since the last released was made only about a week ago, I tend not to make a new release very soon. Normally I wouldn't consider new releases within a month of the last release, but if this problem is too much trouble, I can try to make the next release sooner (but still in one week or two: the main thing that holds me back is rmarkdown's thousands of rev deps to be checked).

So perhaps you'll have to do (B) for a couple of weeks. Sorry!

**Comment by hadley** [comment]
Please release as soon as possible; this is breaking a large number of workflows for us. 

If you make the smallest patch to fix this problem, you do not need to re-run all the revdeps (especially since CRAN will run them too). If you really do need to run them, you should talk to @jimhester about taking advantage of our cloud revdep tools so that you can run them all in a couple of hours.

**Comment by hadley** [comment]
Could we please get an update on the release process?

**Comment by yihui** [comment]
@hadley Sorry I was mostly offline in the past few weeks, and my hands have been extremely tightly tied. I'll try my best to make the new release as soon as possible, but as I said above, it would still be in one week or two. Besides, I have an existing CRAN issue about another package sent from BDR that I haven't completely resolved, so I feel very nervous about making any new CRAN releases at this time.

It might actually be easier for me if you tell me which packages are currently broken, and I send pull requests to you add `remotes::install_github('rstudio/rmarkdown')` to your Travis or GHA  configurations instead.

Apologies again for the trouble, and thanks for you patience and understanding!

**Comment by jimhester** [comment]
Every R package that uses rmarkdown on R < 3.6 is broken.

**Comment by hadley** [comment]
If you need help with the release, we can do it.

**Comment by yihui** [comment]
@jimhester Yes, I fully acknowledge that every R package that has vignettes with the output format `rmarkdown::html_vignette` on R < 3.6 is broken. It was my bad that I failed to realize that `tools::vignetteInfo()` was not exported until R 3.6. It was my bad that I didn't test lower R versions on Travis earlier. I'm extremely sorry for breaking your workflows. Please give me just a few more days to prepare the release. Thank you very much for your patience!

**Comment by yihui** [comment]
On CRAN now: https://cran.r-project.org/package=rmarkdown

**Comment by wch** [comment]
Thanks!

**Comment by jimhester** [comment]
Thanks for doing a off schedule release for this @yihui!
