### ISSUE TITLE
Check older R versions using CI

### ISSUE THREAD

**Issue by jimhester** [rstudio/rmarkdown#1838]
There was a recent change (https://github.com/rstudio/rmarkdown/issues/1831) that caused rmarkdown to fail on R versions older than 3.6.

This issue could have been caught before being released to CRAN if rmarkdown was being checked on older R versions using CI.

The tidyverse team does this to ensure our packages support the last 5 minor R releases, which is now R 3.3, 3.4, 3.5, 3.6 and 4.0

It would be great if we could do rountily have similar checks for the knitr / rmarkdown stack, to ensure we don't lose compatibility with these critical packages accidently in the future.

**Comment by yihui** [comment]
Yes, we should definitely do it. Thanks for the suggestion!

**Comment by cderv** [comment]
This could also be an opportunity to switch to GHA instead of Travis as now the new infrastructure and frameworks are more widely use. Then tests would have more OS and more R versions, maybe more pandoc version too... 
Could be done in several phases obviously. At the end, I think it is worthwhile.
