### ISSUE TITLE
ioslides: presentation window and main window getting out of sync.

### ISSUE THREAD

**Issue by sje30** [rstudio/rmarkdown#186]
Hi,

I really like the presentation mode (generated when ?presentme=true).  If I am in the presenter window and move from one slide to the next, the main window updates accordingly.

However, if by accident I am on the main window, and navigate to another slide, the presenter window is not updated.  The two screens are then out of sync and stay that way until I reset them (e.g. by moving back repeatedly to the start in each window).

Is this known behaviour?  Its not a big issue, but thought I'd mention it.  Sometimes by accident I have my pointer in the main window e.g. to interact with an iframe, as I can't interact with it on the presenter window.  My workaround for now will be to ensure that I return the pointer to the presenter window before navigating to another slide!

version information:

rmarkdown Version:              0.2.50
knitr             Version:            1.6

**Comment by yihui** [comment]
I guess it is unlikely that we can fix this issue, since we do not really maintain the JS library. If you are interested in the presentation mode, several other more modern and better maintained libraries can do a much better job. Two examples are [revealjs](/rstudio/revealjs) and [xaringan](/yihui/xaringan).
