### ISSUE TITLE
Square brackets in md_document

### ISSUE THREAD

**Issue by DanChaltiel** [rstudio/rmarkdown#1860]
Hi dev team,

I'm using `pkgdown` to document my package, and I thus have to generate an `index.md` file.

My documentation has some square brackets, and the knitting process unexpectedly escapes them. However, it seems that this is then interpreted incorrectly in the further HTML conversion, as the brackets disappear and the inside turns to italic (I think it triggers the math formula format). 

This happens whether I use the Rstudio "knit" button or I use `knitr::knit` myself. 

For now (until I'm able to correct it), you can see an example [here](https://danchaltiel.github.io/crosstable/index.html#margins-and-totals): the second row of the table should have square brackets, as median[IQR]. This also happens using the RStudio "preview" button on the `md` file.

This behavior has already been described in 2016 in https://github.com/rstudio/rmarkdown/issues/667 but was closed without being truly solved. The OP accepted a workaround: including all bracket sequences as inline code. However, this won't work in generated HTML tables such as mine.

Here is a reproducible example:

```Rmd
---
output: md_document
---

I want to describe something as median[IQR].
```

Resulting `md` file:
```md
I want to describe something as median\[IQR\].
```

Resulting HTML:
```html
<p>I want to describe something as median
	<span class="math display">
		<span class="MathJax_Preview" style="color: inherit;"/>
		<div class="MathJax_Display" style="text-align: center;">
			<span class="MathJax" id="MathJax-Element-1-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot; display=&quot;block&quot;><mi>I</mi><mi>Q</mi><mi>R</mi></math>" role="presentation" style="text-align: center; position: relative;">
				<nobr aria-hidden="true">
					<span class="math" id="MathJax-Span-1" style="width: 2.574em; display: inline-block;">
						<!-- some mathjax things -->
					</span>
				</nobr>
				<span class="MJX_Assistive_MathML MJX_Assistive_MathML_Block" role="presentation">
					<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
						<mi>I</mi>
						<mi>Q</mi>
						<mi>R</mi>
					</math>
				</span>
			</span>
		</div>
		<script type="math/tex; mode=display" id="MathJax-Element-1">IQR</script>
	</span>.
</p>

```

If I manually unescape these square brackets in the `md` file, the HTML result is OK. However, there can eventually be a whole lot of them, in multiple files, so this doesn't seem a sustainable solution to me.

Couldn't there be an option in the YAML header that would prevent this unwanted escaping behavior?

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I think what you described is a pandoc behavior. Here my understanding and investigation

knitr won't escape the bracket.

``` r
knitr::knit(text = "with [bracket]")
#> [1] "with [bracket]"
```
If you convert your Rmd to md with knitr only - no escaping.

However, pandoc will escape (Using `md_document` format will tell rmarkdown to use pandoc to convert to a markdown document)
```bash
$ echo "text with [bracket]" | pandoc -t markdown_strict
text with \[bracket\]
```

This is because brackets are special characters in markdown syntax, so pandoc escapes them to indicate they are parsed as text and not as their markdown meaning. 

However, I understand that you convert this index.md file to HTML, and `\[....\]` is then seen as a Mathjax syntax, so it is converted to inline math. I think this because pkgdown uses explicitly the [tex_math_single_backslash](https://pandoc.org/MANUAL.html#extension-tex_math_single_backslash)
> Causes anything between \( and \) to be interpreted as inline TeX math, and anything between \[ and \] to be interpreted as display TeX math. Note: a drawback of this extension is that it precludes escaping ( and [.

This happens here: https://github.com/r-lib/pkgdown/blob/caf7cc74e008e8d0d6e53eeda93cd3cad3545bf2/R/markdown.R#L6

and here is the effect of what pkgdown does when converting .md to .html 
```bash
$ echo "text with \[bracket\]" | pandoc -f markdown_github -t html
[WARNING] Deprecated: markdown_github. Use gfm instead.
<p>text with [bracket]</p>
```
```bash
$ echo "text with \[bracket\]" | pandoc -f markdown_github+tex_math_single_backslash -t html
<p>text with <span class="math display"><em>b</em><em>r</em><em>a</em><em>c</em><em>k</em><em>e</em><em>t</em></span></p>
```

So I think this is a pkgdown issue. For example, they could use instead `tex_math_double_backslash` with this format.
```bash
$ echo "text with \[bracket\]" | pandoc -f markdown_github+tex_math_double_backslash -t html
<p>text with [bracket]</p>
```

Here are the background about all this in pkgdown
* About math : https://github.com/r-lib/pkgdown/pull/1193
* About markdown_github: https://github.com/r-lib/pkgdown/pull/1195

And at last, it also seems that github flavored markdown does not support Math Expression 🤔 

Your rendering issue should be reported to pkgdown repo I think.

Hope it helps.

**Comment by DanChaltiel** [comment]
Hi Christophe,

Thank you for this very thorough answer, it helps my understanding a lot.

Indeed, this seems to be a pandoc behavior. However, I'm not sure this should be seen as a pure pkgdown issue, as RStudio HTML preview for .md files has the same behavior. This makes me think that this is the correct/expected/accepted rendering behavior.

Still, if a fix could happen at a lower level, such as pandoc, both outputs would be right. This is especially true in an RStudio pipeline, as "knit" and "preview" buttons are important helpers. However, I'm pretty sure that this is not important enough to motivate pandoc to add another extension for not escaping square brackets.

I don't understand `rmarkdown::render` enough to know, but if there was an argument for specifying characters that should not be escaped during the pandoc transformation (like `no_escape="[]"`), this would solve this kind of issues.

In the end, I'm afraid that if this cannot be addressed in rmarkdown or at the same level, then it will not be addressed at all. But of course there might be no workable solution.

For now, I will use this workaround, which corrects the issue:
```r
fixBrackets = function(file){
    x=readLines(file)
    y=gsub("\\[", "[", x, fixed = TRUE)
    y=gsub("\\]", "]", y, fixed = TRUE)
    writeLines(y, file)
}
rmarkdown::render(input="pkgdown/index.Rmd")
fixBrackets("pkgdown/index.md")
```

**Comment by cderv** [comment]
Pandoc does the escaping to protect so that it does not conflict with markdown syntax after. You can give a 👍  in the issue so that the markdown writer in pandoc gets improved : https://github.com/jgm/pandoc/issues/6259

> However, I'm not sure this should be seen as a pure pkgdown issue, as RStudio HTML preview for .md files has the same behavior.

The fact that `\[..\]` is turned to Math is only because the `+tex_math_single_backslash` extension is activated. If pkgdown would not used that extention when converting to HTML, you would not have the issue. There is currently no option to deactivate the extension (`-tex_math_single_backslash`) or change it. (`+tex_math_double_backslash`)
However, Github Markdown originally support this, and your issue is a known one for markdown_github format. See https://github.com/jgm/pandoc/issues/2707
I still think this could be interesting to report in pkgdown repos so that this limitation is known.

If you want to avoid using pandoc conversion from md markup to another md markup, you may also write the Rmd file with the markdown you want directly then use `knitr::knit` to convert from Rmd to md. knit will execute code chunks and generate a md file with the same markdown content with code and result included depending on chunk options. It could be way to generate your `index.md` from `index.Rmd` without having the pandoc Markdown Reader and Writer interference.

Anyway, your solution is a great one too. 👍

**Comment by atusy** [comment]
If the matter is only about HTML output, I suggest `render('index.Rmd', html_document)`.
Maybe `pkgdown` should render `index.Rmd` instead of `index.md`.

**Comment by cderv** [comment]
@atusy  from the doc, it seems to be a design choice : https://pkgdown.r-lib.org/reference/build_home.html#home-page
> If you use index.Rmd or README.Rmd it's your responsibility to knit the document to create the corresponding .md. pkgdown does not do this for you because it only touches files in the doc/ directory.

With pkgdown, you can't provide the resulting html yourself. That is why I suggest to knit directly to md without pandoc as a workaround.

**Comment by atusy** [comment]
@cderv I see... Thanks!

**Comment by atusy** [comment]
I opened a PR #1863 so that `md_document` allows `kntir::knit`ted markdown as an output.
I'm not sure if this hack is affordable... but let's see people's opinion.

**Comment by atusy** [comment]
@DanChaltiel 

I closed PR #1863 because I found a simple work around for RStudio user.
Just add a following line to the YAML front matter of your `Index.Rmd`.

```
knit: (knitr::knit)
```

**Comment by cderv** [comment]
Great solution to customize in RStudio to get only a knitted document ! 
For context about this yaml field, see about customizing the knit button in Rstudio in here: https://bookdown.org/yihui/rmarkdown-cookbook/custom-knit.html

**Comment by cderv** [comment]
I am not sure this is an issue anymore. 

* **pkgdown** has switch from `markdown_github` to using `markdown` when Pandoc 2+ is used so the initial issue should not be there anymore (https://github.com/r-lib/pkgdown/blob/72200017e36ad6a99706d085699e974ad5b3e417/R/markdown.R#L97)

* Pandoc has closed the related issue about aggressively escaping  (https://github.com/jgm/pandoc/issues/6259) so it seems it won't do much more on this. The Pandoc solution would be to use raw attributes as they described in there feed so that the characters are not escaped

Also the escaping of brackets is the expected behavior when the output markdown format considers it as a special characters. (like `markdown_strict` the default variant for `md_document`). 

Post processing as you've done the resulting md file is also a good option in specific case where this is needed.

Considering all this, I'll close this. Please, reopen if there is still something we should consider for such case. 

Thanks you.

**Comment by wcerfgba** [comment]
I am still struggling with this. I have an RMarkdown file which I am rendering to a Word document using bookdown, but adding `knit: (knitr::knit)` to my top matter doesn't change anything.

**Comment by cderv** [comment]
> I have an RMarkdown file which I am rendering to a Word document using bookdown

You are mentionning **bookdown** and output being Word document. So this is different than this issue with **rmarkdown** that targets `md_document()` as output. 

Can you open a new issue in **bookdown** and provide context with ideally a reproducible example for us to understand and reproduce your problem. Thank you !

**Comment by wcerfgba** [comment]
Turns out I just needed to _not_ try and escape the square brackets and they rendered fine! :facepalm:
