### ISSUE TITLE
Bash chunk doesn't recognize conda command for wsl bash

### ISSUE THREAD

**Issue by rezaeir** [rstudio/rmarkdown#1875]
I'm running Rstudio from windows 10. My default terminal is `bash` (windows subsystem for Linux). It works perfectly fine in terminal. 
- The rmarkdown bash chunck recognizes it correctly:
```{bash}
uname -o
```
```
GNU/Linux
```
 
However, the problem is as follows:
- running conda command in bash chunk
```{bash}
conda
```
```
/mnt/c/Users/Reza/AppData/Local/Temp/RtmpmgDnss/chunk-code-41ac2fb52d.txt: line 1: conda: command not found
```
I tried using `engine options = --login` and also tried `source ~/.bashrc` but the problem persists.

I don't know if this is a bug or the feature is not supported yet. Or maybe it is neither and I just don't know how to fix it.

```
> xfun::session_info('rmarkdown')
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 1.3.959

Locale:
  LC_COLLATE=English_United States.1252 
  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 digest_0.6.25   evaluate_0.14   glue_1.4.1     
  graphics_4.0.2  grDevices_4.0.2 highr_0.8       htmltools_0.5.0
  jsonlite_1.7.0  knitr_1.29      magrittr_1.5    markdown_1.1   
  methods_4.0.2   mime_0.9        rlang_0.4.7     rmarkdown_2.3  
  stats_4.0.2     stringi_1.4.6   stringr_1.4.0   tinytex_0.25   
  tools_4.0.2     utils_4.0.2     xfun_0.16       yaml_2.2.1     

Pandoc version: 2.7.3
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I think this is just a setup thing regarding the bash knitr engine. Knitr engine will run `bash -c` by default and so in a non interactive shell. The startup is different regarding how bash is executed. See https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

Conda will add itself to PATH through initialization in the `~/.bashrc`. This file needs to be sourced for `conda` command to be available in PATH. As I am on windows with WSL, I can test and what I see is that in my `~/.bashrc` file, I have this
```sh
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
That means you need to run bash interactively. And using `-c` option for `bash` don't create an interactive shell. This is why you observe this behavior. 
I don't know if the content is specific to Ubuntu 20 that I use, or the same for every linux distro. The other startup file I have like `~/.profile` will run the `.bashrc` but it will always do nothing as written in the script. 

You either need to explicitly tell to use an interactive shell using `bash -i` so by setting 
````r
```{bash, engine.opts="-i"}
conda
```
````
Or modify the `.bashrc` file. 

Or you need to add conda in PATH in another way so that it is available in you non-interactive bash session. 

Here is a related question in knitr https://github.com/yihui/knitr/issues/1762 where you find some of my tests with that. 

I don't think there is any issue in knitr or rmarkdown.

**Comment by rezaeir** [comment]
@cderv , Thank you so much. The `engine.opts="-i"` fixed the problem. I guess this issue can be closed.

**Comment by cderv** [comment]
Glad it worked !

Mind the potential side effect. The `-i` option solves this here, but I don't know what running bash in interactive mode can have as side effect when also using `-c` - I think not so much but you'll see 😄

**Comment by rezaeir** [comment]
@cderv I guess, I'd rather use it while it works and think about this potential issue when it happens 😄
