### ISSUE TITLE
LaTeX Errors: Option clash for package color / Environment {css_class} undefined

### ISSUE THREAD

**Issue by gd047** [rstudio/rmarkdown#1882]
Here is the link of my (unanswered) [question on stackoverflow](https://stackoverflow.com/questions/63538125/latex-error-option-clash-for-package-color)

Just updated R to version 4.0.2 (from 3.6.3) and rmarkdown to v2.3 (from 1.13). But I face several problems when knitting to pdf. I used the following code in the yaml section of a new rmarkdown (pdf), leaving the rest of the contents unchanged, and I got the error of the title. 

    ---
    title: "Untitled"
    output: 
      pdf_document:
        fig_height: 6
        fig_width: 9
        includes:
          in_header: greek.tex
        latex_engine: xelatex
        pandoc_args: [
                       "--variable", "geometry:paperwidth=8.27in",
                       "--variable", "geometry:paperheight=11.69in",
                       "--variable", "geometry:left=0.75in",
                       "--variable", "geometry:right=0.75in",
                       "--variable", "geometry:top=0.75in",
                       "--variable", "geometry:bottom=0.75in"
                     ]
    
    ---

greek.tex contents:

    \usepackage{fontspec}
    \usepackage{hyperref}
    \usepackage{longtable}
    \usepackage{rotating}
    \usepackage{tabularx}
    \usepackage{pdflscape}
    \usepackage{float}
    \usepackage[usenames, dvipsnames]{color}
    \usepackage[normalem]{ulem}
    \usepackage[bottom]{footmisc} 
    \setmainfont[Scale=1.0]{Segoe UI} 
    \setsansfont{Calibri}
    \usepackage[font=small]{caption}
    \captionsetup[table]{name=Πίνακας}
    \renewcommand{\baselinestretch}{1.2}

I also noticed that html code like this, that I need when knitting to html

    <div class="text-center"> 
now generate errors, like

    ! LaTeX Error: Environment text-center undefined.

Session Info

    > sessionInfo()
    R version 4.0.2 (2020-06-22)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 8.1 x64 (build 9600)
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=Greek_Greece.1253  LC_CTYPE=Greek_Greece.1253   
    [3] LC_MONETARY=Greek_Greece.1253 LC_NUMERIC=C                 
    [5] LC_TIME=Greek_Greece.1253    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods  
    [7] base     
    
    loaded via a namespace (and not attached):
     [1] compiler_4.0.2  htmltools_0.5.0 tools_4.0.2     yaml_2.2.1     
     [5] rmarkdown_2.3   knitr_1.29      xfun_0.16       digest_0.6.25  
     [9] packrat_0.5.0   rlang_0.4.7     evaluate_0.14 

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi, 

For the first question, this is a latex issue. It seems the answer you got as comment in your SO post is the correct one for setting the color option. Pandoc template for tex used by rmarkdown are using the **xcolor** package. If you want ot customize in the header, it seems you need to use `\PassOptionsToPackage` . ( like in the template https://github.com/jgm/pandoc-templates/blob/490c564f068b65b79bf94119259cbd78bc43f961/default.latex#L5)
The header file provided to be included must create a correct tex file - you can look at the tex file by setting `keep_tex: true` in the yaml option for `pdf_document`. More on this issue : http://www.texfaq.org/FAQ-optionclash

For the second part about `<div class="text-center">`, for a Latex document this will be converted to a Native pandoc Div. With rmarkdon 2.3, it is by default converted to a latex environment. Let's not that using htlm code for a `pdf_document` is not a good idea. However, you may need them for producing a html document also. Anyway, this has no been fixed and change back - You need to update to rmarkdown dev version on github so that it is not converted by default anymore. `data-latex` attribute is needed for this conversion to happen. 

One last comment, in case it could help, you can pass variable to pandoc template by using directly the variable in the YAML header like this. 
```yaml
---
title: "Untitled"
output: 
  pdf_document:
    fig_height: 6
    fig_width: 9
    latex_engine: xelatex
geometry:
  - paperwidth=8.27in
  - paperheight=11.69in
  - left=0.75in
  - right=0.75in
  - top=0.75in
  - bottom=0.75in
---
````
it is easier to write.  But your way works also ok ! 

I'll close as there are no issue in Rmarkdown regarding this.
