### ISSUE TITLE
Weird Interaction between level 4 header and code chunk

### ISSUE THREAD

**Issue by MarcusOy** [rstudio/rmarkdown#1896]
Crossposted from [StackOverflow](https://stackoverflow.com/questions/63778506/weird-interaction-between-level-4-header-and-code-chunk).

I am using R Studio for one of my classes (reproducible on R Studio Cloud) and I've been running into a bug where if a level 4 header is above an R code chunk with `echo=T`, the header will appear below the first code chunk. This only happens when output is PDF. Here's a picture to show what I mean:

![image](https://user-images.githubusercontent.com/16263577/92652828-7c833080-f2bb-11ea-80c0-34bbb287bc21.png)

And here's an example of what anything above a level 4 header looks like (pictured is a level 3 header):

![image](https://user-images.githubusercontent.com/16263577/92652837-80af4e00-f2bb-11ea-91d4-9761a33d1075.png)

Both examples are built from the Magma Demo rmd file from R Studio Cloud, but a simple, reproducable example can be seen below:

````
#### Header

Description: asdfasdf

```{r}
10+12

100/10
```

Conclusion: fdsafdsa

````

Is this intended? Or am I doing something wrong? Many thanks in advance.

---

By filing an issue to this repo, I promise that

- [X] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
There was a reason why I saw (and edited) your SO post but didn't reply yesterday: https://yihui.org/en/2018/01/screenshots-vs-text/ Please provide the reproducible example instead of screenshots. Thanks!

> I can't post the code without breaking the editor and the code isn't very hard to reproduce, so here's a picture of the code:

We'll appreciate it if you could read the issue guide, and fulfill the promises above.

**Comment by MarcusOy** [comment]
@yihui Ok well here's a workaround to making it so that my code snippet doesn't break the github code block.

```
#### Header

asdfasdf

```{r}
10+12

100/10
```{delete everything but the three symbols on the left}

asdfasdf

```

**Comment by yihui** [comment]
>     ```{delete everything but the three symbols on the left}

Alright. Let me be more specific about what you really need to read in the issue guide: https://yihui.org/issue/#please-format-your-issue-correctly

**Comment by MarcusOy** [comment]
Fixed @yihui , sorry bout that.

**Comment by yihui** [comment]
Okay. Thanks for learning the syntax!

The example you provided may not be self-contained, since I don't know the output format. Here is what I tested:

````
---
title: "Level 4 header"
output: pdf_document
---

#### Header

Description: asdfasdf

```{r}
10+12

100/10
```

Conclusion: fdsafdsa
````

## With the level 3 header

![image](https://user-images.githubusercontent.com/163582/92807120-380d9880-f380-11ea-9e52-21dc42a36608.png)

## With the level 4 header

![image](https://user-images.githubusercontent.com/163582/92807358-6c815480-f380-11ea-9868-c3b43e40607c.png)

I don't see the problem you described.

**Comment by MarcusOy** [comment]
I just realized that by simplifying the repro, I completely messed up the scope of the problem. Fixed YET AGAIN, this time tested. I promise I'm not a complete dunce.
````
### Question 1

Description for Q1: asdf asdf.

#### Solution

```{r}
10+12

200/10
```

Conclusion for Q1: fdsa fdsa.

### Question 2

Description for Q2: asdf asdf.

### Solution

```{r}
10+12

100/10
```

Conclusion for Q2: fdsa fdsa.
````

Question 1 contains the error (where the level 4 header makes its way underneath the first code chunk somehow), and Question 2 is what I'd expect the knitted Pdf to look like, using a level 3 header instead of a level 4 header.

Here's a zip file that contains the Rmd, Pdf, and Html files. The Html doesn't contain the irregularity, only the Pdf. [rstudio-export.zip](https://github.com/rstudio/rmarkdown/files/5205695/rstudio-export.zip)

**Comment by yihui** [comment]
I've isolated the issue from **rmarkdown** and created a minimal reproducible example:

```tex
\documentclass{article}
\usepackage{xcolor}
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}

\begin{document}

Hello,

\paragraph{world!}

\begin{Shaded}
1 + 1
\end{Shaded}

\end{document}
```

Save it as `test.tex`, run `pdflatex` on it, and you can reproduce the problem. I don't have enough LaTeX expertise to fix this problem. My guess is that it was caused by a weird interaction between the `snugshade` environment and `\paragraph{}`. If you really want to figure it out, I recommend that you ask the question and mention this minimal example (you don't need to mention **rmarkdown** or Pandoc).

`\paragraph{}` was generated from the level-4 header `####`, which causes the problem here. Without `\paragraph{}`, it works fine.

Perhaps you could consider using `##` for questions and `###` for solutions, or `** **` (bold text) for solutions. I guess there isn't much that I could do on **rmarkdown**'s side. Sorry.

**Comment by yihui** [comment]
I just saw a similar question on SO: https://stackoverflow.com/q/63965202/559676 The solution there might also work for you. Anyway, this is definitely a LaTeX issue, so I'm closing it here. If the solution doesn't work, please feel free to ask on public forums like SO or RStudio Community. Thanks!
