### ISSUE TITLE
custom-style in docx only works for block-level text, does not work for inline text

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#1911]
Using latest CRAN rmarkdown v2.4 and pandoc 2.7

As per the [pandoc documentation](https://pandoc.org/MANUAL.html#custom-styles), it should be possible to use custom styles in docx documents. Custom styles need to first be defined in the reference docx and then they can be used either in inline text (span tags or "bracketed spans" syntax) or in paragraph level text (div tags or "fenced divs" syntax). 

In all following code chunks, [this reference word document](https://github.com/rstudio/rmarkdown/files/5337076/ref.docx), which has a custom style named "deanstyle" using red colour and underlined, is used as the "ref.docx".

The following Rmd works correctly and produced the word "test" in red and underlined:

```
---
title: "testing custom styles inline vs block level"
output: 
  word_document:
    reference_docx: ref.docx
---

<div custom-style="deanstyle">test</div>
```

The following also works:

```
---
title: "testing custom styles inline vs block level"
output: 
  word_document:
    reference_docx: ref.docx
---

::: {custom-style="deanstyle"}
test
:::
```

So it works with block level. But if I try to use inline text to have specific words with the style, it does not work:

```
---
title: "testing custom styles inline vs block level"
output: 
  word_document:
    reference_docx: ref.docx
---

<span custom-style="deanstyle">test</span>
```

or 

```
---
title: "testing custom styles inline vs block level"
output: 
  word_document:
    reference_docx: ref.docx
---

[test]{custom-style="deanstyle"}
```

**Comment by cderv** [comment]
Hi @daattali, 

I believe there is no issue here and just a question about how Pandoc and Word is working. Not related to Rmarkdown specifically as it is just using Pandoc feature here.

WORD is making a distinction between Paragraph Style and Character Style. Currently, you have define a Paragraph style only I believe.

From [pandoc documentation](https://pandoc.org/MANUAL.html#custom-styles):
> If you define a div or span with the attribute custom-style, pandoc will apply your specified style to the contained elements (with the exception of elements whose function depends on a style, like headings, code blocks, block quotes, or links). So, for example, using the bracketed_spans syntax,
>
> ````
> [Get out]{custom-style="Emphatically"}, he said.
> ````
> would produce a docx file with “Get out” styled with **character style** Emphatically. Similarly, using the fenced_divs syntax,
>
 > ```
> Dickinson starts the poem simply:
> ::: {custom-style="Poetry"}
> | A Bird came down the Walk---
> | He did not know I saw---
> :::
> ```
>  would style the two contained lines with the Poetry **paragraph style**.

it says explicitly that applying to a span will use **character style** in docx, and applying to a Div will use **paragraph style**. 

It means you need to define also a character style in your reference document. Try with 
[ref2.docx](https://github.com/rstudio/rmarkdown/files/5339596/ref2.docx) where I define an "inline" style and with this in your Rmd 
````md
---
title: "testing custom styles inline vs block level"
output: 
  word_document:
    reference_docx: ref2.docx
---

::: {custom-style="deanstyle"}
test
:::

[test2]{custom-style="deanstyleinline"}
````
You should get this: 
![image](https://user-images.githubusercontent.com/6791940/95315276-9439de80-0892-11eb-9f31-d79398c5e1d1.png)


BTW I don't think you can apply a Paragraph style as a Character style. You can however have a paragraph style that uses a chracter style. In fact in your `ref.docx` your custom style use the default character style (use the style inspector to look at it).
IMO it make sense because you may want to apply a specific character style to some text inside a paragraph - so they can't be the same. It is like in HTML where you use span to change the style of some text inside a div which has its own style. 
My understanding is you would need two style : one for inline and one for block, with your block style using the inline style by default. and you would be able to apply the inline style in any other paragraphs also. 

Anyhow, this is Word wizardry and you should look at documentation about how this works in docx. 

If you consider this an issue, I would suggest report in Pandoc repository as this has nothing to do with rmarkdown I believe. 

Does it make sense ? Can I close this issue ?

**Comment by daattali** [comment]
Thank you so much, you're absolutely right. This is a character style vs paragraph style issue - a distinction I didn't know exists. I thought I was reading the documentation correctly but didn't notice that one word (character vs paragraph) is actually technically significant. Thanks for the detailed help instead of just telling me it's not an rmarkdown issue!
