### ISSUE TITLE
Why is email obfuscation made impossible in html_document?

### ISSUE THREAD

**Issue by seankross** [rstudio/rmarkdown#1969]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

I am referring to this line code: https://github.com/rstudio/rmarkdown/blob/master/R/html_document_base.R#L38. I am making an html template that depends on `html_document()` and I would like to obfuscate linked email addresses in the document. Why is this option always turned off for `html_document()`? Would you accept a change that makes it possible to enable email obfuscation?

**Comment by cderv** [comment]
Personally, I don't see why we couldn't an option to change that pandoc option. 

Digging in history, I see it is there since a long time (2014 version 0.6 https://github.com/rstudio/rmarkdown/commit/39645713781451e0add0a6f276a531c4a5917ead). 

I believe at that time, `--email-offuscation=none` was not the pandoc default behavior. From [release note](https://pandoc.org/releases.html), the option was introduced in 2009 1.2 and it default to none since 2016 1.17.2. 

So for Pandoc 1.17.2+, we could even remove that option from the command line, living it possible to users to use `pandoc_args` argument to add it with a non default value. 

So we could: 
* Provide an option to change the value
* Provide a new argument in `html_document_base()` to set this
* Remove it completly for Pandoc 1.17.2+, and let (advanced) user provide it using `pandoc_args` directly. 

For now, I believe you can alreay use it for your need.

I think if you provide the pandoc arg, it will be used instead of the one provided inside `html_document_base` as long as it is provided after in the command line argument. For example
````yaml
output:
  html_document: 
    pandoc_args: ["--email-obfuscation", "javascript"]
```
Works for me.

If you are defining a new format, I think it would work also 
``` r
dummy_out <- rmarkdown::output_format(
  knitr = list(),
  pandoc = rmarkdown::pandoc_options(
    to = "html4",
    from = rmarkdown::from_rmarkdown(),
    args = c("--email-obfuscation", "references")
  ),
 base_format = rmarkdown::html_document_base() 
)
# place after the one in html_document_base()
dummy_out$pandoc$args
#> [1] "--email-obfuscation" "none"                "--self-contained"   
#> [4] "--email-obfuscation" "references"
```

both would be in command line, but same as above, the latter would be used.

or you could replace the command line argument
``` r
out <- rmarkdown::html_document_base()
ind <- which(out$pandoc$args == "--email-obfuscation")
if (length(ind) != 0) 
  out$pandoc$args[ind + 1] <- "javascript"
out$pandoc$args
#> [1] "--email-obfuscation" "javascript"          "--self-contained"
```

it depends how you define the custom output. 

Hope it helps

**Comment by seankross** [comment]
Thank you so much @cderv for such a thoughtful and thorough answer! It looks like your suggestions will solve my short term issues.

**Comment by yihui** [comment]
> * Remove it completly for Pandoc 1.17.2+, and let (advanced) user provide it using `pandoc_args` directly.

I'm okay with that, but we need to ask @jjallaire about the motivation of 3964571 (why email obfuscation should be disabled).

**Comment by jjallaire** [comment]
I think I just felt that none was a better default (as often times Rmd documents are not published on the public web so email obfuscation isn't necessary). I also think that the method at the time was probably e.g. `jj at rstudio.com` which I didn't think was clear enough for non-technical users.

I think we should definitely make it an option, and if the javascript method prints the full email address by default I wouldn't object to turning it on by default.

**Comment by yihui** [comment]
Since `--email-obfuscation=none` has become the default since Pandoc 1.17.2, I guess we can just remove the lines added in 3964571 now, and leave the option to users (i.e., using `pandoc_args`). This is a relatively advanced feature, and I tend not to add an extra argument like `email_obfuscation` to the output format functions.

**Comment by cderv** [comment]
Just to share about the different options, that already works today because last command line switch is taken into account by pandoc


## Using javascript 

```yaml
  html_document: 
    pandoc_args: ["--email-obfuscation", "javascript"]
```

renders like this

```html
<p><script type="text/javascript">
<!--
h='&#100;&#x6f;&#x65;&#46;&#x6f;&#114;&#x67;';a='&#64;';n='&#106;&#x6f;&#104;&#110;';e=n+a+h;
document.write('<a h'+'ref'+'="ma'+'ilto'+':'+e+'" clas'+'s="em' + 'ail email">'+e+'<\/'+'a'+'>');
// -->
</script><noscript>john at doe dot org</noscript></p>
```
and shows as 
![image](https://user-images.githubusercontent.com/6791940/101041996-f9513e00-357c-11eb-8282-b22fc24a68da.png)

## Using references

It only works if `self_contained = FALSE`. (not sure sure why)

In this case 
````yaml
  html_document: 
    self_contained: FALSE
    pandoc_args: ["--email-obfuscation", "references"]
````
renders this
```html
<p><a href="&#x6d;&#x61;&#x69;&#108;&#116;&#x6f;&#58;&#106;&#x6f;&#104;&#110;&#64;&#100;&#x6f;&#x65;&#46;&#x6f;&#114;&#x67;" class="email">&#106;&#x6f;&#104;&#110;&#64;&#100;&#x6f;&#x65;&#46;&#x6f;&#114;&#x67;</a></p>
````
and shows also as this 
![image](https://user-images.githubusercontent.com/6791940/101043505-b001ee00-357e-11eb-9a56-4d566aeb9f80.png)
