### ISSUE TITLE
Improvement/enhancement: Update html_document themes to support the most recent ones in bootswatch

### ISSUE THREAD

**Issue by jmcastagnetto** [rstudio/rmarkdown#1988]
Just a minor suggestion, to support the current themes at https://bootswatch.com/. The repo is at: https://github.com/thomaspark/bootswatch

**Comment by cderv** [comment]
Hi, 

We are currently working on integration between **rmarkdown** and **bslib** (WIP in #1706). This should lead to access to any **bslib** feature and you should be able to create a theme using any of the one in bootswatch (https://rstudio.github.io/bslib/#create-a-theme). 

I leave this open until we finish the work.

**Comment by cderv** [comment]
@jmcastagnetto if you install the dev version of **rmarkdown** with
```r
remotes::install_github("rstudio/rmarkdown", dependencies = TRUE)
```
so that Suggests dependencies are also installed (you need **bslib**) 

you can the pass a list to `theme` argument that will be passed to `bslib::bs_theme()`. For example, this would use the _Lux_ bootswatch theme: 

````yaml
title: "Untitled"
output: 
  html_document:
    theme: 
      bootswatch: lux
````

You can do much more. You'll find the information for now in the **bslib** doc and in the upcoming talk about **bslib** at rstudio::global: https://global.rstudio.com/student/activity/40601
