### ISSUE TITLE
New mistake in default pandoc template for pdf using bookdown

### ISSUE THREAD

**Issue by fecet** [rstudio/rmarkdown#2022]
In the past, the default pandoc template will always include 

`\usepackage{amssymb,amsmath}`

before determine which engine selected:

```
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
```

but now, the default template change to:

```
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
```

now it will not use `amssymb` by default in xetex, but if you use it manually in `preamble.tex` , `amssymb` will always included after `unicode-math` and that will result in a conflict which has been mentioned in [here](https://tex.stackexchange.com/questions/547150/latex-command-is-already-defined-error). My question is where the default template located and we can modify it?

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi @fecet, 

The template used for PDF are the one from Pandoc. That means they will depend on the version of Pandoc you have.
 
**Which version do you have, please ?** 

It seems they remove `amssym` in version 2.11.0.3 (https://github.com/jgm/pandoc/commit/83b54bb0b375c041fc59f9c0599c626582184903) and put it back in 2.11.3 (https://github.com/jgm/pandoc/commit/ea8097e41249387613cae2552866f1ea1cea1462). It is also mentioned in the [release note ](https://pandoc.org/releases.html) of Pandoc. 

So there is a set of versions (2.11.0.3, 2.11.0.4, 2.11.1, 2.11.1.1, 2.11.2) where it will not be included in the templates, and you'll need to 
* add the package manually as an extra dependencies
* use pdflatex
* use lualatex or xelatex with setting `mathspec=true` in the YAML to activate pandoc variable (but this will also use `mathspec` package instead of `unicode-math`

Other solution is to update Pandoc. If you are using RStudio 1.4, you should have a version above 2.11.3

**Comment by cderv** [comment]
@yihui do you think it worth patching the template by adding this dependency for those specific versions of Pandoc ?

**Comment by cderv** [comment]
@fecet also to get the default template if you want to write it to a file and modify you can do in bash
```
pandoc -D latex > template.tex
```
or equivalent in R 
```
template <- system2(rmarkdown::pandoc_exec(), c("-D", "latex"), stdout = TRUE)
xfun::write_utf8(template, "template.tex")
```

**Comment by fecet** [comment]
> Hi @fecet,
> 
> The template used for PDF are the one from Pandoc. That means they will depend on the version of Pandoc you have.
> 
> **Which version do you have, please ?**
> 
> It seems they remove `amssymb` in version 2.11.0.3 ([jgm/pandoc@83b54bb](https://github.com/jgm/pandoc/commit/83b54bb0b375c041fc59f9c0599c626582184903)) and put it back in 2.11.3 ([jgm/pandoc@ea8097e](https://github.com/jgm/pandoc/commit/ea8097e41249387613cae2552866f1ea1cea1462)). It is also mentioned in the [release note ](https://pandoc.org/releases.html) of Pandoc.
> 
> So there is a set of versions (2.11.0.3, 2.11.0.4, 2.11.1, 2.11.1.1, 2.11.2) where it will not be included in the templates, and you'll need to
> 
> * add the package manually as an extra dependencies
> * use pdflatex
> * use lualatex or xelatex with setting `mathspec=true` in the YAML to activate pandoc variable (but this will also use `mathspec` package instead of `unicode-math`
> 
> Other solution is to update Pandoc. If you are using RStudio 1.4, you should have a version above 2.11.3

Thanks so much for your response, it always came faster than I expected ! I install a 2.11.4 version pandoc and
`rmarkdown::find_pandoc(version = "2.11.4")` and it works. 

Actually I used an old version rstudio(about 1.9.x) yesterday and after I install the newest rstudio from your website the problem occurs as the bundled in version is 2.11.2. So I think It's better to bundled a newer version in further rstudio.

**Comment by cderv** [comment]
Oh you're right. RStudio 1.4.1103 ships with Pandoc 2.11.2. I thought is was upper. 
FWIW the last daily version (https://dailies.rstudio.com/) ships with 2.11.4. 

There are always some delay because a new version is block for any evolution weeks before release in order to have the pre release tests and all. 

I'll reopen because as this will be an issue with anyone using the RStudio version, we may need to patch. There will be a patch release of the IDE I think so maybe it will upgrade. 

Thank you for reporting this!

**Comment by jjallaire** [comment]
PR for the IDE to update to pandoc v2.11.4 here: https://github.com/rstudio/rstudio/pull/8848

**Comment by yihui** [comment]
> do you think it worth patching the template by adding this dependency for those specific versions of Pandoc ?

We can consider patching the template if more users report this issue and have to use the problematic versions of Pandoc. Since the IDE has updated Pandoc, I think we can close this for now.
