### ISSUE TITLE
Comment in the RMarkdown file is not treated as comment in the LaTeX file

### ISSUE THREAD

**Issue by psads-git** [rstudio/rmarkdown#2026]
Please try to knit the attached file: the bug will be clear. 
[example.zip](https://github.com/rstudio/rmarkdown/files/5896704/example.zip)
Thanks!

**Comment by cderv** [comment]
Hi, 

For reference, here is the document in the zip file
````markdown
---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{enumerate}

<!-- My comment -->

\item This an item.

\end{enumerate}
````

This comment is in HTML format in the Markdown document. Currently, there is not a "Comment" syntax in Markdown known by Pandoc to be converted. This is still a feature request https://github.com/jgm/pandoc/issues/1926

This means Pandoc will see this comment as raw content, raw HTML in this case.
So you need to provide them in your document in raw format of your desired output, here LaTeX. 

In your example, this is also very specific because the HTML comment is in the middle of LaTeX syntax, so the whole block between `\begin{enumerate}` and `\end{enumerate}` is seen as a Raw LaTeX block, so pass as-is by Pandoc to LaTeX output. And the HTML comment syntax is not known by LaTeX.  This is because there is not [`markdown_in_tex_block`](https://github.com/jgm/pandoc/issues/2453) - this means anything in a TeX block is seen as raw TeX. 
Otherwise, it would have been discarded from the result as raw HTML won't be put in a LaTeX output. Example: 

````markdown
---
output: 
  pdf_document:
    keep_tex: true
---

Following is a list

<!-- My comment -->

1.  This an item.


````

Some workaround if you need that: 

* Create and use a R function to include the correct syntax based on the output

````markdown
---
output: 
  pdf_document:
    keep_tex: true
---

```{r, include= FALSE}
comment <- function(text) {
  if (knitr::is_html_output()) {
    sprintf("<!-- %s --->", text)
  } else if (knitr::is_latex_output()) {
    sprintf("%% %s", text)
  }
}
```

\begin{enumerate}

`r comment("My comment")` 

\item This an item.

\end{enumerate}
````
 

* Write a [Lua filter](https://bookdown.org/yihui/rmarkdown-cookbook/lua-filters.html) that would look for HTML comments and convert to LaTeX comments. This would be easier if the comment is not in a LaTeX block.

So, I believe this is not something we could improve in **rmarkdown**, it would need to be supported upstream in Pandoc. 

Is the solution with a R function something that would work for you ?

**Comment by psads-git** [comment]
Thanks, Christophe. I thought RMarkdown would “understand” that 

`<!-- My comment -->`

is a comment, even if inside a LaTeX block.

If, instead of 

`<!-- My comment -->`

one inserts

`% My comment`

it works fine.

**Comment by cderv** [comment]
> I thought RMarkdown would “understand” that
> `<!-- My comment -->`
> is a comment, even if inside a LaTeX block.

I wish this would work but this is a limitation of Pandoc for now which parses the Markdown content but does support this (as explained above linking to https://github.com/jgm/pandoc/issues/2453)

> If, instead of
> `<!-- My comment -->`
> one inserts
> % My comment
> it works fine.

For sure this works ! 

I believe I can close this issue then. If you still have issues with this, please reopen ! Thank you.
