### ISSUE TITLE
iframes don't work in rmarkdown

### ISSUE THREAD

**Issue by bkostadi** [rstudio/rmarkdown#2027]
I just updated to RStudio 1.4 and R 4.0.3 and I just tried embedding an iframe in an rmarkdown document, but when I open the knitted html in the Chrome browser,  I just see a black screen. I urgently need to be able to do this for my lectures. This issue was raised 5 days ago in the RStudio Community, with no solutions offered as of now: <https://community.rstudio.com/t/insert-raw-html-iframe-into-rmarkdown/94334?u=boyan.kostadinov>

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue. 
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Hi @bkostadi, 

I share here the same answer as in the community

It seems it is indeed a change from Pandoc as you guessed. Recent Pandoc version seems to now process **iframe**  tags the same as other when using `self-contained` document. 

You could either use `self_contained: false` in YAML to not have those `data:` tansformation, or follow Pandoc documentation and add `data-external="1"` attributes like this 
````html
<iframe src="https://ntu.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=894e2520-46b3-4c7e-9666-acbc00eee050&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=false&amp;start=0&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" data-external="1"></iframe>
````

This would prevent the transformation by Pandoc. Source of this info is here: https://pandoc.org/MANUAL.html#option--self-contained

Pandoc made this change to solve https://github.com/jgm/pandoc/issues/6854 in https://github.com/jgm/pandoc/commit/c1fbe7b91af03a43c6a771edca85b29334975070

While it works for some website, it may not work for all website (maybe they disallow it) like the one you tried. 

So this is a Pandoc feature (issue ? - I don't know if using data URI for iframe is good or bad).
It seems it is intentional, and you need to add the attribute or deactivate self contained feature.

**Comment by bkostadi** [comment]
Great! Thanks for looking into this! Adding this attribute works indeed.

**Comment by cderv** [comment]
@bkostadi we finally fix this by adding `data-external=1` by default in https://github.com/yihui/knitr/commit/5df7d270ae7d10069b8231899ac568674c1690f6

This means that if you use `knitr::include_url()` to insert the iframe with a url, this should be preserve and working as expected. 

Something like this would add the `data-external=1` by default. 

````markdown
```{r, out.width=720, out.extra='style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay"'}
knitr::include_url("https://ntu.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=894e2520-46b3-4c7e-9666-acbc00eee050&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=false&amp;start=0&amp;interactivity=all", height = 405)
```
````

Previous workaround with this function was to pass it in `out.extra`: `out.extra = "data-external=1"`

I'll close this as we have a solution in R directly now. Thanks for sharing.
