### ISSUE TITLE
pandoc_self_contained_html() prints <!DOCTYPE html> in <p> </p>

### ISSUE THREAD

**Issue by nvelden** [rstudio/rmarkdown#2066]
pandoc_self_contained_html() function prints the `<!DOCTYPE html> in a <p> </p> tag` making it visible on top of each page. 

Knitting the .RMD template to HTML and then converting it to a self contained html using `pandoc_self_contained_html()` (rmarkdown version 2.7) will produce:

```

> ---
> title: "title"
> author: "author"
> date: "9 3 2021"
> output: html_document
> ---
> 
> ```{r setup, include=FALSE}
> knitr::opts_chunk$set(echo = TRUE)
> ```
> 
> ## R Markdown
> 
> This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
> 
> When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:
> 
> ```{r cars}
> summary(cars)
> ```
> 
> ## Including Plots
> 
> You can also embed plots, for example:
> 
> ```{r pressure, echo=FALSE}
> plot(pressure)
> ```
> 
> Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```
Note the <!DOCTYPE html> tag on top of the page. The source code shows that the `<!DOCTYPE html>` is located in a `<p></p>` tag making it visible. 

![Screenshot_2021-03-09 title](https://user-images.githubusercontent.com/45127542/110488145-81039700-80ee-11eb-9cf8-7327c5b8d589.png)

---

By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.org/issue/.
- [x ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for the report. 

I believe this is because `<!DOCTYPE html>` is not recognized as a raw html string by pandoc to not touch. And because everything is a paragraph for Pandoc, unless raw HTML block. 
```sh
$ pandoc -f markdown -t html
<!DOCTYPE html>

# test
<strong>Something</strong>
^Z
<p>&lt;!DOCTYPE html&gt;</p>
<h1 id="test">test</h1>
<p><strong>Something</strong></p>
```

We could just detect and remove it before conversion I guess. 

Out of curiosity, can I ask how you use `pandoc_self_contained_html()` ? It is an old function that is not so commonly used, because when you want to produce a self contained document, it is best to set the `self_contained` option in the format output. 

Specifically, 
> Knitting the .RMD template to HTML and then converting it to a self contained html using pandoc_self_contained_html()

Why the knitting part does not get you the correct self contained HTML in the first place ? 

Thanks.

**Comment by nvelden** [comment]
I have quite a complicated HTML document with multiple images, external CSS and JS files. I have tried to set self_contained in the yaml header:

```
output:
  html_document:
    self_contained: yes #also tried TRUE or true
```

but nothing is embedded. Only when I knit first and then convert the .html file with pandoc_self_contained_html() I get a self contained .html.

**Comment by cderv** [comment]
Is this one .Rmd document or several ? 
`rmarkdown::render_site()` is for rendering multiple documents as a website, it is why I asked.
if so, do you have a `_site.yaml` file too ? 
`rmarkdown::render()` is for rendering one document.

I am trying to understand better what you are doing.

**Comment by nvelden** [comment]
I used the "hello-website" example: https://github.com/rstudio/rmarkdown-website-examples/tree/master/hello-website

I added a skeleton folder where I placed all my external files and I then used render_site(). I get the warning above and self_contained: yes does nothing. My website has only one index page for the moment but I would like to add more pages.

**Comment by cderv** [comment]
Thanks for precision. 

You are then using websites - as documented in https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html
> In addition to whatever common options you define, there are two output options that are automatically set when rendering a site:
> 1. The `self_contained` option is set `FALSE`; and
> 2. The `lib_dir` option is set to `site_libs`.
> These options are set so that dependent files (e.g., jQuery, Bootstrap, and HTML widget libraries) are shared across all documents within the site rather than redundantly embedded within each document.

This is part of the R Markdown website generator function. That is why setting the option won't apply. 
Usually for website, you don't need to have self contained document because 

* HTML files will be heavier, so longer to load (less responsive)
* Websites are composed of several HTML files that share common assets. Self contained makes more sense for single document to have everything inside on file so that is portable. 

Why are you looking to obtain self contained files if you are using website with several HTML ? 

>  Often I don't need the title or author headers that are automatically added on top of each page. I can hide it using css. (.title{display:none;}) but is there any other way to just not include it?

Just don't provide those fields in YAML. No `author`, and use `pagetitle` instead of `title` to avoid having a title header created.

**Comment by nvelden** [comment]
Great thanks a lot! This solves all my problems. 

I actually just wanted to generate just one page as self contained and thought I could also do it through the render_website function as my website consists of only one page at the moment.

**Comment by cderv** [comment]
> This solves all my problems.

Great ! So does it means I can close this ?

**Comment by nvelden** [comment]
Yes! Thank you.
