### ISSUE TITLE
Improve or drop support for old Pandoc

### ISSUE THREAD

**Issue by atusy** [rstudio/rmarkdown#2082]
I just happened to know that I fail to build vignette with Pandoc 2.0.1 because `pandoc.utils` reuired by `pagebreak.lua` is available since Pandoc 2.0.6: https://github.com/atusy/ftExtra/pull/59/checks?check_run_id=2208657510

A reprex that fails to be built with Pandoc < 2.0.6:

```yaml
---
title: "Untitled"
output: html_document
---
```

> Error running filter /home/runner/work/_temp/Library/rmarkdown/rmarkdown/lua/pagebreak.lua:
...work/_temp/Library/rmarkdown/rmarkdown/lua/pagebreak.lua:18: module 'pandoc.utils' not found:

I understand we can fallback so to skip `pagebreak.lua` for older Pandoc versions.
However, I think enough time has passed to drop such very old versions, especially Pandoc 1.x.
Dismiss my suggestion if there is any reason that **rmarkdown** still supports Pandoc >= 1.14.

Anyway, I would also suggest that `pkg_file_lua` should be updated so that we can skip filters for old Pandoc versions.
For example, maybe we can update the function so that each filters can require minimal Pandoc version by their names.

```r
pkg_file_lua(c("2.0.6" = "pagebreak.lua"))
```

<details><summary>xfun::session_info('rmarkdown')</summary>

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.3    grDevices_4.0.3   highr_0.8        
  htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1    markdown_1.1      methods_4.0.3     mime_0.10        
  rlang_0.4.10      rmarkdown_2.7     stats_4.0.3       stringi_1.5.3     stringr_1.4.0     tinytex_0.30      tools_4.0.3      
  utils_4.0.3       xfun_0.22         yaml_2.2.1       

Pandoc version: 2.0.1
```
</details>

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by atusy** [comment]
I think checking Pandoc version from Lua filter side is nice and explicit.
However, `PANDOC_VERSION` seems to be supported since Pandoc 2.1.0, implying difficuly to check version prior to it.

```lua
-- Check PANDOC_VERSION
if (not PANDOC_VERSION) or PANDOC_VERSION < "2.7.3" then
  print("skipping filter")
  return {}
end

-- Add filters
function Pandoc(doc)
  print("running filter")
end
```

**Comment by atusy** [comment]
Also note that CI fails with Pandoc 1.14.

> Error: Error: pandoc document conversion failed with error 83  
> https://github.com/atusy/rmarkdown/pull/2/checks?check_run_id=2219792064

**Comment by cderv** [comment]
> Anyway, I would also suggest that pkg_file_lua should be updated so that we can skip filters for old Pandoc versions.
For example, maybe we can update the function so that each filters can require minimal Pandoc version by their names.

For Lua filter, I would prefer that we put the check in the filter. If a Lua Filter needs a specific version to work, I think we need to make this filter conditional: Only apply when Pandoc version is above a requirement and do nothing otherwise. Lua filter can access the version in `PANDOC_VERSION` global variable: https://pandoc.org/lua-filters.html#global-variables
Thus this is available since Pandoc 2.1 only I think .
Example of such requirement test
https://github.com/pandoc/lua-filters/blob/f09e3336e54c97a795faca5645a5edbc8303add3/section-refs/section-refs.lua#L1

I think this would be easier and more transverse to keep the requirement for a Lua filter inside the Lua filter itself and not inside R. 
But we can do both also if you think having it in R is necessary.

Regarding dropping 1.x, I would also be ok with that. We don't know who used it for sure. I wondering if some OS still have only Pandoc 1.x in there stable repository. I encountered this case for Git in the past on CentOS: only version in repo that we had access was 1.x whil Git 2.x was out since several years. We need to check this I think. Not sure how. 

I think there is a scenario where we can still support old version for some feature that we freeze, and we then make sure everything is conditional on the right version of Pandoc after that. It is king of already the case where a lot of documented feature are working only with Pandoc 2.0. And also we don't test yet on Pandoc 1.x has you've done on your CI. We could fix that to. 

I'll be working on the Pandoc with R topic very soon and I'll have this Lua filter topic in mind;

**Comment by atusy** [comment]
I also prefer check in the filter, and implemented it in #2088.
I noticed that we do not need `PANDOC_VERSION` if we simply test existence of modules.

**Comment by cderv** [comment]
> I noticed that we do not need PANDOC_VERSION if we simply test existence of modules.

It fixes indeed the issue but does not provide a generic solution for making a requirement in Lua filters. I don't mind making the min requirement to Pandoc 2.1 for using Lua filters as I don't think this is very sensible because should be a few users (if none) `2.0` and `2.0.6`. 

Let's discuss this in the PR.

**Comment by cderv** [comment]
Part of this has been dealt in #2088. 

Should we keep this issue open to consider Pandoc 2.0+ support? Or should we make a new one for that ?

**Comment by yihui** [comment]
I think we can close it for now. We can fix the specific issues caused by Pandoc 1.x as they come. I'm not sure when we can fully drop the support for 1.x.
