### ISSUE TITLE
Drop the intermediate files *.knit.md and *.utf8.md

### ISSUE THREAD

**Issue by yihui** [rstudio/rmarkdown#2086]
In **rmarkdown**, we used to generate the intermediate file `*.knit.md` from `knitr::knit()`, and convert it to another intermediate file `*.utf8.md`. Then pass the utf8 file to Pandoc (because Pandoc only accepts UTF-8 input).

Since [**knitr** 1.24](https://github.com/yihui/knitr/releases/tag/v1.24), `knitr::knit()` only accepts UTF-8 input. Since [**rmarkdown** 2.0](https://github.com/rstudio/rmarkdown/releases/tag/v2.0), functions in **rmarkdown** also only accept UTF-8. It makes little sense to generate these two intermediate files now (e.g. d8fbf4c4641f9c3d3df13f77d7cb34fe01d3daab makes an unnecessary file copy), and I suggest that we stop generating them in a future version.

Additional benefits:

1. **blogdown** users no longer needs to ignore these files: https://github.com/rstudio/blogdown/blob/a6c92734/R/check.R#L51 It may also avoid the unnecessary refreshing of Hugo server.
2. **bookdown** users won't see these intermediate files, either: https://github.com/rstudio/bookdown/issues/986

**Comment by cderv** [comment]
`*.knit.md` is used for giving a name to the output file after knitting the `input`. 
I would think that we need to keep this intermediates that **knitr** will write and will be the entry file for Pandoc, and that we need to remove after a `render()`. 

For now, I opened a draft PR for some more test by only removing the `*.utf8.md`

**Comment by yihui** [comment]
For `*.knit.md`, I was thinking that we could just use the single extension `*.md`. This would solve the **bookdown** issue. However, it will be problematic for **blogdown** (it's easy to specify that Hugo should ignore `*.knit.md`, but not easy to ignore `*.md` since not all `*.md` files should be ignored).

I guess we can either keep `*.knit.md`, or add an option to specify the extension (e.g., `options(rmarkdown.knit.ext = '.md')` can be used for **bookdown**, and `options(rmarkdown.knit.ext = '.md~')` for **blogdown** since Hugo automatically ignores files that end with `~`). What do you think?

**Comment by cderv** [comment]
I am not quite sure why it will fix the issue for **bookdown**. Knitting the Rmd will still produce a `.md` file used for the HTML conversion. This file is not to keep and should be removed (unless `keep_md` is true). 
I find it quit informative to have this file labelle `*.knit.md`, you know it comes from the knitting process in render. Otherwise, `test.Rmd` will lead to `test.md` then `test.html`. 
it is highly possible that a `test.md` file exist in the working directory already and I am not sure we want to overwrite this one. This is because we render everything in the working dir by default so we need to be careful with filename. 

I may have missed why this is an issue for bookdown because the file would still be there but with a different name. Can you (re)explain please? 

The options mechanism you suggest would allow to modify behavior for different package.

**Comment by yihui** [comment]
You are right about **bookdown**. The intermediate `*.md` file will still be there. The problem won't be completely solved (with the PR #2098, it only reduces one intermediate file).

Let's keep `*.knit.md`. If it's easy enough, let's also add a global option for **blogdown** to customize the intermediate file extension.
