### ISSUE TITLE
Add alt text to images added to Ppt via rmarkdown 

### ISSUE THREAD

**Issue by jsgosnell** [rstudio/rmarkdown#2106]
When using rmarkdown to add images to PowerPoint files, the alt text designation in the image tag becomes the title/caption.  If using a web-based image, the url becomes the alt text. This isn't optimal for screen readers (the main reason I'm trying to add alt text to the images) (see answer provided to question on stackoverflow by Josh:  https://stackoverflow.com/questions/66959628/how-do-you-add-alt-text-for-accessibility-to-images-in-powerpoint-files-create). Is it possible to update the code so the alt text truly becomes alt text and the caption is handled elsewhere (like a fig.cap argument)?  

Example of issue:
````
---
title: "Making presentations in R"
author: "jsg"
date: "3/29/2021"
output: 
  powerpoint_presentation
---

## Issue example:  Puffin image

![This should be alt text and not caption](https://upload.wikimedia.org/wikipedia/commons/9/94/Puffin_Mrkoww.jpg)

````

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
        -  https://stackoverflow.com/questions/66959628/how-do-you-add-alt-text-for-accessibility-to-images-in-powerpoint-files-create
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rmarkdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rmarkdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by apreshill** [comment]
I'm seeing in both cases (local image and url) that the alt text populates the image path:
<img width="1436" alt="Screen Shot 2021-06-03 at 4 50 40 PM" src="https://user-images.githubusercontent.com/12160301/120725980-eff15180-c48b-11eb-9b79-c251f443c3b6.png">

<img width="1436" alt="Screen Shot 2021-06-03 at 4 50 27 PM" src="https://user-images.githubusercontent.com/12160301/120725969-e8ca4380-c48b-11eb-95a6-399394cf12c1.png">

**Comment by apreshill** [comment]
Source:

```
---

## Alt text does not work with urls

```
![look a puffin](https://upload.wikimedia.org/wikipedia/commons/9/94/Puffin_Mrkoww.jpg "Title: A proper puffin"){fig.alt="alt text: it is a very cute puffin."}
```

![look a puffin](https://upload.wikimedia.org/wikipedia/commons/9/94/Puffin_Mrkoww.jpg "Title: A proper puffin"){fig.alt="alt text: it is a very cute puffin."}

---

## Alt text does not work with local images either

```
![look a puffin](images/Puffin_Mrkoww.jpg "Title: A proper puffin"){fig.alt="alt text: it is a very cute puffin."}
```

![look a puffin](images/Puffin_Mrkoww.jpg "Title: A proper puffin"){fig.alt="alt text: it is a very cute puffin."}
```

**Comment by cderv** [comment]
Just for context for me later, there is several things in this issue. 

This markdown syntax
````markdown
![This should be alt text and not caption](https://upload.wikimedia.org/wikipedia/commons/9/94/Puffin_Mrkoww.jpg)
````
will be processed by Pandoc and not **knitr** or **rmarkdown** directly. So better support for alt text in the Markdown syntax is something to do on the Pandoc side. 

Doc about the syntax is here: https://pandoc.org/MANUAL.html#images 

> A link immediately preceded by a ! will be treated as an image. The link text will be used as the image’s alt text:
>
> ```
> ![la lune](lalune.jpg "Voyage to the moon")
> ```

But 

> Extension: implicit_figures
> An image with nonempty alt text, occurring by itself in a paragraph, will be rendered as a figure with a caption. The image’s alt text will be used as the caption.
> ```
> ![This is the caption](/url/of/image.png)
> ```

So `implit_figures` extentions could have an impact, and this is not clear which formats supports what. 

I have looked into this while working on adding `fig.alt` in **knitr** for figures. So this is related also to support for non HTML output format: https://github.com/yihui/knitr/issues/1967 
Main issues to support `fig.alt` chunk option for DOCX / PPTX is because this is buggy in Pandoc. 

With DOCX, the syntax would work (in some way) - see https://github.com/yihui/knitr/issues/1965#issuecomment-777584905

> `![A plot](test_files/figure-docx/unnamed-chunk-1-1.png "Description")`
> Will lead to having

> * "A plot" as a image caption/legend
> * Both "A plot" and "Description" as alternative text description in WORD I got
> ``` 
> Description
> 
> A plot
> ```

Oddly we don't get that with PPTX and I think you've found a new bug in Pandoc @apreshill ! It should at least be the same as with DOCX. I'll report that to Pandoc repo maybe.

**Comment by apreshill** [comment]
Thank you for filing that issue @cderv!

**Comment by apreshill** [comment]
I tried the syntax I did because JJ told me to try: `![figure caption goes here](img.png){fig.alt="alt text here"}` in another issue. "Alternatively you can just use the native pandoc syntax for alt (quoted text after the image path). include_graphics should definitely not be required"

**Comment by cderv** [comment]
Just to share that this will be taken into account in Pandoc. It has already been merged (see the issue in pandoc repo) and it will be available in a future Pandoc version.

**Comment by apreshill** [comment]
Here is the PR: https://github.com/jgm/pandoc/pull/7507

**Comment by cderv** [comment]
Since Pandoc 2.14.2, It is now possible to pass a description text to inlucde in Powerpoint using the Title part of the syntax
https://pandoc.org/MANUAL.html#images
````
![used as caption](link "Description")
````

So with original example this should be 
````markdown
---
title: "Making presentations in R"
author: "jsg"
date: "3/29/2021"
output: 
  powerpoint_presentation
---

## Issue example:  Puffin image

![This is the caption](https://upload.wikimedia.org/wikipedia/commons/9/94/Puffin_Mrkoww.jpg "And here is more information in description")
````

![image](https://user-images.githubusercontent.com/6791940/147359407-15a564bf-3b48-42fe-8d29-5bb05ce174e1.png)

This require a recent Pandoc which is included in RStudio current Daily version, and will be in next release. 

Thanks for opening this issue!
