### ISSUE TITLE
shinyAppDir function does not recognize global.R using Rmarkdown to embed a shiny app

### ISSUE THREAD

**Issue by lbcollins** [rstudio/rmarkdown#211]
What I did: Start RStudio. Open mytest.Rmd (in working directory). Click "Run Document".
What I see: "ERROR: object 'mylabel' not found" ('mylabel' is defined in global.R and referenced in server.R)

Note: runApp from console works fine (successfully references 'mylabel' from global.R)

See my R session info and all files that reproduce this error at https://github.com/lbcollins/shinyAppDir_and_global.R.git

**Comment by Auburngrads** [comment]
@yihui @jcheng5 Has this issue been addressed in the shiny package since the latest post in Nov 2014?  I've traced the differences between `runApp` and `shinyAppDir` to see how each handles the global.R file.  I see that `shinyAppDir` calls `shiny:::shinyAppDir_serverR` which does source global.R into server.R.  However, there doesn't appear to to be any connection between ui.R and global.R - which is the issue I'm having.  

Ideally, I'd like to be able to publish apps both on their own and as part of an Rmd document/presentation.  I'm aware that I can use `knitr::include_app` to pull an already-published app into an Rmarkdown doc/pres.  While this works great for pulling in one app, most of my lecture presentations have many apps in them (10 or more apps is not unusual).  In this case, calling `knitr::include_app` 10 times results in loading many of the same resources 10 times and causes the presentation to render very slowly when I navigate to the published app's URL.
