### ISSUE TITLE
Using pipe notation in header now breaks when compiling gitbook

### ISSUE THREAD

**Issue by daynefiler** [rstudio/rmarkdown#2132]
Using the default gitbook shipped with RStudio (1.4.1106) and adding the following line the the header in the index:

    copyright: |
      `r if(knitr:::is_latex_output()) paste(readLines("frontmatter/copyright.Rmd"), collapse = "\n  ")`

produces an error (before it did not):

    # [WARNING] Citeproc: citation R-bookdown not found
    # [WARNING] Citeproc: citation xie2015 not found
    # [WARNING] This document format requires a nonempty <title> element.
    #   Defaulting to 'testbook.knit' as the title.
    #   To specify a title, use 'title' in metadata or --metadata title="...".

Unfortunately, I am not sure what version I was using previously. This functionality used to allow me to pass data into the pdf (which still builds without issue). The resulting site does not have a title, author, date and does not find the citations resulting in an empty references section.

    rmarkdown::find_pandoc()
    # $version
    # [1] ‘2.11.4’
    # 
    # $dir
    # [1] "/Applications/RStudio.app/Contents/MacOS/pandoc"
    
    xfun::session_info("rmarkdown")
    # R version 4.0.5 (2021-03-31)
    # Platform: x86_64-apple-darwin17.0 (64-bit)
    # Running under: macOS Catalina 10.15.6, RStudio 1.4.1106
    # 
    # Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
    # 
    # Package version:
    #   base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.5   
    #   grDevices_4.0.5   highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.33       
    #   magrittr_2.0.1    markdown_1.1      methods_4.0.5     mime_0.10         rlang_0.4.11     
    #   rmarkdown_2.8.1   stats_4.0.5       stringi_1.5.3     stringr_1.4.0     tinytex_0.31     
    #   tools_4.0.5       utils_4.0.5       xfun_0.22         yaml_2.2.1       
    # 
    # Pandoc version: 2.11.4

**Comment by daynefiler** [comment]
You can see how I was using previously, [here](https://github.com/daynefiler/dissertation). I was compiling this in October/November of 2020 originally, but cannot guarantee I was version-current then.

**Comment by cderv** [comment]
I think you had previously a Pandoc version that allowed this and now using 2.11.4 makes this not working. 
I went further and tested Pandoc 2.1 and I don't have the issue. it happens with 2.5, 2.7.3 and 2.11.4 so somewhere in Pandoc version updates this gets unsupported. I don't know if this is an issue with Pandoc or if it is expected, we would need to ask Pandoc project.

If you want to make this work, you can downgrade Pandoc to the version that was working for you. You can also adapt your YAML so that it is not empty for HTML ? 
This is a Pandoc thing here. I don't think we can do much on **rmarkdown** or **knitr** side.

BTW, is `copyright` variable only used in PDF template ? Is it used in HTML template to ? 
What is inside of `frontmatter/copyright.Rmd` ? Is this only Markdown text ? 

If the variable is it is not used in HTML template, you could probably don't bother testing the output type and use 
```
copyright: | 
  `r paste(readLines("frontmatter/copyright.Rmd"), collapse = "\n  ")`
```
The value of `copyright` would be ignore and not used by Pandoc for HTML conversion. 

You could also use Pandoc Raw block so that this is ignored by Pandoc depending on the output. See example for header-includes here: https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

Something like 

````
copyright: | 
  ```{=latex}
  `r paste(readLines("frontmatter/copyright.Rmd"), collapse = "\n  ")`
  ```
```

Anyway, if you want this to work with new Pandoc, you need a workaround. It could be worth opening an issue in Pandoc for why this change but if a bug it would be fixed in later version. 

Hope it helps
