### ISSUE TITLE
[FR] MathJax scale to fit container

### ISSUE THREAD

**Issue by englianhu** [rstudio/rmarkdown#2135]
---

There has 2 ways to adjust the alignment of LaTex output

**Mehotd 1:** [MathJax scale to fit container](https://codepen.io/mathjax/pen/qEdqPg)

```css
.box {
  margin: 1em auto 0 auto;
  border: 2px solid black;
  padding: 0 20px;
  width: 20em;
}
```
---
**Mehotd 2:** [align, aligned and R Markdown](https://tex.stackexchange.com/questions/284538/align-aligned-and-r-markdown)

So, just to be clear (as it says this is unanswered), just write the align (without $$):

```r
\begin{align}
a_1 &= \beta_0 \\
b_1 &= \beta_1 \\
c_1 &= \beta_2 \\
d_1 &= \beta_3
\end{align}
```
and not
```r
$$
\begin{align}
a_1 &= \beta_0 \\
b_1 &= \beta_1 \\
c_1 &= \beta_2 \\
d_1 &= \beta_3
\end{align}
$$
```

Is it possible to apply **CSS** to adjust the alignment?

**Reference :**

- [align, aligned and R Markdown](https://tex.stackexchange.com/questions/284538/align-aligned-and-r-markdown)
- [MathJax scale to fit container](https://codepen.io/mathjax/pen/qEdqPg)
- [rmarkdown-book/03-documents.Rmd : MathJax equations](https://github.com/rstudio/rmarkdown-book/blob/master/03-documents.Rmd)

**Comment by cderv** [comment]
Hi @englianhu, 

Unfortunately, I am not sure to understand the issue here. It would be helpful to have a clear minimal example of the issue as asked in the issue template and guide ? What I mean is a Rmd document that we can render and which show what the issue is with **rmarkdown**. 

If this is a CSS question for HTML output, please ask too on Q&A website: https://yihui.org/issue/#got-a-question

Thank you

**Comment by cderv** [comment]
Our last comment did not get answered since May. I will assume you have found a solution since then. 

Please reopen and provide a reproducible example so that you help us help you by better understanding the issue. Thank you !
