### ISSUE TITLE
Emacs, mode poly-markdown+r, and render()

### ISSUE THREAD

**Issue by lgautier** [rstudio/rmarkdown#215]
Hi,

I have the following first line in an .Rmd file in order to tell Emacs which mode I'd like to use:

```
## -*- mode: poly-markdown+r; -*-
```

Everything is looking great until I call `render()`, as that line is rendered verbatim in the resulting document.

Could an option be added to `render()` ? (e.g., `skip_n_first_lines`=1)

**Comment by yihui** [comment]
`##` means the second-level section heading in Markdown instead of comments, so we probably cannot ignore it for the sake of a specific text editor. If Emacs could support the real comment syntax `<!-- -->`, rmarkdown won't have problems rendering the file. The other approach is to let Emacs ignore it temporarily when rendering the file (or whatever extension that supports `poly-markdown+r`).
