### ISSUE TITLE
[FR] Code chunk reusing for separate chunk running

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rmarkdown#2161]
Just a suggestion from a view without any consideration of how hard it could be operated. 

Glad to learn the tricks to reuse both chunk contents and options by the [Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/reuse-chunks.html) and  [Yihui's blog](https://yihui.org/en/2021/05/knitr-reuse/). Regarding the chunk content reusing, none of the three ways introduced by the cookbook seems to work for separated chunk running (what ctrl+shift+k initiates). It's understandable since the reusing is based on `knitr`,  but it would be convenient if the separated chunk running could also recognize `<<>>` or `ref.label` someday in the future. In many cases, people run through the codes before compiling the entire document. If the reusing chunk was not recognizable for running the chunk separately, it may be less efficient than just creating a unique object for either the function or output of the chunk, I guess?

**Comment by cderv** [comment]
Hi @sammo3182, 

Thanks for the suggestion ! 

This would be a feature request for the RStudio IDE. The interactive evaluation of Rmd chunks are done by the IDE directly and it is possible that all knitr behavior are not yet correctly respected. 

We'll pass the suggestion but you can also open a feature request in https://github.com/rstudio/rstudio so that the IDE team can track the idea, and the community can vote of this feature.

Thanks !
