### ISSUE TITLE
LaTeX xcolor Clash

### ISSUE THREAD

**Issue by rcyost** [rstudio/rmarkdown#2169]
Trying to use Render function to create PDF output with formatted tables:
Similar Issues Found but solutions provided didn't work:
- https://stackoverflow.com/questions/48014265/unable-to-use-format-latex-in-knitrkable-within-a-rmarkdown-document-g?rq=1
- https://stackoverflow.com/questions/60011425/kableextra-error-in-markdown-when-rendering-to-pdf
- https://github.com/pbs-assess/TTTworkshop/issues/29

Session:
![image](https://user-images.githubusercontent.com/32645001/122607496-a5093980-d048-11eb-9f94-687d053fe4e0.png)

Output Rmd:
![image](https://user-images.githubusercontent.com/32645001/122608051-93746180-d049-11eb-8af4-eae2db79c0cf.png)

Trying to use render:
![image](https://user-images.githubusercontent.com/32645001/122607636-e1d53080-d048-11eb-8f69-46b9acf8fd2c.png)

Error:
![image](https://user-images.githubusercontent.com/32645001/122607649-e7327b00-d048-11eb-8991-9c00d284ec11.png)

**Comment by cderv** [comment]
I believe this is related to other question asked in the past. See https://github.com/rstudio/rmarkdown/issues/1882#issuecomment-682443444
This is a LaTeX issue when you are trying to define two times options for a package. See about this error in TeX FAQ: https://texfaq.org/FAQ-optionclash
**rmarkdown** is use the default Pandoc's template for LaTeX and it already contains `\usepackage{xcolor}`, you can't define that in your preamble a second time.

I believe you need to use a correct preamble if you want to modify some options for xcolor using `\PassOptionsToPackage`. Probably `\PassOptionsToPackage{table}{xcolor}` from what I saw in your screenshots. (please next time copy paste the content so that we want also copy paste and try it out). 

I don't think this is an issue with **rmarkdown** directly. Maybe something with **kableExtra** but I believe this is just due to the conflict between default behavior, and your custom tweaks you are inserting in `header-includes`

Hope it helps

**Comment by rcyost** [comment]
---
title: "test"
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
output:
  pdf_document:
    keep_tex: yes
    number_sections: yes
    toc: yes
---


```{r}

options(kableExtra.latex.load_packages = FALSE)
options(knitr.table.format = "latex") 
library(kableExtra)

m <-  as.data.frame(matrix(c(.5, .2, .2, .5), nrow = 2, byrow = TRUE))


a <- kbl(m, format="latex")%>%
    kable_styling(full_width = F) %>%
    row_spec(0:length(m), color = "black")

a

```

**Comment by rcyost** [comment]
rmarkdown::render(
                  input = file.path("testTable.Rmd"),
                  
                  output_file = paste("testTable.pdf"),
                  
                  output_format = "pdf_document",
                  
                  # start fresh environment for each render
                  envir = new.env()
                  
)

**Comment by cderv** [comment]
Thanks for sharing the screenshot content. Did you try to change your preamble accordingly to the advice above? 

You are still loading xcolor yourself in header-includes and it is already loaded by the template. So the conflict probably comes from there.

**Comment by rcyost** [comment]
Yes this header worked: 
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
  - \PassOptionsToPackage{table}{xcolor}

Sorry this wasn't really an rmarkdown issue but I spent over a day trouble shooting so you certainty have my gratitude.

**Comment by cderv** [comment]
No worries ! Glad it works now.
