### ISSUE TITLE
Website page on citations: CSL-YAML format is not enlisted

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rmarkdown#2179]
At https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html it seems that CSL-YAML, which AFAIK is pandoc's alternative representation of CSL-JSON (hence fully compatible), is not enlisted:

> ![afbeelding](https://user-images.githubusercontent.com/19164640/124599065-8e931880-de65-11eb-88f8-dc15fa0884d3.png)

So I think it should be added, especially since it's supported by RStudio VME.

Compared to CSL-JSON, I believe that CSL-YAML has superior human-readability.

**Comment by cderv** [comment]
Thanks ! 

This page clearly needs some update. We'll make sure to add this when updating the website soon.

**Comment by yihui** [comment]
That document was copied from Pandoc's manual quite a few years ago. Personally I tend not to copy the documentation of a third-party software package because it would mean that we have to maintain it. In the past, we had two other pages copied from Pandoc's documentation, and I have redirected them back to Pandoc's official documentation:

https://github.com/rstudio/rmarkdown/blob/42f8bd141ed8cfd1ff249273385eb5d037e9b1bb/_redirects#L24
https://github.com/rstudio/rmarkdown/blob/42f8bd141ed8cfd1ff249273385eb5d037e9b1bb/_redirects#L6

Unless anyone has objections, I suggest that we redirect https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html to https://pandoc.org/MANUAL.html#citations.

**Comment by florisvdh** [comment]
Sounds good!

Not sure if I understand it right, but with the cited code lines do you mean that https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html already redirects? Contents differ from https://pandoc.org/MANUAL.html#pandocs-markdown though, seems an older version. Also, https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html also includes the subsequent headers from https://pandoc.org/MANUAL.html such as https://pandoc.org/MANUAL.html#citations - still at an older version.

**Comment by florisvdh** [comment]
Works excellent; thank you!
