### ISSUE TITLE
Rmarkdown file with over 2500 command lines

### ISSUE THREAD

**Issue by bendeivide** [rstudio/rmarkdown#2186]
Hello. I created a .Rmd file whose command lines exceed 2500 lines. When rendering the page, I notice that the final part has problems. I checked the page through the Firefox browser, the rendering is normal, no problems. But opening in Chrome browser, the bottom of the page has problems. What to do?

**Comment by cderv** [comment]
Hi, 

If the rendering is normal in Firefox, it means the HTML file produced is ok. It could mean the Chrome Browser has difficulties loading this file correctly. This leads to a Web browser issue really, and not a rmarkdown one. However, maybe you can tweak the rendering to make the user experience better in the browser.

What [rmarkdown does](https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-process.html) is converting a Rmd file to Markdown then to HTML using Pandoc. By default, a single Rmd file using `html_document()` will produce a single HTML file, self-contained, so with everything embeded in one HTML files. If you are using a lot of web resources among those numerous command line (like html widgets, or plots, or anything than just text), this mean everything will be encoded in the HTML file, which could be really heavy (you can check the size). This also includes all the possible JS library you need to render (like if you are using plotly, DT, or leaflet...). 
As I don't know your content, it is hard to be more precise.

On possible solution that could help is trying to reduce the size of the HTML file to reduce the loading time in the browser. If you set `self_contained: FALSE` for the rendering, then the resulting HTML file will be a lot smaller in size as every resources will be externalized. This means that you won't have a single HTML file to share but rather a folder with a HTML files and files/folder with web libraries used and other resources. The browser will then load those resources but won't have to decode them as no more embedded. You can try that. 

If this is still difficult, than you could try splitting the single HTML file into a website. A lot of web content are not single page but multi pages. You can do that easily with [R Markdown website](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html) for example. Using a book project like with **bookdown** is another solution for multipage content. By using a project like this, the dependencies of your single file will be shared across multiple files, and your user would navigate through several smaller HTML files instead of one big HTML file. This should result in a way faster user experience as one HTML page will be quicker to load than all the pages at once. 

So basically, when this is a browser issue, you need to investigate on the rendered side as things could be caused by load time. Using a plot as image will be for example quicker to load and experience for a user than an interactive graph with lots of data. So you could also adapt the content to that. 
Also, Chrome has features for analyzing performance in the [devtools pane](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/). You could also find what is causing the specific issue in the browser with your file. 

I hope this helps. It is as much as I could share with the information you shared. Please go ask for advice and others's experience in community like https://community.rstudio.com. Some users may have encountered already some similar challenges. 

If you can share more details on your use case (with an example) and you think there is something we can improve in the tool, please tell us. We just need more information than just a general question like this one.

**Comment by bendeivide** [comment]
Thank you very much. You ended up suggesting many possible solutions.
