### ISSUE TITLE
Shiny prerendered documentation page missing examples

### ISSUE THREAD

**Issue by j-andrews7** [rstudio/rmarkdown#2187]
The [documentation page](https://rmarkdown.rstudio.com/authoring_shiny_prerendered.HTML) for Shiny prerendered documents is missing most of the example chunks. Some are there, most are not.

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

**Comment by cderv** [comment]
Thanks for the report. 

There is indeed something not right with the way we load the example. For reference, we have error in browser console with the loading:
![image](https://user-images.githubusercontent.com/6791940/125962847-c56a8fad-1586-461d-a245-8605bddba55c.png)

I'll try to see what has changed.

**Comment by cderv** [comment]
@apreshill I found the why. 

This page is using resources that where stored in `flexdashboard/` folder. See the Rmd source. 

https://github.com/rstudio/rmarkdown/blob/a40b26412c1b0c2cdc7149d51b5bff0864418237/authoring_shiny_prerendered.Rmd#L10-L12

These resources where removed in 38841ed76d2f394e378fe88a1f1115a29bbee1c2 (https://github.com/rstudio/rmarkdown/pull/2131) when working on switching **flexdashboard** website. 

We just need to bring back those resources here so that it is fixed.

@yihui are you in charge of this website ? I don't manage to build correctly this website, and you may already have the correct environment for this right ?

**Comment by cderv** [comment]
Also, I can confirm that those resources are only used in this page `authoring_shiny_prerendered.html` and not others.

We could also possibly load them from where they live now ? 

For the context, with the new flexdahboard website, we have moved them in [**quillt**](https://github.com/rstudio/quillt/tree/master/inst/pkgdown/assets) template. So they are available on any pkgdown website using the theme. 

For example: 
* https://pkgs.rstudio.com/flexdashboard/ace-1.2.3/ace.js
* https://pkgs.rstudio.com/flexdashboard/holder-2.9.0/holder.min.js
* https://pkgs.rstudio.com/flexdashboard/snippets/snippets.js

We could also load them for there maybe.

**Comment by yihui** [comment]
I just fixed the URLs of these JS scripts. Thanks!

**Comment by cderv** [comment]
Thanks. It is working now.
