### ISSUE TITLE
.Rproj working directory in rmarkdown failure

### ISSUE THREAD

**Issue by pallomamarciano** [rstudio/rmarkdown#2225]
Hi there,

I am working with .Rproj relatives paths in Rmarkdown. Unfortunately, in the last few days, every time I use a chunk to access files or write files in the project folders, the following error appears:

`Error: '' does not exist in current working directory ''.`

However, when I use the same code in the Console, it works perfectly. 

In the screenshot, it is possible to see the problem and the same code working:

<img width="960" alt="2021-09-28" src="https://user-images.githubusercontent.com/38811416/135146377-95fefca9-4129-4be0-b4b5-881ef5a2de8f.png">

```
xfun::session_info('rmarkdown')
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1717

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  bslib_0.3.0      digest_0.6.27    evaluate_0.14    fastmap_1.1.0    fs_1.5.0         glue_1.4.2       graphics_4.1.1  
  grDevices_4.1.1  highr_0.9        htmltools_0.5.2  jquerylib_0.1.4  jsonlite_1.7.2   knitr_1.35       magrittr_2.0.1   methods_4.1.1   
  R6_2.5.1         rappdirs_0.3.3   rlang_0.4.11     rmarkdown_2.11.2 sass_0.4.0       stats_4.1.1      stringi_1.7.4    stringr_1.4.0   
  tinytex_0.34     tools_4.1.1      utils_4.1.1      xfun_0.25        yaml_2.2.1      

Pandoc version: 2.11.4
```

**Comment by cderv** [comment]
Hi, 

Thanks for the report. 

Where is your Rmd document located ? Is it in the root directory or in a subfolder of the project ? 
Is the path passed to `read_delim()` relative to the root project directory or relative to the Rmd document folder ? Meaning is `data/` folder at the same level of the Rmd file ? 


I ask all this because 
* your console will execute code by default from a Working directory which should be the project one. 
* The Rmd document will by default execute the code chunk relatively to the Rmd document itself. 

This is explained in detail in this chapter of our last book
https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html

THe **here** package can be a good tool when you organize your project and Rmd resources in more complex structure than local to the Rmd file.See https://here.r-lib.org/articles/rmarkdown.html

We mentioned it in the book chapter. 

Hope it helps

**Comment by cderv** [comment]
Hello @pallomamarciano, 

There is no answer since my last comment in September. 

I'll close this as we are doing a bit of triaging in our issue board. Please comment and reopen if there is still something to help you with. 

Thanks.
