### ISSUE TITLE
[FR] accessing filename and path of selected file in parameters file dialog

### ISSUE THREAD

**Issue by mariodejung** [rstudio/rmarkdown#2248]
I started to use the parameters dialog for creating markdown documents and knitting with parameters. This makes it easy for the (not programming) user to give manual inputs.
What I miss in the "file" dialog is retrieving the file names of the input files.

This would give me the possibility to retrieve also the original file path and create analysis figures as pdf in the same folder as the input file, as well as give the files the "input file name as prefix".

So far, that dialog gives only the path to the uploaded temporary file.

It would be great to have that "click and browse to location" possibility to get correct file and folder names, because typing all by hand are a little bit error prone.

**Comment by cderv** [comment]
Hello @mariodejung 

By file dialog you mean this ? 
````yaml
---
title: My Document
output: html_document
params:
  data:
    label: "Input dataset:"
    value: results.csv
    input: file
---
````

doc: https://bookdown.org/yihui/rmarkdown/params-knit.html#the-interactive-user-interface

**rmarkdown** is taking advantage of `shiny::fileInput()` which will upload the file to the server, being here a temp directory. It won't use directly the local file provided by as input. This behavior is from **shiny** directly and we can't really control it on our side. 

> What I miss in the "file" dialog is retrieving the file names of the input files.

You are seeking the original file path ? 

> So far, that dialog gives only the path to the uploaded temporary file.

This is because of how `shiny::fileInput()` is working. 

> It would be great to have that "click and browse to location" possibility to get correct file and folder names, because typing all by hand are a little bit error prone.

Can you give an example ? i am not sure to understand for sure what you mean. Do you want original file path ?

**Comment by mariodejung** [comment]
>You are seeking the original file path ?
...
> Can you give an example ? i am not sure to understand for sure what you mean. Do you want original file path ?

Hi @cderv 
this is exactly what I am looking for. 
For example, I have a markdown script, which reads files as an input (I would love to provide with the `shiny::fileInput()` dialog) and I want to create a few output files. For the output files, it would be create to save them in the same folder as the input file. Thats why I was wondering, if there is a way to retrieve the absolute file path of the input file.

So far, when I want to write files in a specific folder, the user has to write the file path by hand, which gives error on typos or so. A handy folder selection (bz navigating with mouse and click) dialog would be nice! Or, for my specific example, retrieving the input file name and using `dirname()` function to get to folder path.

This is what I have in mind. Not sure if it is to specific or if there are better ways to at least "select" an output folder by clicking on a file path in a browser... But it would be handy.


Best
Mario

**Comment by cderv** [comment]
> This is what I have in mind. Not sure if it is to specific or if there are better ways to at least "select" an output folder by clicking on a file path in a browser... But it would be handy.

This is rather specific for **rmarkdown** because it is not a tool to build user interface for app in the first place. **Shiny** is that tool and that is why **rmarkdown** is leveraging shiny input for this within the RStudio IDE. 

I don't know if `shiny::fileInput()` can do something like you want. The temporary filepath copy could be there for security purposes so that a web app cannot access a user disk space: file is uploaded to the webapp so that it can be read and it is not the webapp which reads the local file. 

In the shiny ecosystem there is [shinyFiles](https://github.com/thomasp85/shinyFiles) which alllows an app to access local file. However, this would not be used with param and the rmarkdown report would need to be generated from input retrieve from a shinyApp maybe. Did you explore building a shinyapp for this ? 

Anyway, for what you descrived to be possible in **rmarkdown**, it would need to be supported in `shiny::fileInput()` I believe. Otherwise, it would be quite specific to **rmarkdown**.

**Comment by yihui** [comment]
I doubt if `shiny::fileInput()` would ever support this. If it won't, I'm afraid there's little that we could do on our side.

That said, there are other ways to interactively select files/dirs in R, such as `file.choose()`, `tcltk::tk_choose.dir()`, `tcltk::tk_choose.files()`, `rstudioapi::selectFile()`, `rstudioapi::selectDirectory()`, etc. Each way has its pros and cons, e.g., may not be cross-platform, may depend on RStudio IDE, may not work in a non-interactive R session, etc.
