### ISSUE TITLE
shinyApp / flexdashboard height issues

### ISSUE THREAD

**Issue by SiSch90** [rstudio/rmarkdown#2259]
I am using flexdashboard with RMarkdown to create an application. However the height of the application is compressed since making use of the rmarkdown package version newer than 2.4.  

The described problem only occurred with the new R-Studio version 1.4.1717 and the associated new version of the rmarkdown package. After installing the old version of the package everything works as usual.

![Example](https://user-images.githubusercontent.com/96174833/146165925-c1f914da-df85-4942-b85b-6300d99f9e21.jpg)

Example: 

```{r}
---
title: "Test"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r example}

library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Value boxes"),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      # A static valueBox
      valueBox(10 * 2, "New Orders", icon = icon("credit-card")),

      # Dynamic valueBoxes
      valueBoxOutput("progressBox"),

      valueBoxOutput("approvalBox")
    ),
    fluidRow(
      # Clicking this will increment the progress amount
      box(width = 4, actionButton("count", "Increment progress"))
    )
  )
)

server <- function(input, output) {
  output$progressBox <- renderValueBox({
    valueBox(
      paste0(25 + input$count, "%"), "Progress", icon = icon("list"),
      color = "purple"
    )
  })

  output$approvalBox <- renderValueBox({
    valueBox(
      "80%", "Approval", icon = icon("thumbs-up", lib = "glyphicon"),
      color = "yellow"
    )
  })
}

shinyApp(ui, server)
```

**Comment by cderv** [comment]
I can reproduce using your example. It is not minimal enough to know from where the configuration comes from. 
You are using flexdashboard with rmarkdown using shiny compent to insert a shinydashboard. 

Just curious why you are inserting a shinydashboard within a flexdahsboard, and not building the dahsboard using flexdashboard only or shinydashboard only ? 

Both have similar component and I am not sure to see the value of inserting a shinydashboard app inside a flexdashboard. 

I ask this because there could be an interaction of some sort in the CSS and JS from those tools.

Anyway, I may move this to the flexdashboard repo as I don't think this is something directly related to **rmarkdown** which lower level in this case. 🤔

**Comment by cderv** [comment]
Can you also share you package version ? Your session info so that we can compare ? 

rmarkdown 2.4 is an older version. Do you know which version this above was working ?

**Comment by cderv** [comment]
Issue seems to be that the iframe is inserted into a `<p>` element which get a small height size. 
Setting the size manually to 100% fix the issue - I am still not convince that this iframe should be inside a `<p>` element though... 

Something seems off in the current usage :think

**Comment by SiSch90** [comment]
Yes, you are right! This mixing wasn't a good example I guess.

Another small example: 

````{r}
---
title: "Vergleichskaufpreisermittlung - Ein-/Zweifamilienhäuser"
output:
  flexdashboard::flex_dashboard:
  orientation: columns
  vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
#library(tidyverse)
#library(shiny)
#library(shinyWidgets)
library(leaflet)
library(leaflet.extras)
#library(mapview)
#library(DT)
#library(plotly)
#library(rmarkdown)
#library(rstudioapi)
#library(sf)
#library(ggmap)
#library(XLConnect)
#library(readxl)

RuFo <- function(Zahl, Nachkomma = 0){  format(round(Zahl, Nachkomma), decimal.mark = ",", big.mark = ".", nsmall = Nachkomma, na.encode = FALSE)}  

ZoomPos_KK <- c(6.13615,51.79282,12)

#Kartendefinition
Karte <- function()
          {
            leaflet() %>%
            addProviderTiles(providers$CartoDB.Positron,
                             options = providerTileOptions(minZoom = 10, maxZoom = 16),                 
                             group="Karte") %>% 
            addProviderTiles(providers$Esri.WorldImagery, group="Luftbild",
                             options = providerTileOptions(minZoom = 10, maxZoom = 20)) %>%
            addWMSTiles(baseUrl = "http://www.wms.nrw.de/geobasis/wms_nw_alkis_grau", 
                         layers = c("adv_alkis_gebaeude","adv_alkis_flurstuecke"),
                        options = providerTileOptions(minZoom = 17, maxZoom = 20),
                          group = "Karte") %>%
            addWMSTiles(baseUrl = "https://alkisservices.krzn.de/WMS_ALKIS_kleve/FlurkarteADV", 
                         layers = c("adv_alkis_gebaeude","adv_alkis_flurstuecke"),
                        options = providerTileOptions(minZoom = 17, maxZoom = 20),
                          group = "ALKIS (KRZN)") %>%
            addLayersControl(baseGroups=c("Karte","Luftbild", "ALKIS (KRZN)"),overlayGroups = c("Kauffälle"), options = layersControlOptions(collapsed = TRUE)) %>% 
            hideGroup("ALKIS (KRZN)") %>% 
            addScaleBar() %>% 
            addResetMapButton() %>% 
            addSearchOSM() # %>% 
         # addMouseCoordinates()
  }

```

```{r Übersichtskarte, height = "100%"}

ui <- fluidPage(
  fluidRow(style = " overflow: auto;  height: calc(100vh - 50px) !important;",
      mainPanel("Karte",leafletOutput("map")))
)
      

server <- function(input, output,session) {
  
output$map <- renderLeaflet({  Karte() %>% setView(lng=ZoomPos_KK[1],lat=ZoomPos_KK[2],zoom=ZoomPos_KK[3])   })

}

shinyApp(ui, server)
````

Current Package Versions:
flexdashboard 0.5.2
rmarkdown 2.11

Session Info:
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.5.4   compiler_4.1.0      magrittr_2.0.1      fastmap_1.1.0       htmltools_0.5.2     tools_4.1.0         flexdashboard_0.5.2
 [8] yaml_2.2.1          DT_0.19             rmarkdown_2.11      knitr_1.36          jsonlite_1.7.2      xfun_0.24           digest_0.6.27      
[15] rlang_0.4.11        evaluate_0.14      

The described problem has occurred since version 2.6 of the rmarkdown package I guess. 

However, you may be right that the problem is caused by the flexdashboard package and is not directly related to the rmarkdown stuff.

**Comment by cderv** [comment]
It is another example with including a shinyapps. Does it happen only in that case ?

**Comment by cderv** [comment]
Including only the leaflet map works as expected 
````markdown
---
title: "Vergleichskaufpreisermittlung - Ein-/Zweifamilienhäuser"
output:
  flexdashboard::flex_dashboard:
  orientation: columns
  vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(leaflet)
library(leaflet.extras)

RuFo <- function(Zahl, Nachkomma = 0){  format(round(Zahl, Nachkomma), decimal.mark = ",", big.mark = ".", nsmall = Nachkomma, na.encode = FALSE)}  

ZoomPos_KK <- c(6.13615,51.79282,12)

#Kartendefinition
Karte <- function()
          {
            leaflet() %>%
            addProviderTiles(providers$CartoDB.Positron,
                             options = providerTileOptions(minZoom = 10, maxZoom = 16),                 
                             group="Karte") %>% 
            addProviderTiles(providers$Esri.WorldImagery, group="Luftbild",
                             options = providerTileOptions(minZoom = 10, maxZoom = 20)) %>%
            addWMSTiles(baseUrl = "http://www.wms.nrw.de/geobasis/wms_nw_alkis_grau", 
                         layers = c("adv_alkis_gebaeude","adv_alkis_flurstuecke"),
                        options = providerTileOptions(minZoom = 17, maxZoom = 20),
                          group = "Karte") %>%
            addWMSTiles(baseUrl = "https://alkisservices.krzn.de/WMS_ALKIS_kleve/FlurkarteADV", 
                         layers = c("adv_alkis_gebaeude","adv_alkis_flurstuecke"),
                        options = providerTileOptions(minZoom = 17, maxZoom = 20),
                          group = "ALKIS (KRZN)") %>%
            addLayersControl(baseGroups=c("Karte","Luftbild", "ALKIS (KRZN)"),overlayGroups = c("Kauffälle"), options = layersControlOptions(collapsed = TRUE)) %>% 
            hideGroup("ALKIS (KRZN)") %>% 
            addScaleBar() %>% 
            addResetMapButton() %>% 
            addSearchOSM() # %>% 
         # addMouseCoordinates()
  }

```

```{r Übersichtskarte}
Karte() %>% setView(lng=ZoomPos_KK[1],lat=ZoomPos_KK[2],zoom=ZoomPos_KK[3])
```
````

So this comes from shiny inclusion it seems

**Comment by SiSch90** [comment]
You're right. The problem only seems to appear when integrating shiny in this way.

However, I still don't understand why the problem only occurs when a new rmarkdown version (or a newer R-Studio version) has been installed. The presentation of the dashboards was still different under the old versions or, to be more precise, the entire height of the browser screen was used for displaying the content.

**Comment by cderv** [comment]
> However, I still don't understand why the problem only occurs when a new rmarkdown version (or a newer R-Studio version) has been installed. The presentation of the dashboards was still different under the old versions or, to be more precise, the entire height of the browser screen was used for displaying the content.

A lot of things can get updated in this process: The new RStudio version can require a new package version, and one package in the mix has a regression. 

Do you know with which version it was working ? 

I think we can get a minimal example based on shiny demo app: 

````markdown
---
title: "Test"
output: 
  flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
ui <- fluidPage(titlePanel("Hello Shiny!"),
                sidebarLayout(sidebarPanel(
                  sliderInput(
                    inputId = "bins",
                    label = "Number of bins:",
                    min = 1,
                    max = 50,
                    value = 30
                  )
                ),
                mainPanel(plotOutput(outputId = "distPlot"))))
server <- function(input, output) {
  output$distPlot <- renderPlot({
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    hist(
      x,
      breaks = bins,
      col = "#75AADB",
      border = "white",
      xlab = "Waiting time to next eruption (in mins)",
      main = "Histogram of waiting times"
    )
  })
}
shinyApp(ui, server)
```
````

![image](https://user-images.githubusercontent.com/6791940/146250267-373dcfa0-fb56-405a-9160-e56f0b5061e2.png)


This would be an issue for **flexdashboard** I think. 

@cpsievert what do you think of this ? 

<details>
<summary>Session Info</summary>

````r
> sessioninfo::session_info()
- Session info ----------------------------------------------------------------------------
 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64 (build 19043)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  French_France.1252
 ctype    French_France.1252
 tz       Europe/Paris
 date     2021-12-15
 rstudio  2022.02.0-daily+323 Prairie Trillium (desktop)
 pandoc   2.16.2 @ C:/Users/chris/scoop/apps/rstudio-daily/current/bin/quarto/bin/ (via rmarkdown)

- Packages --------------------------------------------------------------------------------
 package       * version    date (UTC) lib source
 askpass         1.1        2019-01-13 [1] CRAN (R 4.1.0)
 bslib           0.3.1      2021-10-06 [1] CRAN (R 4.1.1)
 cachem          1.0.6      2021-08-19 [1] CRAN (R 4.1.1)
 Cairo           1.5-12.2   2020-07-07 [1] RSPM
 cli             3.1.0      2021-10-27 [1] CRAN (R 4.1.2)
 crayon          1.4.2      2021-10-29 [1] CRAN (R 4.1.1)
 credentials     1.3.2      2021-11-29 [1] CRAN (R 4.1.1)
 curl            4.3.2      2021-06-23 [1] CRAN (R 4.1.0)
 digest          0.6.29     2021-12-01 [1] CRAN (R 4.1.1)
 ellipsis        0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 evaluate        0.14       2019-05-28 [1] CRAN (R 4.1.0)
 fastmap         1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
 flexdashboard   0.5.2.9000 2021-12-15 [1] Github (rstudio/flexdashboard@33458ea)
 htmltools       0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
 httpuv          1.6.4      2021-12-14 [1] CRAN (R 4.1.2)
 jquerylib       0.1.4      2021-04-26 [1] CRAN (R 4.1.0)
 jsonlite        1.7.2      2020-12-09 [1] CRAN (R 4.1.0)
 knitr           1.36       2021-09-29 [1] CRAN (R 4.1.1)
 later           1.3.0      2021-08-18 [1] CRAN (R 4.1.1)
 lifecycle       1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
 magrittr        2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
 mime            0.12       2021-09-28 [1] CRAN (R 4.1.1)
 openssl         1.4.5      2021-09-02 [1] CRAN (R 4.1.1)
 promises        1.2.0.1    2021-02-11 [1] CRAN (R 4.1.0)
 prompt          1.0.1      2021-03-12 [1] CRAN (R 4.1.0)
 R6              2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp            1.0.7      2021-07-07 [1] CRAN (R 4.1.0)
 rlang           0.4.12     2021-10-18 [1] CRAN (R 4.1.2)
 rmarkdown       2.11.3     2021-12-15 [1] Github (rstudio/rmarkdown@69e6f98)
 rsconnect       0.8.25     2021-11-19 [1] CRAN (R 4.1.2)
 rstudioapi      0.13       2020-11-12 [1] CRAN (R 4.1.0)
 sass            0.4.0      2021-05-12 [1] CRAN (R 4.1.0)
 sessioninfo     1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
 shiny         * 1.7.1.9002 2021-12-15 [1] Github (rstudio/shiny@9389160)
 stringi         1.7.6      2021-11-29 [1] CRAN (R 4.1.1)
 stringr         1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
 sys             3.4        2020-07-23 [1] CRAN (R 4.1.0)
 xfun            0.29       2021-12-14 [1] CRAN (R 4.1.2)
 xtable          1.8-4      2019-04-21 [1] CRAN (R 4.1.0)
 yaml            2.2.1      2020-02-01 [1] CRAN (R 4.1.0)

 [1] C:/Users/chris/Documents/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.1/library

-------------------------------------------------------------------------------------------
````


</details>

**Comment by cpsievert** [comment]
I can at least confirm that upgrading from rmarkdown 2.5 to 2.6 adds an additional `<p>` around the `<iframe>` (maybe this is pandoc thing?), which causes the height difference. 

Assuming there is no way out of getting rid of the `<p>` wrapper via rmarkdown/pandoc/knitr, feel free to transfer to flexdashboard and we can investigate a fix over there

**Comment by SiSch90** [comment]
Yes, exactly! Since I have a R-Studio version that requires at least rmarkdown version 2.6, the problem has existed.

Many thanks to you both for the help, I will transfer to flexdashboard. Hence, thread can be closed.

**Comment by cderv** [comment]
Let's reopen so that I can check this `<p>` thing. Thanks @cpsievert for finding this. I tried to compare some version but did not get to this conclusion. I'll try to test several pandoc version to check if this is related to Pandoc. 

@SiSch90 if necessary, we'll tranfer the issue ourself from one repo to the other. Thanks for opening the issue!

**Comment by cderv** [comment]
I have seen you already open one though. For reference: https://github.com/rstudio/flexdashboard/issues/379

**Comment by SiSch90** [comment]
Thank you very much!

**Comment by cderv** [comment]
@cpsievert Thanks for pointing out the version that triggered the breakage. I believe this comes from the new way in **rmarkdown** 2.6 to use `htmltools::html_preserve()`. **htmltools** 0.5.1 has introduce the use of Pandoc's raw attributes. Previously, it was a R Markdown trick : **htmltools** would introduce magic comment `<!--html_preserve-->` and `<!--/html_preserve-->` so that the inner content can be preserve asis. But then, Pandoc's raw attributes was used
````markdown
```{=html}
content
```
````
or 
````markdown
`content`{=html}
````

This is controlled by option `htmltools.preserve.raw` which **rmarkdown** sets to TRUE by default in 2.6. 

With the above example doing 
````r
options(htmltools.preserve.raw = FALSE)
rmarkdown::run("test.Rmd")
````
fix the issue.

Minimal example of the change of behavior which emulate what happens 

````markdown
---
title: "Test"
output: 
  html_document:
    keep_md: true
---

```{r, echo = FALSE}
knitr::asis_output(
  htmltools::htmlPreserve("<iframe></iframe>")
)
```
````

* Using rmarkdown 2.5 

we get in the intermediate markdown file

````markdown
<!--html_preserve--><iframe></iframe><!--/html_preserve-->
````

and then in the HTML file 

````html
<iframe></iframe>
```` 

* Using rmarkdown 2.6 or later (or setting the option to TRUE)

we get in the intermediate markdown file the raw attributes syntax 

````markdown
`<iframe></iframe>`{=html}
````

and in the HTML
````markdown
<p><iframe></iframe></p>
````

This is the Pandoc's way: everything is included in a paragraph ! I should have thought of that. 

> Assuming there is no way out of getting rid of the <p> wrapper via rmarkdown/pandoc/knitr, feel free to transfer to flexdashboard and we can investigate a fix over there

@cpsievert As this is Pandoc including the `<p>` wrapping, do you think we can take that into account in **flexdashboard** ? 
Otherwise we would need to find a way to unwrap. but that could be tricky. 

Easy (Workaround ?) solution : **flexdashboard** could set `htmltools.preserve.raw = FALSE` so that the old way is used. But using Pandoc's raw attributes could be used in other situation and is the canonical way to include content to preserve with Pandoc. So I guess it is worth supporting it.

What your thoughts on this ?

**Comment by cderv** [comment]
Oh and we could also ask Pandoc is this could be unwrap. As this is to preserve some content, it feels "odd" that a `<p>` tag is added to be honest. But not sure this could be done - IDK the implication.

**Comment by cderv** [comment]
On our side (or rather **htmltools**), one solution would be to use only block raw_attributes

````markdown
```{=html}
content
```
````

as this will only be caused by online raw_attributes
````markdown
`content`{=html}
````

which becomes a single line in Markdown file, which pandoc sees as a Paragraph , and then wrap in `<p>` (which seems to be expected thinking this way) 🤔 

Currently, if the HTML to preserve is a one liner we use the latter form
https://github.com/rstudio/htmltools/blob/943217e24631d54a3fdb857e6fd819300a098659/R/tags.R#L1446-L1463

**Comment by cpsievert** [comment]
Thanks for the additional context @cderv. Since [there are various benefits](https://github.com/rstudio/rmarkdown/pull/1965#issuecomment-734804176) to using raw attributes, I'd like to avoid setting `htmltools.preserve.raw = FALSE` in flexdashboard, if we can get away with it.

Any chance you know of way to add a class to the `<p>` tag? I tried doing this, but it doesn't seem to do whatI want:

```{=html, class.output='html-preserve'}
content
```

**Comment by cderv** [comment]
To be clear,  this form won't create a p tag 
````markdown
```{=html}
content
```
````
````powershell
❯ pandoc -t html
```{=html}
<iframe src="https://example.org"></iframe>
```
^Z
<iframe src="https://example.org"></iframe>
````

Only the short inline form
````powershell
❯ pandoc -t html
`<iframe src="https://example.org"></iframe>`{=html}
^Z
<p><iframe src="https://example.org"></iframe></p>
````

and unfortunately, you can't control the class on the p tag. 

Attributes can really be set on Spans and Divs only. 

We got this problem here with iframes because what will be produced by the code chunk with `shinyApp()` is a one liner with `<iframe></iframe>`, and when `htmltools::htmlPreserve()` sees that, it will use the inline form and not the block form. 

Maybe that is where things should be adapted ?

**Comment by cpsievert** [comment]
Ahh, sorry for overlooking that! And yea, it feels like the right change here would be to avoid using the inline form at all in `htmlPreserve()`. See https://github.com/rstudio/htmltools/pull/306

**Comment by cpsievert** [comment]
@cderv feel free to close (I can't) since I'm now tracking the core issue here rstudio/htmltools#305
