### ISSUE TITLE
shiny_prerendered server contexts cannot be empty

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#2272]
Originally reported by @jcheng5 here (https://github.com/quarto-dev/quarto-cli/issues/88):

I would've expected empty Shiny server contexts to be allowed:

    ```{r}
    #| context: server
    ```

But if the server context is empty (or contains only whitespace), you get this error:

```
Error in shiny_prerendered_app(target_file, render_args = render_args) :
  No server contexts or server.R available for density-contours.qmd
```

Follow up from @cderv:

````markdown
---
title: "Hello Prerendered Shiny"
output: html_document
runtime: shinyrmd
---

```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
```

```{r, context="server"}
```
````

````r
Backtrace:
    x
 1. \-rmarkdown::run(...)
 2.   \-rmarkdown:::shiny_prerendered_app(target_file, render_args = render_args)
Erreur dans shiny_prerendered_app(target_file, render_args = render_args) : 
  No server contexts or server.R available for C:/Users/chris/Documents/test.Rmd
````

Support for empty server context should probably be added there.

**Comment by cderv** [comment]
I had a quick look into this. 

This come as deep as **knitr** in https://github.com/yihui/knitr/blob/887fc44cadea648b562c2cf7065199b603975dd5/R/block.R#L236
````r
res = if (is_blank(code)) list() else if (isFALSE(ev)) {
    as.source(code)
  } else if (cache.exists && isFALSE(options$cache.rebuild)) {
    fix_evaluate(cache$output(options$hash, 'list'), options$cache == 1)
  } else in_dir(
    input_dir(),
    evaluate(
      code, envir = env, new_device = FALSE,
      keep_warning = !isFALSE(options$warning),
      keep_message = !isFALSE(options$message),
      stop_on_error = if (is.numeric(options$error)) options$error else {
        if (options$error && options$include) 0L else 2L
      },
      output_handler = knit_handlers(options$render, options)
    )
  )
````

If the code in a chunk is empty, then `evaluate` hook won't be called. In the context of a shiny prerendered document, this means that no server context will be registered in the HTML document., even an empty one. So `shiny_prerendered_app()` throw the error because it can't find a server context among the HTML document context node as none have been added for `server` during  knitting. 

To make this work, we would need a way to trick **knitr** somehow. Or maybe just initialize an empty server if none is found 🤔 
instead of the last `stop()` if all the previous `if()` are FALSE
https://github.com/rstudio/rmarkdown/blob/880923dc33c45d34db688b7012c35fb3b9e815ae/R/shiny_prerendered.R#L60-L82

```r
server <- function(input, output) {}
```
