### ISSUE TITLE
add support for ioslides thank you and closing slide

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#230]

**Comment by acoppock** [comment]
Hi all, just checking in on this!

**Comment by yihui** [comment]
@acoppock You may consider [the xaringan package](https://github.com/yihui/xaringan) based on remark.js, which is a better maintained JS library. I think it is much more customizable than ioslides (especially in terms of CSS).

I'm closing this issue since it has been left here for too long and I don't think it will be resolved anytime soon. @kiwiroy made an attempt in #687 but the tricky thing was that the CSS classes were added to `<article>` instead of `<section>`.
