### ISSUE TITLE
[FR] Have equal spacing for nested lists

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rmarkdown#2323]
For example, this is what my `example.Rmd` document looks like:

````md
---
title: "Plan"
output: 
    html_document:
      keep_md: true
---

- Day 1: do that but this way

  * step 1
  * step 2

- Day 2: do something else
````

The HTML output for this document doesn't have equal spacing between the top-level unordered list items and the child unordered list items:

![image](https://user-images.githubusercontent.com/11330453/156374610-40a539b4-aa08-4133-9455-3103c43606d5.png)

But if I convert the generated `.md` file to HTML using `pandoc`,

```bash
pandoc example.md -o example.html
```

I get the desired output:

![image](https://user-images.githubusercontent.com/11330453/156375166-c2d0f4ba-b6e7-4e23-b023-63585900fb5c.png)

Is it possible for `rmarkdown` to support this by default?

Thanks.

**Comment by cderv** [comment]
I believe this is because it comes from a Boostrap rule for nested list 
````
ol,ul {
    padding-left: 2rem
}

ol,ul,dl {
    margin-top: 0;
    margin-bottom: 1rem;
}

ol ol,ul ul,ol ul,ul ol {
    margin-bottom: 0;
}
````

So `<ul>` have a margin at the bottom, but not the nested `<ul>`. 

Pandoc doesn't have bootstrap by default, unlike rmarkdown. 

I would tend not to overwrite Bootstrap specificically in **rmarkdown**. It has already create issue in the past with Bootstrap update and is not that easy to maintain. (even if this is a small change). 

All the more because you can easily apply some CSS to change that in your document, or deactivate bootstrap if you wish (with `theme: null` where you'll get the Pandoc like output, but loose some feature from rmarkdown obviously). 

Also, styling is always a matter of preference, and changing this would impact all outputs. As of now, I don't think we had a lot of request for this. We can leave this issue open to gather 👍 and if really this is annoying. 

But **rmarkdown** is highly customizable using CSS, SASS or even **bslib** in YAML so this is really something that any user can tweak at its convenience. 

Am I too conservative ?

**Comment by IndrajeetPatil** [comment]
Thanks a lot for the detailed explanation, Christophe! 

Given that there are no upvotes on this issue, I am assuming that this is something that only I am bothered by 😅

Nonetheless, thanks for considering the FR! And, like you said, this is possible via customization, so maybe that's the route for me to achieve this.
