### ISSUE TITLE
Identical base R plots in the same chunk only show up once

### ISSUE THREAD

**Issue by jtr13** [rstudio/rmarkdown#2367]
(Note: this is not something I care gets fixed, reporting in the spirit of if you see something say something.)

Reproducible example:

Change the second chunk in the `.Rmd` template to:

```{r pressure, echo=FALSE}
plot(pressure)
plot(pressure)
```

Only one shows up.  This doesn't happen with **ggplot2**.

Using `rmarkdown_2.14`

**Comment by cderv** [comment]
Thanks for the report. 

I believe this is a expected behavior that exists since the beginning of **knitr**, or a least since `fig.keep = "high"` is the default. Normally, this `fig.keep` option is for keeping low level plots or not, and two identical plots are considered as low level + high level. This is by design as mentioned in https://github.com/yihui/knitr/issues/612#issuecomment-25201356

Setting `fig.keep = "all"` for example will produce the two plots. 

> This doesn't happen with ggplot2.

**ggplot2** are not handled the same way as base plot by **knitr** I guess. 

@yihui can you confirm this is still intended behavior for base plot ? 

> (Note: this is not something I care gets fixed, reporting in the spirit of if you see something say something.)

Thank you for this ! Very much appreciated!

**Comment by jtr13** [comment]
Thanks, good to know, really interesting! 

My use case was to show a plot with and without additions, such as:

```
df <- data.frame(x = rnorm(10), y = rnorm(10))
plot(df$x, df$y)
plot(df$x, df$y)
polygon(df[1:3,])
```

Easy workarounds are to make a very minor change to one of the plots or -- as I just discovered -- use `mfrow()`:

```
par(mfrow = c(1, 2))
df <- data.frame(x = rnorm(10), y = rnorm(10))
plot(df$x, df$y)
plot(df$x, df$y)
polygon(df[1:3,])
```
![image](https://user-images.githubusercontent.com/14161912/171208710-7a620d32-9839-4291-944e-8e510780a6fa.png)

**Comment by cderv** [comment]
I think you are looking for `fig.keep` options https://bookdown.org/yihui/rmarkdown-cookbook/low-plots.html

For example, using `"all"` would plot the first layer without the addition, and then the last plot with the addition. 
````markdown
```{r, fig.keep = "all"}
df <- data.frame(x = rnorm(10), y = rnorm(10))
plot(df$x, df$y)
polygon(df[1:3,])
```
````
![image](https://user-images.githubusercontent.com/6791940/171219140-4888ac58-1257-4ba2-bb26-f7b3815eee23.png)

And playing with other options you can get both on same line 
````markdown
```{r, fig.keep = "all", out.width="50%", fig.show = "hold"}
df <- data.frame(x = rnorm(10), y = rnorm(10))
plot(df$x, df$y)
polygon(df[1:3,])
```
````
![image](https://user-images.githubusercontent.com/6791940/171219373-28f1bb9d-5b62-4254-b31d-4303de964a22.png)

**Comment by jtr13** [comment]
Oh, that's great. Thanks a lot!!
