### ISSUE TITLE
Inline code is not highlighting when using "darkly" theme

### ISSUE THREAD

**Issue by sir-farts-alot** [rstudio/rmarkdown#2390]
I hope the issue is clear enough. 
Please suggest a solution. Thanks.

**Comment by cderv** [comment]
Unfortunately, this is not supported by Pandoc which is in charge of the highlighting: https://github.com/jgm/pandoc/issues/7560 and https://github.com/jgm/skylighting/issues/122

You can do that or now by applying a custom CSS style derived from you dark theme. (using `css` chunk or passing style in `css` argument. For PDF, you would need to pass a custom preamble I guess. I don't know how to customize this for LaTeX TBH.  

We could try to bring better support for HTML at least in **rmarkdown** directly by getting the background information of the Pandoc style used and add a CSS style based on it.

**Comment by cderv** [comment]
This is a great exercise to learn about CSS ! Use the inspector in your browser to find the inline code element and its applied style. 
Some resources to learn CSS: 
 * https://web.dev/learn/css/
 * Specific to R Markdown: https://emilyriederer.netlify.app/post/rmarkdown-css-tips/
 
 You would need to 
* Inspect your dark code block to find the color applied
* Inspect the inline code block to get the correct selector to apply the same style as in code block. 

I let you with the exercice and come back later this week if you can't manage to made it work. Please share back what you tried in the meantime (Also doing it because you did not share a reproducible example of what you are doing and I don't have the time right now to create one, trying to guess your specific usage - if you share back more info, it will be easier to help)

**Comment by sir-farts-alot** [comment]
@cderv 
Tbh, learning CSS just to fix one issue seems like too much to me. I'm not a developer or have anything to do in this field. 
But rmardown is so easy that the site turned out to be great with even learning HTML
Though there is a lack of themes for dark mode still one is good enough. 

Below is my issue.
[test.zip](https://github.com/rstudio/rmarkdown/files/9143284/test.zip)

![image](https://user-images.githubusercontent.com/104090079/179810001-ce63c2ad-63d2-4588-9f0a-fc4ae370d02f.png)

Please look into this if it's not too much work. Thanks.

**Comment by cderv** [comment]
> Tbh, learning CSS just to fix one issue seems like too much to me. I'm not a developer or have anything to do in this field.
But rmardown is so easy that the site turned out to be great without even learning HTML

yes I agree. And this is the case if you stay within supported feature and default behavior. If you want to customize or add specific support, you will need to add a bit of CSS / JS for HTML output, and LaTeX for PDF. 

Honestly, this is really useful skills if you produce HTML document to understand and now how to tweak a CSS theme. 

Example with `zenburn` style looking in HTML how is the color of this style and appplying to inline code 

 ````markdown
---
output: 
  html_document:
    highlight: zenburn
---

```{css, echo = FALSE}
p > code {
  background-color: rgb(48, 48, 48);
  color: rgb(204, 204, 204);
}
```

Hi!

Below is a inline code which is not highlighting with "darkly" theme.

`blah blah`

See, that blah blah supposed to be higlighted, but it isn't. 
It works fine in all other themes but issue is only with "darkly"

```{r}
1 + 1
```

````

hope it helps

**Comment by sir-farts-alot** [comment]
Thanks, sir 👍 worked.
