### ISSUE TITLE
Rmarkdown issue

### ISSUE THREAD

**Issue by abhayguptaastellas** [rstudio/rmarkdown#2400]
When users trying to launch R Markdown file from(File --> New File --> R Markdown option) they are getting the error(please see screenshots). Can you please check what could be the issue.
![inlineImage](https://user-images.githubusercontent.com/111520548/185430680-df19acf1-70fb-4369-bc10-513333055bb0.jpeg)
![inlineImage (1)](https://user-images.githubusercontent.com/111520548/185430861-bb814e58-8315-4124-9c88-613e4bfd10b6.jpeg)

Thanks,
Abhay Gupta

**Comment by yihui** [comment]
Have you installed **rmarkdown**?

```r
install.packages('rmarkdown')
```

**Comment by abhayguptaastellas** [comment]
Yes, we have installed markdown. The error we are getting is :

[https://mango-solutions.zendesk.com/attachments/token/nfEXS0O45hseegk8ExfqhWSkT/?name=inlineImage.jpeg]

[https://mango-solutions.zendesk.com/attachments/token/M2BcOIjHCpapIS37fojMcUF9b/?name=inlineImage.jpeg]

Kind Regards,

Abhay Gupta
Tata Consultancy Services – Support Analyst
Application Management Services for Astellas
Tel: +91-9144006232
Email: ***@***.******@***.***>,
***@***.******@***.***>

**Comment by yihui** [comment]
This is most likely to be an RStudio IDE issue, but you have provided too little information and we can't really help much (please follow the issue guide when filing new issues). If your RStudio version is not the latest, please consider upgrading. If it is, please make sure you have set a CRAN repository: Tools -> Global Options -> Packages -> CRAN repository. Thanks!

**Comment by abhayguptaastellas** [comment]
Can you please let me know what else information will you need?

**Comment by cderv** [comment]
This is in the issue guide when you open an issue. See https://github.com/rstudio/rmarkdown/blob/main/.github/ISSUE_TEMPLATE/bug-report.md

Are you using old version of the tools ? 
Message in your screenshot is saying rmarkdown 2.10, which is quite old. CRAN version 2.15 now: https://cran.r-project.org/web/packages/rmarkdown/index.html

So it may be why it sees that at unavailable. I don't know why 2.10 would be required, unless maybe you have a very old RStudio version 🤔 

So as you see we can only guess when you only share screenshot. It is not a **rmarkdown** issue but something related to the IDE or maybe related to your environment setup somehow. That is why it is closed here, this is not the best place for such question. 

I can try to keep helping if you provide more information, otherwise you should ask on other forums, or some contact at mango-solutions maybe.
