### ISSUE TITLE
How can I give a dataframe to params?

### ISSUE THREAD

**Issue by qqwxp** [rstudio/rmarkdown#2436]
It seems that only string, numeric, and logical value can be passed to params in rmarkdown file.

However, sometimes I want to pass a dataframe or .rdata, which is preprocessed in the previously. I know one practice is to export the object to a file, then give the file path to the rmarkdown params. But when the object is large (i.e. omics data), and exploratory analyses performed for many times with many processed objects, this practice results in much disk space occupied. 

Is there any trick to give the processed object (i.e. dataframe, .rdata, rds) to the rmarkdown?

**Comment by cderv** [comment]
> It seems that only string, numeric, and logical value can be passed to params in rmarkdown file.
> However, sometimes I want to pass a dataframe

I believe this is a limitation due to how parameters are / needs to be declared in YAML. https://bookdown.org/yihui/rmarkdown/params-declare.html
YAML structure is not aware of a R data.frame object so you indeed can't pass a data.frame as a default value. You can pass string though. 

To clarify, let's look at this example 
````markdown
---
title: "Test"
output: html_document
params: 
  df: dummy
---

```{r}
head(params$df)
```
````

I used `dummy` in the declaration because currently a default value need to be passed, and we can pass a data.frame. 
However, I can pass a data.frame as parameters 

````r
rmarkdown::render("test.Rmd", params = list(df = mtcars))
````

However, rendering without explicit `params` in `render()` call will not get us the expected results, unless we handle a default value better. For example 

````markdown
---
title: "Test"
output: html_document
params: 
  df: mtcars
---

```{r}
df <- params$df
if (!is.data.frame(df) & is.character(df)) df <- get(df)
head(df)
```
````

where default rendering would be with `mtcars` and you could change when calling render 
````r
rmarkdown::render("test.Rmd", params = list(df = cars))
````

**This above all works because `rmarkdown::render()` is coded in R and calling directly knitr - there is no transformation to any other format like YAML in the process when `params` argument is used. 

> or .rdata, which is preprocessed in the previously

Passing `.rdata` file seems possible to me in parameters as this would be a string, and you can then load it inside the R Markdown document using R function. 

> I know one practice is to export the object to a file, then give the file path to the rmarkdown params. But when the object is large (i.e. omics data), and exploratory analyses performed for many times with many processed objects, this practice results in much disk space occupied.

This is usually a good practice to pass object through an intermediate, especially when running multiple render for example. If it is not disk space used, it would be memory, so usually the preferred method depends of what you have available. 

When using disk, you could try find the best format for speed when writing and reading or accessing information. This could be a full write and full read using file format (text like .csv or binary like .rds), or some optimized format for data.frame for example (look at **arrow** 📦 https://arrow.apache.org/docs/r/#reading-and-writing-data-files-with-arrow). 
It could also be a case of using data base by writing result in local data.base, and then connecting and reading to it later when needed instead of loading the full dataset. 

There is not one best solution, only a good solution adapted to the use case. 

> Is there any trick to give the processed object (i.e. dataframe, .rdata, rds) to the rmarkdown?

Otherwise, I can think of one trick that could be a dangerous one when not understood properly. `rmarkdown::render()` will execute in the current R session by default. This means that if you have a data.frame loaded, it can be accessed within the rendering. Obviously using that, you'll use interactive rendering by the Knit button, and you would need to use a custom script. 

Example 

* `test.Rmd`

````markdown
---
title: "Test"
output: html_document
---

```{r}
head(df)
```
````

* `render.R`

```r
df <- mtcars
rmarkdown::render("test.Rmd")
```

There is not much difference in this small example from using `params` argument in `render()`, but it could be useful in more complex project to use such render script. 

Anyway, as I said, it can be dangerous as the `.Rmd` is not more self contained, and the render script is part of the project so that all the object are loaded. 

Best practice for reproducibility remains to load every data inside some chunks of the document, even using external script. 

Hope it helps understand how this currently works. 

@yihui I am leaving this opens to think about this limitation of parameter declaration for the data.frame case than in fact works using `render()`

**Comment by qqwxp** [comment]
@cderv Thanks a lot!

**Comment by yihui** [comment]
@qqwxp Does the above reply answer your question? If you have a preprocessed in-memory data frame, I'd render the Rmd document with this as @cderv mentioned above:

```r
rmarkdown::render("test.Rmd", params = list(df = mtcars))
```

If the preprocessed data has been saved to a file, you can simply define the file path in `params` (which is a string and a value type supported by YAML) and read the file in Rmd.

> @yihui I am leaving this opens to think about this limitation of parameter declaration for the data.frame case than in fact works using `render()`

@cderv I don't think we can do anything here since YAML doesn't support arbitrary data types. For greater flexibility, users have to resort to the `!expr` trick, e.g.,

```r
params:
  df: !expr mtcars
```

**Comment by cderv** [comment]
Oh if the `!expr` tricks works in the definition, then I guess it solves the issue. It is just not documented explicitly. 

So yes this would be how to do that 
````markdown
---
title: "Test"
output: html_document
params: 
  df: !expr mtcars
---

```{r}
head(params$df)
```
````

and then `rmarkdown::render("test.Rmd", params = list(df = cars))` to change value from the default. 

Thank @yihui!
