### ISSUE TITLE
Style "tango" used with YAML header argument "highlight" got changed or is broken

### ISSUE THREAD

**Issue by danbraswell** [rstudio/rmarkdown#2444]
Something changed the distinctive "tango" style sometime between August 2020 and June 2021, making it much less attractive.

I describe the issue in detail at the Kaggle link below. I include there screenshots showing the problem. I know you don't like screenshots, but they are appropriate for this issue. In the comments, user @headsortails delves into the matter and states where he thinks the problem is.

Link:
https://www.kaggle.com/discussions/questions-and-answers/378497

The issue occurs for me locally using both the latest stable release of Rstudio  and the latest daily update. It also appears when running an R Markdown file at Kaggle.

**Comment by cderv** [comment]
Thanks for the issue. 

As explained in the kaggle thread, `tango` style and the syntax highlighting system comes from Pandoc itself. 

From some test, the change happens in Pandoc 2.11. If you render the document with a Pandoc before 2.11 you'll get the initial highlighting, and after Pandoc 2.11 you'll get a new one. This is because internally the syntax highlighter and/or theme as changed. 

This can be customized by extracting the data from source code or from Pandoc command line and passing it to Pandoc command line. See https://pandoc.org/MANUAL.html#syntax-highlighting

See also my answer on the community regarding this https://community.rstudio.com/t/was-pygments-highlight-style-in-html-output-changed-in-rstudio-1-4/89925/2?u=cderv for this same question. 

We won't do much in **rmarkdown** directly except allowing a user to customize all this for a format, and this should already be possible now using `highlight` and `pandoc_args` in YAML, so I'll close this. 

Thanks for the question ! That will be useful to anyone wondering the same as you.
