### ISSUE TITLE
Markdown chunk runs in standalone .Rmd file, but errors when included with other markdown chunks in .Rmd file 

### ISSUE THREAD

**Issue by AnyPersonCanDo** [rstudio/rmarkdown#2449]
I have a .Rmd file that is set up to knit to a .pdf file.  This .Rmd file only includes 2 R code chunks - a {r setup} code chunk and a {r mccv egression} code chunk.  When the .Rmd file is run and rendered to a PDF file using the knit button, it outputs a PDF file as expected.

Conversely, if the {r mccvregression} code chunk **is copied to another .Rmd file** and pasted into the file, it creates an error every time.  If I remove the line(s) that caused the error message, it will throw an error again.  

For example:
1st error...
Quitting from lines 278-352 (HW1RMC.Rmd) 
Error in `colnames<-`(`*tmp*`, value = c("MCCV Regresson Training Error",  : 
  attempt to set 'colnames' on an object with less than two dimensions
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> colnames<-
Execution halted

When I remove or comment out the offending line, a different error appears.
2nd error....
Quitting from lines 278-352 (HW1RMC.Rmd) 
Error in seq.default(1, table_info$nrow - table_info$position_offset,  : 
  wrong sign in 'by' argument
Calls: <Anonymous> ... pdfTable_styling -> styling_latex_striped -> seq -> seq.default
Execution halted

This will continue endlessly.  To resolve this, I have:

- updated R-Studio
- updated R language
- updated Miktex
- checked the YAML in both .Rmd files to ensure the settings are similar
- check the {r knitrSetup} code chunk to ensure they are the same
- removed header-includes to identify if a latex package was interfering ({booktabs}, {xcolor},{colortbl}
- retyped the code chunk settings to ensure nothing was added during the copy/paste
- set the code chunk settings to the most basic {r mccvregression} to ensure this was not causing the issue
- removed all comments from the code chunk, then got a different error message:

Quitting from lines 278-339 (HW1RMC.Rmd) 
Error in seq.default(1, table_info$nrow - table_info$position_offset,  : 
  wrong sign in 'by' argument
Calls: <Anonymous> ... pdfTable_styling -> styling_latex_striped -> seq -> seq.default
Execution halted

- removed all whitespace in the code chunk, same error as line above
- tried rmarkdown::render("HW1RMC.Rmd")  and got this error message:

processing file: HW1RMC.Rmd                                                                                                                                                    
output file: HW1RMC.knit.md
Error: Functions that produce HTML output found in document targeting latex output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:
  always_allow_html: true
Note however that the HTML output will not be visible in non-HTML formats.

- Added _always_allow_html: true_ to YAML, received this error message:

Quitting from lines 279-319 (HW1RMC.Rmd) 
Error in seq.default(1, table_info$nrow - table_info$position_offset,  : 
  wrong sign in 'by' argument
Calls: <Anonymous> ... pdfTable_styling -> styling_latex_striped -> seq -> seq.default
Execution halted

- tried rmarkdown::render("HW1RMC.Rmd") again, and got this error message:

Error: LaTeX failed to compile HW1RMC.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
In addition: Warning message:
In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"pdflatex"' not found

Note that the code chunk **runs without any errors when in a standalong .Rmd file (and knitted) and when the Run Current Chunk green triangle button is used.**

Any suggestions on other approaches to correct this.

I'd like to get all code chunks into a single .Rmd file to separate code outputs and code chunks for properly formatted reports.

**Comment by cderv** [comment]
Those errors are mainly R errors from the packages and functions you are using. 

> Error: Functions that produce HTML output found in document targeting latex output.

This means that somewhere in your code you are producing HTML table (or rather a function you are using does), but you are targetting a PDF output so that won't work. You need to check for this. 

> In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
'"pdflatex"' not found

Do you have the necessary tools to render to PDF ? e.g TeX Live ? if not see https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html

> I'd like to get all code chunks into a single .Rmd file to separate code outputs and code chunks for properly formatted reports.

Sharing your document would have been easier so that we know exactly which code you are running. I feeld this is not an issue with the **rmarkdown** itself, and you may just need help find out how to do what you are looking for. 

The Community (https://community.rstudio.com/) is a great place for that.

**Comment by AnyPersonCanDo** [comment]
Hi Cderv,

Thanks for the suggestions.  

I have Miktex installed (https://miktex.org/) and it produces .pdf output files.  However, I also installed Tex Live as you suggested from the link above and am still seeing the same error behavior.

Note that the code chunk that is causing the error **runs perfectly fine with no errors if it is the only chunk in the .Rmd file.** When the **exact same code chunk is included in a different .Rmd  file along with other code chunks, it always stops and throw an error.**

Thus, we should be able to ascertain that the code chuck is correct - e.g it runs with no errors.  No R error messages, no latex error messages, no knitr error messages, and it ouputs a .pdf file.  However, it must be the **only code chunk in the .Rmd file**. 

When the code chunk is one of several code chunks in a .Rmd file, it errors every time.  

It appears there is some interaction between the error causing code chunk that **only occurs when it is included in a .Rmd file with several other code chunks.**   Oddly, the problematic code chunk also executes properly without errors when code chunk is simply "run" (vs kniting the whole .Rmd file.)

- FileA.Rmd with code chunk1 = runs with no errors, knits with no errors, produces .pdf output
- FileB.Rmd with code chunk2, code chunk3, code chunk4 and code chunk5 = runs with no errors, knits with no errors, produces .pdf output
- Now, copy code chunk 1 into FileB.Rmd... so that FileB includes code chunks 1 through 5 = errors every time

Unfortunately I cannot share the code in any public forum.

**Comment by cderv** [comment]
> I have Miktex installed ([miktex.org](https://miktex.org/)) and it produces .pdf output files. However, I also installed Tex Live as you suggested from the link above and am still seeing the same error behavior.

You should check your installation, because `'"pdflatex"' not found` means that the command is not found by R run convert LaTeX file to PDF. 

> Regarding the HTML error, I have included always_allow_html: true in the .Rmd YAML header. This StackOverflow thread ([stackoverflow.com/questions/42543206/r-markdown-compile-error](https://stackoverflow.com/questions/42543206/r-markdown-compile-error)) suggests to me that the HTML will be ignored when rendered to pdf file format. Perhaps I'm misunderstanding?

It is better to not include at all some HTML in TeX file as this won't be understood by LaTeX. `always_allow_html: true` is a trick where in some specific case it could be needed. But most of the time (almost always), don't include raw HTML code for PDF document convertion, this will create issue. Use some conditional to mix content based on output format: https://bookdown.org/yihui/rmarkdown-cookbook/latex-html.html

> Note that the code chunk that is causing the error runs perfectly fine with no errors if it is the only chunk in the .Rmd file. When the exact same code chunk is included in a different .Rmd file along with other code chunks, it always stops and throw an error.

Without knowing the code chunk content, it will be hard to understand what is going. It is possible that some tools impact the way another piece of code behave (e.g prints during knitting).

> Oddly, the problematic code chunk also executes properly without errors when code chunk is simply "run" (vs kniting the whole .Rmd file.)

When the code chunk is run in IDE, there is no knitting happening, and no convertion to LaTeX and PDF. Only evaluating the code for preview in IDE. If the error is not in the R code, but in the way it should be output in TeX document, then issue will happen only during knitting.

> FileA.Rmd with code chunk1 = runs with no errors, knits with no errors, produces .pdf output
> FileB.Rmd with code chunk2, code chunk3, code chunk4 and code chunk5 = runs with no errors, knits with no errors, produces .pdf output
> Now, copy code chunk 1 into FileB.Rmd... so that FileB includes code chunks 1 through 5 = errors every time
> Unfortunately I cannot share the code in any public forum. Any other suggestions on what else I might troubleshoot?

Without knowing what you do in chunk1, or chunk2 or chunk3 etc... I can't help anymore. 

I still don't think this is an issue with the R package for which this issue board is from. I think you have some interaction in some tools. 

Anyway, without sharing the code, it will be hard for us (or anyone else to help) further. You can either: 

* Try to isolate the issue by creating a reproducible example you can share 
   *  Reduce your data, 
   * Use the same package and functions but on dummy data
   * Try to understand what is happening. 
* Debug further the issue 
   * Add `keep_md: true` in the YAML header to see what is in the Markdown file that will be passed to Pandoc; You may find some problem.
   * Add `keep_tex: true` in the YAML header to see the `.tex` file and try to see what is causing a pdf convertion issue. 

* Otherwise, you can share with a private repo, or send me some content to my email. I could have a look when I find time.

**Comment by AnyPersonCanDo** [comment]
Cderv,

After reading through your additional feedback yesterday, and believing the root of the problem is the interaction of one or more packages; I started with a clean .rmd file, added each code chuck one-at-a-time.

Several of my code chunks were using a small package named magicfor (https://cran.r-project.org/web/packages/magicfor/vignettes/magicfor.html) to obtain results of intermediate values in R for loops.   The errors never occurred prior to a code chunk using magicfor.  

What I found was that if I replaced magicfor() and magic_result_as_dataframe() with dataframes to accumulate intermediate results in my loops, the errors would move to the prior code chunk.  When all instances of magic() and magic_result_as_dataframe() were removed from all code chucks, the code ran without errors.

I had used magicfor() in several consecutive code chucks so perhaps this was contributing to the issue, however, I thought that each code chuck ran within its own R environment when knitted and output via latex.  Therefore each instance of magicfor() would be isolated, but perhaps that is not true.  Because magicfor() seems to modify the structure of for-loops, perhaps some bug is being introduced. 

After resolving the issue, I checked the bug reports for magicfor() and several stack overflow posts (https://stackoverflow.com/questions/69678104/error-in-for-loops-could-not-find-function-check-reserved) about the package, and it seems that there may be some issues with how magicfor() modifies R for-loops that is causing issues for others, too.



**Thank you for responding so quickly and providing relevant suggestions** - it is very much appreciated, and I would not have found a solution without your input.

**Comment by cderv** [comment]
Thanks for your feedback ! 

It seems your issue is resolved so I'll close. Happy to have been of help. If you reach out to **magicfor** maintainers and find out that some work need to be done for  better compatibility, please do not hesitate to reopen an issue.
