### ISSUE TITLE
output must be first in _output.yaml ?

### ISSUE THREAD

**Issue by presnell** [rstudio/rmarkdown#2461]
With the attached `mydoc.Rmd` and `_output.yaml` files, running
```r
rmarkdown::render("mydoc.Rmd")
```
fails with the error
```
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:6: unexpected symbol
1: Jane Doe
         ^
```
If I edit `_output.yaml` and move the line `output: html_document` to the top, then the render command works as expected.
Otherwise, I have to call `rmarkdown::render()` with the `output_format` specified, e.g.,
```r
rmarkdown::render("mydoc.Rmd", output_format = "html_document")
```

I am reporting this as a bug because I don't recall seeing anywhere that the output field had to be given first in _output.yaml, so I assume that this is not the intended behavior.

```
> xfun::session_info("rmarkdown")
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_US.UTF-8        LC_COLLATE=C              
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  R6_2.5.1          base64enc_0.1.3   bslib_0.4.2       cachem_1.0.7     
  cli_3.6.0         digest_0.6.31     ellipsis_0.3.2    evaluate_0.20    
  fastmap_1.1.1     fontawesome_0.5.0 fs_1.6.1          glue_1.6.2       
  grDevices_4.2.2   graphics_4.2.2    highr_0.10        htmltools_0.5.4  
  jquerylib_0.1.4   jsonlite_1.8.4    knitr_1.42        lifecycle_1.0.3  
  magrittr_2.0.3    memoise_2.0.1     methods_4.2.2     mime_0.12        
  rappdirs_0.3.3    rlang_1.0.6       rmarkdown_2.20.1  sass_0.4.5       
  stats_4.2.2       stringi_1.7.12    stringr_1.5.0     tinytex_0.44     
  tools_4.2.2       utils_4.2.2       vctrs_0.5.2       xfun_0.37        
  yaml_2.3.7       

Pandoc version: 3.1.1
```
[rmd-output-yaml-issue.zip](https://github.com/rstudio/rmarkdown/files/10913411/rmd-output-yaml-issue.zip)

**Comment by cderv** [comment]
Your `_output.yaml` looks like this 

````yaml
author: "Jane Doe"
output: html_document
````

It won't work - not because of order but because this file can contain only output formats information. 

This is explained in this part of the doc  https://bookdown.org/yihui/rmarkdown/html-document.html#shared-options
and an example for book projects is shown in https://bookdown.org/yihui/rmarkdown/bookdown-project.html#output.yml

This file is used only to set output format information for a project or to be reuse in `render()` (https://pkgs.rstudio.com/rmarkdown/reference/render.html) 

We can surely add better check for a more useful error message. 

Hope it helps understand the issue here

**Comment by presnell** [comment]
Yikes!  Sorry for the trouble.  I'm not sure how I got so far down the wrong track --- the file name `_output.yaml` should have been a hint.
