### ISSUE TITLE
With render(), message=FALSE does not print to console as expected

### ISSUE THREAD

**Issue by bbimber** [rstudio/rmarkdown#2547]
Hello - I am trying to render() a markdown and to have it print message() to the console, rather than the markdown itself. According to the docs, I think this should log the message() to the console; however, when message=FALSE, the line is not logged anywhere I can see. When message=TRUE, it is logged to the HTML output as expected. Below is a simple example markdown:

````

---
title: Test
---

```{r setup}
knitr::opts_chunk$set(cache=FALSE, message=FALSE, warning=FALSE, error=FALSE)
 ``` 

Expected behavior: print to console. Actual: doesnt print anywhere.

```{r}

message('I am a message')
warning('I am a warning')

```

Same as above, expect explicitly set in the chunk. Also does not seem to print anywhere.

```{r message=FALSE, warning=FALSE}

message('I am a message')
warning('I am a warning')

```

Expected behavior: print to markdown HTML output. Actual: does this.

```{r message=TRUE, warning=TRUE}

message('I am another message')
warning('I am another warning')

```
````

When I run the above, using:

```
Rscript -e "rmarkdown::render('test.rmd')"
```

The messages are not logged to the console.  I am using: R version 4.3.2 and rmarkdown 2.26. 

Is there some setting I am missing? Thanks in advance for any help.

**Comment by atusy** [comment]
Hi. This sounds like [knitr](https://github.com/yihui/knitr)'s issue.

Anyway, it sounds good to me to logging on the console or somewhere.
In this way, users can stop knitting once they find some unexpected messages or warnings.

On the other hand, I would keep the current behavior of the chunk options (`message`, `warning` and `error`) for the simplicity.
An alternative approach would be to provide package options for logging, e.g., `knitr::opts_knit(loglevel = "warning", logfile = "stderr")`.

> According to the docs

Would you provide a link to the doc that describes your expected behavior?
I briefly read through https://yihui.org/knitr/options/ , but cannot find it.

**Comment by bbimber** [comment]
@yihui Thank you, your first post fits. I was sure the behavior used to be that message=FALSE would print them, but I could not find the docs on it. message=NA does behave as you posted. Nonetheless, I think explicitly logging is probably a more clear route and I think we'll use this. 

It would be great if you could update the docs since it took a while to figure out the expected behavior.

**Comment by yihui** [comment]
I'll update the docs for sure. Sorry about the confusion!
