### ISSUE TITLE
Adding `"paged_df"` to a `data.frame` class stops the data frame from printing to console when `{rmarkdown}` is loaded

### ISSUE THREAD

**Issue by markfairbanks** [rstudio/rmarkdown#2562]
Adding `"paged_df"` to a `data.frame` subclass stops the data frame from printing to console when `{rmarkdown}` is loaded.

This issue occurs when using `library(rmarkdown)` but also prevents things from working with the `{reprex}` package.

This is a new issue, not sure what changed. I found out about it due to this issue [here](https://github.com/markfairbanks/tidytable/issues/810). I add `"paged_df"` as a subclass of a `tidytable` found in the print method [here](https://github.com/markfairbanks/tidytable/blob/main/R/print.R) so paged printing would work in Rmarkdown. Not sure if there is a better/recommended way to allow paged printing of a data frame subclass like a tidytable?

There's not output here when using `reprex::reprex()`

``` r
library(tidytable)

tidytable(x = 1:3, y = 1:3)
```

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

``` r
xfun::session_info('rmarkdown')
#> R version 4.3.1 (2023-06-16)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Sonoma 14.5
#> 
#> Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
#> 
#> Package version:
#>   base64enc_0.1.3   bslib_0.7.0       cachem_1.1.0      cli_3.6.3        
#>   digest_0.6.36     evaluate_0.24.0   fastmap_1.2.0     fontawesome_0.5.2
#>   fs_1.6.4          glue_1.7.0.9000   graphics_4.3.1    grDevices_4.3.1  
#>   highr_0.11        htmltools_0.5.8.1 jquerylib_0.1.4   jsonlite_1.8.8   
#>   knitr_1.47        lifecycle_1.0.4   memoise_2.0.1     methods_4.3.1    
#>   mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.4      
#>   rmarkdown_2.27    sass_0.4.9        stats_4.3.1       tinytex_0.51     
#>   tools_4.3.1       utils_4.3.1       xfun_0.45         yaml_2.3.8       
#> 
#> Pandoc version: 3.1.1
```

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

-->

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

**Comment by cderv** [comment]
> This is a new issue, not sure what changed.

Do you remember when it was working ? Which version of the tools ? 

This is really puzzling to me it was working before... 

Let's discuss why this is happening. 

I believe you get the issue because your print method is returning `invisible(x)` and so it is not catch by knitr / evaluate output. 

The printing does correctly happens, meaning `print.page_df` for rmarkdown is called, but not used by evaluation. 

This all happens in **evaluate** handlers 
https://github.com/yihui/knitr/blob/4a02625e0dce1b88f1c90396790e1eb40401a779/R/utils.R#L863-L881

So using `invisible()` but also calling print within another print() as you currently do `print.tidytable` will mess this up I believe. 
If you remove `invisible(x)` in `print.tidytable()` this works too. 

````diff
diff --git a/R/print.R b/R/print.R
index d6a3d201..3959cb95 100644
--- a/R/print.R
+++ b/R/print.R
@@ -3,7 +3,6 @@
 print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
   y <- set_class(x, print_class("tidytable_print"))
   print(y, ..., n = n, width = width, n_extra = n_extra)
-  invisible(x)
 }

 #' @export
````

I did a few tests, and this is happening at the **evaluate** level too
````r
> str(evaluate::evaluate(input = "library(rmarkdown)\nlibrary(tidytable)\ntidytable(x = 1:3, y = 1:3)"))
List of 3
 $ :List of 1
  ..$ src: chr "library(rmarkdown)\n"
  ..- attr(*, "class")= chr "source"
 $ :List of 1
  ..$ src: chr "library(tidytable)\n"
  ..- attr(*, "class")= chr "source"
 $ :List of 1
  ..$ src: chr "tidytable(x = 1:3, y = 1:3)"
  ..- attr(*, "class")= chr "source"
````

See how there is no result captured when rmarkdown is making the print method available

We have one results showing when no rmarkdown is loaded, 
```r
> str(evaluate::evaluate(input = "suppressPackageStartupMessages(library(tidytable))\ntidytable(x = 1:3, y = 1:3)"))
List of 3
 $ :List of 1
  ..$ src: chr "suppressPackageStartupMessages(library(tidytable))\n"
  ..- attr(*, "class")= chr "source"
 $ :List of 1
  ..$ src: chr "tidytable(x = 1:3, y = 1:3)"
  ..- attr(*, "class")= chr "source"
 $ : chr "# A tidytable: 3 × 2\n      x     y\n  <int> <int>\n1     1     1\n2     2     2\n3     3     3\n"
```

So maybe this is specific to how `print.paged_df` is working - it is supposed to in evaluation results to be sewed using `sew.knit_asis` method. 🤔 

I am still wondering about this nested print() of object, and how evaluate works. 

@yihui you know all this better than me - do you confirm this what is happening when the method defined is 
````r
print.tidytable <- function(x, ..., n = NULL, width = NULL, n_extra = NULL) {
  y <- set_class(x, print_class("tidytable_print"))
  print(y, ..., n = n, width = width, n_extra = n_extra)
  invisible(x)
}
````
and that this is how it work ? Or is there an issue somewhere. 

I am surprised this was working before as mentioned .... 🤔 

@markfairbanks regarding printing in knitr context, you can have custom `knit_print()` method too. 
You can read more on `knit_print()` method at https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html

>  Not sure if there is a better/recommended way to allow paged printing of a data frame subclass like a tidytable?

`rmarkdown::paged_table()` is an exported function which is the one handling options and class for `paged_df`. Usually this can be used to build a pagetable from a dataframe. 

Though adding the class is working ok.

**Comment by markfairbanks** [comment]
> Do you remember when it was working ? Which version of the tools ?

I'm not sure unfortunately. It's been working fine for a few years but broke semi-recently.

> You can read more on knit_print() method at

> `rmarkdown::paged_table()` is an exported function which is the one handling options and class for paged_df. Usually this can be used to build a pagetable from a dataframe. Though adding the class is working ok.

I've tried all sorts of things but nothing I do seems to allow me to define the `tidytable`/`data.table` subclass that prints a paged table when `paged.print = TRUE`. I could permanently attach `"paged_df"` as a subclass and it will work (which is currently what I'm leaning towards), but that also seems like the wrong solution.

Is there a simple way to define "if `paged.print = TRUE` use paged printing, otherwise use normal print"?

Feel free to close this issue by the way as maybe this is more of a Stack Overflow type question - but if you happen to know what I need to do that'd be great.

**Comment by cderv** [comment]
I'll think about this. To understand full context, out of curiosity, why return `invisible(x)` in your print method ?

**Comment by markfairbanks** [comment]
I can't remember to be honest 😅. I think a contributor recommended it and it was part of the hack to get paged printing to work, but it's possible it was unnecessary to add.

**Comment by markfairbanks** [comment]
So I reset the printing to get back to basics. Essentially I have a data frame which uses printing from `pillar` (like `tibble` does). I do not define a `print.tidytable()` method anymore. Printing now works properly in console and `reprex::reprex()` works.

But now paged printing doesn't work.

``` r
library(tidytable)

df <- tidytable(x = 1:3, y = c("a", "a", "b"))

df
#> # A tidytable: 3 × 2
#>       x y    
#>   <int> <chr>
#> 1     1 a    
#> 2     2 a    
#> 3     3 b

class(df)
#> [1] "tidytable"  "tbl"        "data.table" "data.frame"
```

**Comment by yihui** [comment]
I'm not sure if I understand correctly, but it seems that you want to enforce paged printing for `tidytable`s in R Markdown (and only in R Markdown). Does that mean you want to ignore user's [`df_print` setting](https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing)? e.g., if they want to print via `kable`, but still get a paged table. That doesn't sound right to me.

To solve your original problem, you can probably check if the code is running inside R Markdown, e.g., check if `knitr::opts_knit$get('rmarkdown.df_print')` is `NULL` (TRUE in console, and FALSE in R Markdown). However, since `reprex::reprex()` calls `rmarkdown::render()`, you won't be able to tell if the code chunk is from a normal R Markdown document or a reprex (you could check if the reprex package is loaded, but that sounds like a hack).

Personally I suggest that you leave this choice to users. If they like paged tables, they can easily set an option in YAML.

**Comment by markfairbanks** [comment]
Actually I want the ability to do paged printing. It doesn't currently work with `tidytable`. I'm basically asking - what do I have to do to get paged printing to work if the user wants it?

`paged.print = TRUE` and yet it doesn't work.
<img width="253" alt="image" src="https://github.com/user-attachments/assets/7e0b502e-8746-4683-b0a1-2ed290c0767d">

**Comment by yihui** [comment]
It works fine in the HTML output:

````
---
title: "Paged tidytable"
output:
  html_document:
    df_print: paged
---

```{r}
tidytable::tidytable(x = 1:3, y = 1:3)
```
````

<img width="557" alt="image" src="https://github.com/user-attachments/assets/abc665bb-17d6-4fb4-b73a-a9abaf511e69">

Or maybe you are asking "how to preview tidytable as paged tables when pressing the run button on the chunk toolbar in RStudio"? I don't know the answer to that question. My guess is that you'd need to define a print method, but you need to figure out a way to detect if `tidytable()` is called via the run button (if so, don't add the tibble class but only return a normal data frame). Anyway, I think that's out of the scope of **rmarkdown**, but more like an issue with the RStudio IDE.

**Comment by markfairbanks** [comment]
Ah gotcha, makes sense. Do I open an issue in that repository? Or does the issue stay open here?

**Comment by cderv** [comment]
> Do I open an issue in that repository? Or does the issue stay open here?

This is an issue to open there as it would required integration on their part. Unless there is a way for your to make your package comply with the IDE logic. 

Anyhow, for RStudio IDE behavior, this is with the IDE team to look into. So it is better there as a new issue to explain what is desired. 

Thanks !

**Comment by markfairbanks** [comment]
Yep that works. Thanks for all of the help.
