### ISSUE TITLE
Tables in an output don't have borders

### ISSUE THREAD

**Issue by franceskoi** [rstudio/rmarkdown#2566]
When I make tables (both row markdown and inserted from Excel via code chunk) in Source, and Knit an .Rmd document, the output document (Word, PDF, HTML) has only text that tables contain, but table borders are not shown. 
I use the code from some examples on the web that work since I see the results in the examples, and their tables have borders, but mine don't.
I use TinyTex and have Windows.
I also tried the code on my friend's computer who also has Windows, and the tables are also output without borders. Does that have something to do with the OS we are using? Can you help me solve this problem?

**Comment by yihui** [comment]
Your issue may be the same as https://github.com/rstudio/rmarkdown/issues/2567. Could you read and follow [the issue guide](new/choose) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. Thanks!
