### ISSUE TITLE
Add `pandoc-citeproc` under `SystemRequirements`

### ISSUE THREAD

**Issue by botan** [rstudio/rmarkdown#2584]
Thanks for the amazing package! 

In order to render RMarkdown on a Linux operating system outside of RStudio, it requires to `pandoc-citeproc` available. However, it is not explicitly stated in the `DESCRIPTION` file under `SystemRequirements`. I think it would be useful if it were. For instance, `pak::pak("rmarkdown")` then could auto-detect that as system dependency and install it during the installation.

I’m happy to make a PR if you think it’s worth adding it.

**Comment by yihui** [comment]
I'm not quite sure... `pandoc-citeproc` is required only for processing citations, and a document may or may not use citations.

If you feel strongly about it, please send a PR and I'm okay with adding to `SystemRequirements`. Thanks!

**Comment by cderv** [comment]
> In order to render RMarkdown on a Linux operating system outside of RStudio, it requires to pandoc-citeproc available.

pandoc-citeproc is required by older Pandoc version when citation processing is used. However, `pandoc-citeproc` is not required since Pandoc 2.11 (from 2020) when `--citeproc` was introduced 
See https://pandoc.org/releases.html#pandoc-2.11-2020-10-11

Also I can't find where but there was a change in Ubuntu repo and version where installing system pandoc would not automatically install `pandoc-citeproc` package at the same time as a required dependency. So this could be missing when installing pandoc on Ubuntu 20 or 22 where 2.5 or 2.9 are the one available. 
With Ubuntu 24 - 3.1 will be installed, so not more problem. See https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=pandoc&searchon=names

> For instance, pak::pak("rmarkdown") then could auto-detect that as system dependency and install it during the installation.

I don't know how it would be handled, but it would need to require some os version handling because pandoc-citeproc really does not need to be installed after Pandoc 2.11

**Comment by botan** [comment]
I appreciate your prompt responses.

I think it's not the best user experience to be needed to manually track system dependencies for specific rmarkdown features, especially when the package is used in production.

Also, Ubuntu 24 LTS was released just this year, and considering the [official support dates](https://ubuntu.com/about/release-cycle), I guess Ubuntu 20 and 22 users will be around for quite a while.

Do you think there is any harm in installing `pandoc-citeproc` on Ubuntu 24?

**Comment by botan** [comment]
It seems like the [rule](https://github.com/rstudio/r-system-requirements/blob/main/rules/pandoc-citeproc.json) in [r-system-requirements](https://github.com/rstudio/r-system-requirements) for `pandoc-citeproc` doesn't include Ubuntu 24.04.

**Comment by cderv** [comment]
My point is really that `pandoc-citeproc` is needed only for Pandoc version before 2.11, which is already 4 yers old. Pandoc is now at 3.5 so pandoc before 2.11 is now a quite old version. 

I understand that production environment does not evolve quickly, but I would think that when using **rmarkdown** in a new project today, a more recent version would be used. Especially in deployment environment. 

As an example, I am picturing the following. If you were to work on a R project locally, you would work with latest CRAN package version locally. And you would insure to deploy the same R package version in your production environment. Tools like **renv** are used for that. 
If you were to use **rmarkown** while developping in recent RStudio IDE, you would be working with a recent Pandoc 3 version which is bundled in the IDE. So when you deploy your project, it would be better to use the same Pandoc version the project was developed with. 

I hope it make sense. 

> I think it's not the best user experience to be needed to manually track system dependencies for specific rmarkdown features, especially when the package is used in production.

I agree with that. Honestly the problem is on Ubuntu package side. `pandoc-citeproc` should be a hard dependencies when installing `sudo apt install pandoc` on Ubuntu 20 et 22. I don't know why this is not the case. 

> Do you think there is any harm in installing pandoc-citeproc on Ubuntu 24?

Installing pandoc-citeproc is not needed on if you have Pandoc 2.11 or above. And also I am really not sure that `pandoc-citeproc` is available and installable in Ubuntu 24. The project https://github.com/jgm/pandoc-citeproc is archived and I don't think they built new version. 

Those are the reason for which I am not really strongly in favor of adding a System Requirement like this to this package

**Comment by botana-te** [comment]
Got it, thank you for the detailed explanation!

**Comment by botan** [comment]
Got it, thank you for the detailed explanation!
