### ISSUE TITLE
feature request: Rscript-like front end for render()

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#319]
It feels like `rmarkdown::render()` is missing an idiom for passing command line arguments.

Consider a recipe you might put into a `Makefile` to run an R script in a pipeline:

`Rscript foo.R january.csv`

where you might have lines like `options <- commandArgs(trailingOnly = TRUE); data_file <- options[1]` inside `foo.R`, so you can apply whatever brilliant processing `foo.R` does to data from different months.

Now imagine, you prefer to run R scripts and RMarkdown files with `rmarkdown::render()` instead because you like the side effect of getting Markdown and/or HTML reports along with the primary outputs.

Now your `make` recipes start to look more like this:

``` Makefile
Rscript -e 'library(rmarkdown); data_file <- "$(DATA_FILE)"; render("$<", quiet = TRUE)'
```

assuming you're using `Make`'s command line arguments to set the variable `DATA_FILE`. (_The recipe inevitably goes on to do a lot of file renaming and moving because `render()` is pretty wonky about specifying destination and intermediate directories other than source directory -- e.g. #286, #285, #236, #130_).

I'm not sure what solution I'm even asking for re: command line argument emulation for `rmarkdown::render()`. But `render()` is becoming my preferred way to run things and I'm interested in making that less awkward. Would appreciate any thoughts.

@sjackman do you have anything to add?

**Comment by jennybc** [comment]
Since this issue was opened, parametrized reports have been made possible: [Parametrized Reports](http://rmarkdown.rstudio.com/developer_parameterized_reports.html). Which creates even more opportunities to make a CLI really awesome.

**Comment by sjackman** [comment]
That's fantastic news! Just great.

**Comment by sjackman** [comment]
This feature is super useful, but it doesn't specify a command-line interface to set the parameters. We'll have to dream up that shell `Render` script.

**Comment by znmeb** [comment]
Hmmm ... is that in the CRAN rmarkdown or do I need to go to the GitHub version?

Speaking of Windows, most of the Windows open source devs I know (me in R and most everyone else in Python) prefer to work in their native language (R or Python or sometimes Ruby) rather than deal with the Windows command line. Even PowerShell just "feels wrong" when we have a perfectly good Turing-complete language and an IDE (RStudio or Jupyter).

"git bash" (the new one - http://git-for-windows.github.io/ - not the stable one) does have a decent Unix-like command line (and RStudio shells out to it just fine). But it's probably got a different compiler from what RTools has so you have to be careful about paths. :-(

**Comment by yihui** [comment]
I'm closing this issue now and I think `commandArgs()` plus parameterized reports should get you started. I don't think it is straightforward to ship a general-purpose shell script in the rmarkdown package, but it should be straightforward to write such a script on a case by case basis.

**Comment by sjackman** [comment]
Here's how I'm rendering parameterized reports from the command line:
```sh
Rscript -e 'rmarkdown::render("summary.rmd", "html_document", "output.html",
    params = list(input_tsv="input.tsv", output_tsv="output.tsv"))'
```
