### ISSUE TITLE
Code within enumerate environment is wrapped in markdown syntax

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rmarkdown#323]
I have a [small example](https://raw.githubusercontent.com/cpsievert/cpsievert.github.com/master/stack/enumerate/index.Rmd) where I have code inside LaTeX's enumerate environment, but the [code/output is wrapped in markdown syntax (instead of TeX)](https://github.com/cpsievert/cpsievert.github.com/blob/master/stack/enumerate/index.tex#L118-122). Both `rmarkdown::render` and the "Knit HTML" button seem to have this problem. I am using RStudio version  0.99.78 and here is my `sessionInfo`:

```s
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.6.1

loaded via a namespace (and not attached):
[1] digest_0.6.4     evaluate_0.5.5   formatR_1.0      htmltools_0.2.6 
[5] knitr_1.8        rmarkdown_0.3.13 stringr_0.6.2    tools_3.1.2     
[9] yaml_2.1.13  
```

**Comment by andeek** [comment]
Hi,

I have a similar question. Can I include fenced code chunks within the list structure as well for printing/highlighting languages other that R? For example:

```
 1. First item
 2. Second item

    ```cpp
    \* this is some C++ code *\
    ```
 3. Third item
```

I'm able to successfully print the C++ code within the Rmd file with the above syntax without indentions/lists, but this breaks the list structure. When I use indention I get undefined control sequence errors from pandoc. Any help would be appreciated, even if it's just telling me this cannot/shouldn't be done. I'm using `rmarkdown_0.5.1` if this helps.

Thank you,
Andee

**Comment by yihui** [comment]
@andeek I only see three spaces, and I believe the comment syntax is `/* */` instead of `\* *\`.

**Comment by andeek** [comment]
@yihui You're right, I was trying to make a fast example to show what I am seeing locally. I should have been more thorough (and reread what I wrote). You actually already fixed my problem by making me realize my mistake.

This issue was I am sourcing external C++ code for printing using `r paste(readLines('binomial.C'), collapse = '\n')` inside a cpp fenced code block as above, but I needed to add 4 spaced behind the '\n' in order to keep the indention structure.

Thanks so much for the help!
