### ISSUE TITLE
highlight.js reference in html document not using relative path

### ISSUE THREAD

**Issue by jrowen** [rstudio/rmarkdown#348]
I'm attempting to create a website html document (see description [here](http://rmarkdown.rstudio.com/html_document_format.html#creating-a-website)) using the code below.  In the resulting html file I'm not seeing any code highlight and finding path errors related to the `highlight.js` library.  Looking at the html source, it doesn't appear that the relative path is being generated correctly.

Here is the R code used to render the html document

```
out_nm = "ISM_class_model"
out_path = paste0("~/ShinyApps/markdown/", out_nm)
rmarkdown::render("markdown/ModelResult.Rmd", envir = e1,
                  output_format = "html_document",
                  output_file = paste0(out_nm, ".html"),
                  output_dir = out_path,
                  output_options = list(self_contained = FALSE,
                                                   lib_dir = paste0(out_path, "/lib"),
                                                   css = "../include/htmlcustom.css"))
```

and this is the chunk at the top of the Rmd file

```

---
title: 'ISM Model'
output:
  html_document:
    css: ../templates/htmlcustom.css
    includes:
      in_header: ../templates/header.html

---
```

Here's a subset of the output file's header that includes the path error.  The path for the other external libraries is being set correctly.

```
<script src="lib/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="lib/bootstrap-3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="lib/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="lib/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="lib/bootstrap-3.3.1/shim/respond.min.js"></script>
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="~/ShinyApps/markdown/ISM_class_model/lib/highlight/default.css"
      type="text/css" />
<script src="~/ShinyApps/markdown/ISM_class_model/lib/highlight/highlight.js"></script>
```

If I specify a highlight theme (e.g. `highlight: tango`), the error disappears, as the reference to highlight.js in the header is not in the output html.

**Comment by yihui** [comment]
Usually I don't recommend people to use the `output_file` or `output_dir` arguments of `render()`. I have seen problems too many times. There must be some deep bugs but I don't have time to investigate. Manipulating paths is a rather tricky problem.

Instead, I recommend you to render output files to the default location, and move them to the desired destination (e.g. use `file.rename()`).

For your last question:

> If I specify a highlight theme (e.g. highlight: tango), the error disappears, as the reference to highlight.js in the header is not in the output html.

That is because highlight.js is only used when `highlight = "default"` or `"textmate"`. For all other possible highlighting styles, Pandoc will do the syntax highlighting instead and generate the CSS directly in the HTML output. No JS will be involved.
