### ISSUE TITLE
R CMD build of an rmarkdown vignette does not fail when pandoc is too old

### ISSUE THREAD

**Issue by dtenenba** [rstudio/rmarkdown#356]
I had pandoc 1.12.2.1 installed and ran `R CMD build` against the test package at  https://s3.amazonaws.com/rmarkdown-pandoc-problem/anRpackage_1.0.tar.gz .

It did not produce an error but instead produced a tarball containing a vignette that did not contain a TOC.

If I try to build the vignette manually I get a useful error:

```
> library(rmarkdown)
> render("anRpackage.Rmd", html_document())
Error: pandoc version 1.12.3 or higher is required and was not found.
> 
```

But since I never use RStudio and usually try to build packages rather than individual vignettes, I did not see this message, and `R CMD build` doesn't fail here, but perhaps it should, with a similarly informative message.

Once I updated to pandoc 1.13.2.1 the problem went away but it took me a while to figure out that that's what I needed to do.

**Comment by yihui** [comment]
That is a knitr issue and intentional: I cannot assume CRAN has Pandoc installed on their machines, and honestly I dare not fail. When I cannot find Pandoc, or the version of Pandoc does not suffice, I will fall back to R Markdown v1, i.e. the markdown package. There should be a warning message: https://github.com/yihui/knitr/blob/master/R/utils-vignettes.R#L63-L75 but perhaps R CMD build has suppressed it.
