### ISSUE TITLE
can't  Knit PDF from Rmd file

### ISSUE THREAD

**Issue by ppetto** [rstudio/rmarkdown#378]
Although I can Knit to HTML and to Word, whenever I try to generate a PDF file I see the following error. (This is from the button on the Rstudio tab for my Rmd file.)

> ! LaTeX Error: File `framed.sty' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty)
> 
> Enter file name: 
> ! Emergency stop.
> <read *> 
> 
> l.34 \definecolor
> 
> pandoc: Error producing PDF from TeX source
> Error: pandoc document conversion failed with error 43
> Execution halted

I believe from what I've read elsewhere that I need to install framed.sty so that knitr cab see it somehow, but I'm not quite sure how to do this.

I'm running Mac OS X 10.10.2 and see TeXShop, TeXworks, and LaTeXiT in the list of applications.

I see two instances of framed.sty on my machine:

> \Library\Frameworks\R.framework\Versions\3.0\Resources\library\knitr\misc\framed.sty

and

> \Library\Frameworks\R.framework\Versions\3.1\Resources\library\knitr\misc\framed.sty

I would appreciate any & all advice, or pointers to advice.

**Comment by yihui** [comment]
`sudo tlmgr install framed` in your terminal should resolve the issue.

**Comment by jivelasquezt** [comment]
I also have this issue on macOS. When I try updating frame I get the following error:
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.

**Comment by yihui** [comment]
@jivelasquezt I recommend that you uninstall your existing LaTeX distribution and install TinyTeX instead: https://bookdown.org/yihui/rmarkdown/installation.html

**Comment by mirh** [comment]
But are other distributions presumed/expected to work with this at all?

Because I had just casually installed MiKTeX on windows, and proceeded to knit, only to be met with [this usual](https://github.com/yihui/knitr/issues/1686) very devoid of any meaning error. 
And after some tinkering, I found out that 
```
C:\PROGRA~1\RStudio\bin\pandoc>C:/PROGRA~1/R/R-36~1.1/bin/x64/Rterm.exe --slave --no-save --no-restore -e "rmarkdown::render('C:/template/template.Rmd');"
```
was bad, while 
```
C:\template>C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\pdflatex.exe -halt-on-error -interaction=batchmode "template.tex"
```
was good, asking me to install a bunch of packages and I was done and fixed forever (i.e. the previous scenario too). 
Now, I guess like it could be [this](https://tex.stackexchange.com/questions/358230/sorry-but-latex-exe-did-not-suceed#393049).. But then I also logged that Rterm goes desperately looking for tlmgr for some reason (even though, I don't think it should be supposed to, considering I have never asked for such thing)
