### ISSUE TITLE
fontsize, mainfont, sansfont ignored

### ISSUE THREAD

**Issue by 1beb** [rstudio/rmarkdown#402]
When preparing a pdf document, mainfont, sansfont and fontsize are ignored and the result is the same.

**Comment by yihui** [comment]
Are you talking about `pdf_document`, or a different PDF output format? The former should work. If it does not work, could you provide a minimal reproducible example? Thanks.

**Comment by 1beb** [comment]
Using the basic pdf_document format. Seems to ignore it entirely. 

![screenshot 38](https://cloud.githubusercontent.com/assets/421859/6745771/2e57f414-ce8a-11e4-9186-d66ef519282a.png)

**Comment by 1beb** [comment]
I can get the text that's after the header to change if I include raw tex to do so in an include or in the document itself. But the title maintains it's font.

**Comment by yihui** [comment]
I see. The font names will be passed to LaTeX (pdflatex or xelatex), and you may not just use arbitrary font names there (you have to consider which LaTeX engine you use). You can see how font names are actually used in the default LaTeX template: https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/latex/default.tex It seems you want to use the Wingdings font on Windows, and my guess is you have to use `xelatex` as the LaTeX engine. See `?rmarkdown::pdf_document`

**Comment by 1beb** [comment]
I just used something arbitrary to show that it doesn't work. I've been trying to get it to work with Georgia, but regardless of the latex_engine ... no luck.

**Comment by yihui** [comment]
It is not surprising that certain font names are ignored because they may be invalid names to pdflatex/xelatex. Obtaining the real names of fonts may be a trickier issue than you imagined, e.g. http://tex.stackexchange.com/questions/12881/how-to-get-a-list-of-all-available-ttf-fonts-with-xetex You cannot just think of a name and use it -- you have to check if xelatex can recognize it (pdflatex can be even trickier).

What I normally do if I really have to change the fonts for a LaTeX document is that I do it through LyX first and look at the LaTeX code it generates in the preamble, otherwise it is a frustrating issue to me as well.

**Comment by 1beb** [comment]
Ohhhhhhhhh, I get it now. What a disaster that is. I can add a short note to the rmarkdown online documentation in a pull request if it's on github.

**Comment by yihui** [comment]
Yes, the documentation is in the gh-pages branch of this repo.
