### ISSUE TITLE
AsciiMath syntax

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/rmarkdown#433]
Rmarkdown uses mathjax as it's math rendering engine and mathjax also supports asciimath syntax. Please enable asciimath syntax in mathjax.Latex is extremely cumbersome. Asciiath is very simple syntax for typing math equations

http://asciimath.org/

**Comment by sculptor3** [comment]
+1 for this feature

**Comment by yihui** [comment]
Since Pandoc does not support it (https://github.com/jgm/pandoc/issues/2654), I guess it is unlikely that we are able to support it. You will have to hack at it by yourself, and I think either of the two approaches on the AsciiMath homepage should be possible: http://asciimath.org You can [customize the MathJax URL](http://rmarkdown.rstudio.com/html_document_format.html#mathjax_equations), or load ASCIIMathML.js via the [`includes` option](http://rmarkdown.rstudio.com/html_document_format.html#includes).
