### ISSUE TITLE
escaped braces showing up when resizing with xtable

### ISSUE THREAD

**Issue by dwaggott** [rstudio/rmarkdown#444]
I'm using `render` to convert an rmd file into pdf. There are a number of tables including some using the `longtable` environment. The issue I'm seeing is that braces start showing up in the pdf around calls to xtable. Looking at the tex intermediate file shows that the leading brace in a sizing environment are getting escaped. 

Does this sound familiar? I haven't come up with a reproducible example as of yet.

```
\{\tiny

\begin{tabular}{lrrrrrr}
  \hline
```

**Comment by jjallaire** [comment]
Are you using results='asis' with the chunk that produces the xtable output?

**Comment by dwaggott** [comment]
yes.

**Comment by jjallaire** [comment]
Then I'm not sure what's going on here (have never seen this issue before)

**Comment by dwaggott** [comment]
Two things seem to trigger it. 

1. setting `options(xtable.floating = FALSE)`

2. changing to the longtable environment i.e. in `reporttools`

```
tableNominal(vars=data1, cap=cap1,
             vertical=FALSE,lab="tab:nominal",longtable=T)

```

**Comment by dwaggott** [comment]
I put an example in gist

https://gist.github.com/4eebecb60441d40f81ac

**Comment by yihui** [comment]
I don't think there is anything that we can do on our side here since it is a business between xtable and Pandoc, neither of which we maintain. Basically Pandoc will try to parse raw TeX code in Markdown, and if it _thinks_ the TeX code is not valid, it will give up and escape all special TeX characters. Pandoc's parser can produce false positives. More technical info here: https://github.com/jgm/pandoc/issues/2493 In your case, probably it was because `{\tiny` without `}` on the same line, which made Pandoc think the command was not balanced.
