### ISSUE TITLE
Inline code with newlines are not parsed correctly. 

### ISSUE THREAD

**Issue by biocyberman** [rstudio/rmarkdown#493]
Will, inline means now newline character, I know. But sometimes my editor, with auto line breaking within inline code, will give undesirable output. 

`````` markdown

---
title: "Untitled"
author: "Author"
date: "8/11/2015"
output: pdf_document

---

Test doc

\```{r}
var=15
\```
This is a custom var inline code with return: `r
var`. Where it would be nice to show 15 instead of inline code.

``````

**Comment by yihui** [comment]
knitr needs a space after `` `r `` to recognize the inline expression; is that possible with your editor?

**Comment by biocyberman** [comment]
I confirm that adding a space after ``r` works. Now I know what to expect, I will find a way to deal with it, i.e. setting visible line width limit instead of auto line breaking.

I use `emacs+ESS` by the way, I thought I don't need to inform the editor to make the case generic because Rstudio also does the same. I hope `knitr/rmarkdown` can, for example, replace all `newline` characters with spaces when in encounter R inline code signal ``r <inline code with newlines>``. At the moment I don't see any risk of doing this. 

Thanks for your work with `knitr` and `rmarkdown`.

**Comment by yihui** [comment]
I cannot replace the newline with a space or support newline immediately after `` `r ``, because the case below is not supposed to be an inline R expression (it is a verbatim R code block):

    ```r
    foo
    ```

It is possible to solve the problem using perl regular expressions (probably with zero-width negative lookahead), but I was not using perl regexp when I was designing knitr, so it may be a little dangerous to change that now. Anyway, if you want to help, you may search for `inline.code` in https://github.com/yihui/knitr/blob/master/R/parser.R and pattern.R and see if it still works after you change the R regexp to Perl regexp.

**Comment by biocyberman** [comment]
That's a smart move to ask me to inolve :-) I indeed want to try digging into knitr code and see if I can make it the way hope, just a tiny bit in your fantastic work. However, I am on a travel soon in some days for 5 weeks. I will get back to this may be after a month.

**Comment by yihui** [comment]
Since knitr 1.15, you can use `#` as well as a space after `` `r ``: https://github.com/yihui/knitr/releases/tag/v1.15 so that the inline expression will not be split after `` `r ``.
