### ISSUE TITLE
Problem rendering png image file when shiny is present on another slide

### ISSUE THREAD

**Issue by algoquant** [rstudio/rmarkdown#504]
Below is a small ioslides presentation with an embedded shiny application in one of the slides.  Another slide attempts to display a png image file.
When I "Run Presentation" in RStudio, the png image doesn't render, and there's just an image placeholder icon where the image should be.  I also get a warning: 

> Warning in file.create(to[okay]) :
  cannot create file 'C:\Users\John\AppData\Local\Temp\Rtmpkty0sF\file3b247a612422_files/C:/Develop/data/smile.png', reason 'Invalid argument'

It appears that knitr isn't able to copy the image to the ~\AppData\Local\Temp\ directory, and therefore can't display it, but I don't know why that's happening when there's a shiny application in one of the other slides.  

If I remove the shiny code, and remove "runtime: shiny" from the YAML, then the png image renders properly, without the warning.  In this case RStudio shows a button to "knit" the presentation, instead of "Run Presentation" for the shiny application. 

##### I submitted a question on this in stackoverflow here:

[ioslides presentation doesn't render png image file](http://stackoverflow.com/questions/32291566/ioslides-presentation-doesnt-render-png-image-file)

##### Similar problems were reported here:

[ioslides css and logo](http://stackoverflow.com/questions/28163147/shiny-presentation-ioslides-custom-css-and-logo-windows-7-8)

and here:

[Error adding images in ioslides](http://stackoverflow.com/questions/28492029/error-adding-images-and-plots-in-ioslides-presentation-w-runtime-shiny-on-wind)

##### Here is my setup:
Windows 9,
RStudio version 0.99.473,
Package: rmarkdown version: 0.7.3,
Package: shiny version: 0.12.2.9001,
Package: httpuv version: 1.3.3,

##### Here is my RMarkdown code:

    ---
    title: "ioslides Presentation with Shiny"
    author: "John Doe"
    date: "August 27, 2015"
    output: 
      ioslides_presentation: 
        widescreen: true
        smaller: true
        transition: 0.1
        self_contained: true
    runtime: shiny
    ---
    
    ## Slide with Embedded Inline Shiny Application
    
    Below is an embedded inline shiny application:
    ```{r, echo=FALSE}
    inputPanel(
      selectInput("n_breaks", label = "Number of bins:",
                  choices = c(10, 20, 35, 50), selected = 20),
      
      sliderInput("bw_adjust", label = "Bandwidth adjustment:",
                  min = 0.2, max = 2, value = 1, step = 0.2)
    )
    
    renderPlot({
      hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
           xlab = "Duration (minutes)", main = "Geyser eruption duration")
      
      dens <- density(faithful$eruptions, adjust = input$bw_adjust)
      lines(dens, col = "blue")
    })
    ```
    
    ## Slide With a Smiling Face
    
    ![smiling_face](C:/Develop/data/smile.png)

**Comment by jjallaire** [comment]
The issue may be the use of an absolute path to refer to the PNG. What happens if you move the PNG to a location relative to the Rmd file (either in the same directory or in a subdirectory).

**Comment by algoquant** [comment]
Yes, it works, after moving the .png file to the same directory as the .Rmd file, and changing:
    
    ![smiling_face](C:/Develop/data/smile.png)
to simply:

    ![smiling_face](smile.png)

But that's not a very convenient solution, since I prefer to have a separate directory with image files.
I'm also curious why the difference in rendering with shiny versus without shiny? 

###### Another issue, 
when I view the presentation in an RStudio window, the shiny doesn't render properly and the slider malfunctions.
In addition, with "widescreen: true" I get side panels that don't render properly. 
But when I view the presentation in a browser (Chrome) it all works fine.

###### Also, 
what's the preferred presentation format going forward, .Rmd or .Rpres ?

P.S. @jjallaire that's amazing to get an answer from the CEO at 7AM within 30mins of posting the question.  Thank you!

**Comment by jjallaire** [comment]
The issues here are mostly created by the implications of needing to deploy `runtime: shiny` documents on a server (which I realize you aren't doing here). With `runtime: shiny` we are actually running a Shiny application which has it's own way of serving URLs (i.e. you can serve files from the `www` directory of your Shiny application). For `runtime: shiny` we need to discover all of the dependencies in your document (via source code analysis) and then register custom Shiny URL handlers for them.

In doing this we require relative not absolute URLs to dependent resources because if you moved your `runtime: shiny` document to a server the absolute file reference wouldn't work (i.e. there is no `C:\` drive on the server). By requiring relative references for local `runtime: shiny` documents we are smoothing the path to ultimately deploying them on a server.

Not sure about slider malfunctioning, which version of RStudio are you running?

In terms of Rmd vs. Rpres, the former is going to be much better for attractive/customized output and the latter for teaching-type scenarios (i.e. where you want to display a presentation right within the IDE alongside code, graphics, etc.).

**Comment by algoquant** [comment]
I understand why deploying a presentation on shinyapps.io requires relative paths.  BTW, this relative path didn't work for me:

    ![smiling_face](../../smile.png)

At the moment I'm not trying to deploy my presentations on shinyapps.io.  Should I be using a different option in my YAML, than "runtime: shiny"?

I'm transitioning from LaTex/Beamer/Sweave/pdf to HTML slides. 
I have a need for both, fancy HTML slides for speaking presentations, and also for integrated presentations with narrative+Rcode+interactive_visualization for lecturing/teaching R.
Is it safe to assume that at the moment .Rpres doesn't support shiny?  Are there plans for supporting shiny?

Is it technically possible to knit an .Rmd presentation containing a shiny app into a single HTML?  I can do that with an .Rpres presentation.

##### Here is my setup:
Windows 9,
RStudio version 0.99.473,
Package: rmarkdown version: 0.7.3,
Package: shiny version: 0.12.2.9001,
Package: httpuv version: 1.3.3,

**Comment by jjallaire** [comment]
Yeah, we might not support relative paths in directories above the current one (also for deployment reasons). You might be able to work around this using the Windows equivalent of symlinks (although I don't have experience with what those would be or how they would work).

No you can't knit an .Rmd containing Shiny apps into a single HTML (it's a Shiny app rather than a document and requires a server to render).

There aren't currently plans to support runtime: shiny in Rpres (and I don't think that will change).

**Comment by algoquant** [comment]
I often need to share presentations.  
I can knit an .Rpres presentation into a single HTML, and share the file, but it can't contain a shiny app. 
Is there a good way of sharing presentations containing shiny apps, besides deploying them on shinyapps.io?

**Comment by jjallaire** [comment]
Since a presentation that includes a Shiny app requires an R process to run
it's never simply a matter of bundling up a single file. I'd say you have 3
choices:

1) If the receiver is familiar with R then send them the R code to run
(either as a zip file or as a Gist or other version control repo)

2) Deploy on shinyapps.io

3) Deploy using Shiny Server or Shiny Server Pro (see:
http://rstudio.github.io/shiny-server/latest/#r-markdown)
