### ISSUE TITLE
Can .Rpres format be handled by rmarkdown package?

### ISSUE THREAD

**Issue by sje30** [rstudio/rmarkdown#507]
Hi,

I use ioslides format a bit for writing slides.  The main frustration with it is the two-column support;  this seems to be much nicer in .Rpres format.  However, from what I have read, I cannot see a way of compiling .Rpres files into html outside of Rstudio. 

e.g. is there a magic way of calling Rstudio in batch mode from a Makefile, something like:
```
file.html: file.Rpres
     Rstudio --batch convert file.Rpres file.html
```
I have Rstudio installed, but tend to do most of my editing within Emacs, so having a way to do the conversion from the command line would be a great help.

Thanks, Stephen

cc: @benmarwick

**Comment by benmarwick** [comment]
Yes, I'm also curious to know what's going on to do the conversion to HTML5

**Comment by jjallaire** [comment]
No, there isn't a way to do this. Part of this is the lineage of Rpres --
it was originally intended as a way to create self-paced tutorials that ran
within the IDE (and some of it's features like being able to navigate to
source files anticipate this). As a result the implementation is very much
coupled to the IDE and can't be accessed standalone.

**Comment by sje30** [comment]
> No, there isn't a way to do this. Part of this is the lineage of Rpres --
> it was originally intended as a way to create self-paced tutorials that ran
> within the IDE (and some of it's features like being able to navigate to
> source files anticipate this). As a result the implementation is very much
> coupled to the IDE and can't be accessed standalone.

Ok, thanks JJ.  That's a shame, but makes sense.

Any chance of the flexible two-column formats making it across into any
of the slide formats supported by rmarkdown?

**Comment by jjallaire** [comment]
I think the best chance is in ioslides because we already have our own
custom HTML renderer for it (written in Lua, that's the extensibility
mechanism used by pandoc):

https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/ioslides/ioslides_presentation.lua

We could take the horizontal rule markdown (e.g. --- or ***) and turn it
into a column delimiter but that would require that we accumulate all
content in a buffer that we only render after we've established that a
slide is over and columns have been defined.

Note that there is currently a way to do two-column layout in ioslides (but
I grant you it's not quite as "smart" as Rpres i.e. it doesn't
automatically size images into columns):

http://rmarkdown.rstudio.com/ioslides_presentation_format.html#advanced-layout

**Comment by sje30** [comment]
ok, thanks.
