### ISSUE TITLE
Problem with ioslides_presentation on win7 current cran version of Rmarkdown (0.8)

### ISSUE THREAD

**Issue by simonthelwall** [rstudio/rmarkdown#510]
Running the default presentation fails on windows 7 with the message

> pandoc.exe: Could not fetch C:\Users\simon.thelwall\Documents\R\win-library\3.2\rmarkdown\rmd\ioslides\ioslides-13.5.1/fonts\OpenSans.ttf)

Is the slash between ioslides-13.5.1 and fonts in the wrong direction? 
The file OpenSans.ttf exists in ..\fonts\

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.11  dplyr_0.4.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0     digest_0.6.8    assertthat_0.1  R6_2.1.1        DBI_0.3.1       formatR_1.2    
 [7] magrittr_1.5    evaluate_0.7.2  highr_0.5       stringi_0.5-5   lazyeval_0.1.10 rmarkdown_0.8  
[13] tools_3.2.2     stringr_1.0.0   yaml_2.1.13     parallel_3.2.2  htmltools_0.2.6
```

**Comment by jjallaire** [comment]
I'm not able to reproduce this on Win7. A couple of questions:

1) What version of pandoc are you running? (you can find this out via `rmarkdown::pandoc_version()`)
2) Does this occur for you if you run rmarkdown v0.7 (the older version)

**Comment by simonthelwall** [comment]
```
> rmarkdown::pandoc_version()
[1] ‘1.14.0.1’
```

Installing rmarkdown version 0.7 resulted in a prompt from RStudio requiring a more up to date version.

**Comment by jjallaire** [comment]
The issue seems to be a bug in pandoc 1.14.0.1 (as it renders correctly using 1.13.1, which is the version bundled with RStudio, as well as with the very latest version 1.15.0.6). We know that there were several other bugs in 1.14.0.1 related to CSS processing so this is not a good release to run with rmarkdown. I'd suggest either uninstalling your version of 1.14.0.1 and relying on the version bundled with RStudio or if you need the newer pandoc just run the very latest version 1.15.0.6. Note that in the case that you choose the latter there seems to be an issue with pandoc getting on the PATH correctly, so you should choose "Advanced" installation and install for all users rather than for just your user account.

**Comment by simonthelwall** [comment]
Thanks very much!
