### ISSUE TITLE
rendering to md_document results in error if code generates HTML

### ISSUE THREAD

**Issue by dtenenba** [rstudio/rmarkdown#516]
Hi,

I have a document `test.Rmd` like this:

```
---
output:
   md_document
---

# test

```{r}
library(DT)
datatable(cars)
    ```
```

(just pretend that last line is in the first column; i couldn't figure out how to escape the backticks)

When I render it with:

```
render("test.Rmd")
```

I get

```
Error: Functions that produce HTML output found in document targeting markdown_strict output.
Please change the output type of this document to HTML.
```

Maybe this is a feature, however, isn't HTML valid in markdown? In my particular use case, I am later going to convert the resulting markdown file to HTML using my own tools, but I really need markdown as the output of `rmarkdown::render()`. It would be great if there were a way to override this error and have rmarkdown go ahead and write the html to the output document.

@vjcitn

@vobencha

**Comment by jjallaire** [comment]
The problem is that besides the generated HTML an htmlwidget like DT has additional dependencies (JavaScript and CSS) which in HTML rendering is automatically added to the document but which obviously can't be for markdown. Any publishing of your markdown will require manually reconstructing these dependencies (not impossible, but tricky, and not something we wanted to just leave as an undocumented exercise to the reader).

I created this branch which includes a workaround (an extra parameter to md_document that says it's okay to have HTML with dependencies): https://github.com/rstudio/rmarkdown/tree/feature/md-allow-html-dependencies. Not sure if this is the right answer though so probably won't merge this just yet.

**Comment by dtenenba** [comment]
Great! How do I add the allow_html_dependencies option? I tried

```
options(allow_html_dependencies=TRUE)
```

But that didn't work.

**Comment by jjallaire** [comment]
It's an md_document option, e.g.

---
output:
   md_document:
      allow_html_dependencies: true
---

**Comment by dtenenba** [comment]
OK, I tried that but I was hoping the resulting md document would contain the required script and css tags. 

I don't understand why these "obviously can't" be added to the document for markdown. HTML is valid markdown and in my case the document will eventually be converted to HTML.

Can the behavior be modified so that if allow_html_dependencies is TRUE, then all relevant html is copied to the output document?

**Comment by jjallaire** [comment]
It *can* be modified but it's unfortunately not a simple change and has some chance of breaking things so we aren't in a position to do that right now. Another possible workaround for you is this:

    ---
    output:
       html_document:
          self_contained: false
          keep_md: true
    ---

This preserves the intermediate .md file from an html_document render. It also specifies NOT to create a self contained document and so to copy all of the JS libraries to the _files directory alongside the html and md files. Then you'll just need to pick the right js includes out of the html file (you need the jquery but don't need any of the bootstrap or highlight.js stuff) and ensure they are available in whatever context you are rendering the markdown within.

**Comment by skranz** [comment]
Hi,
I just wanted to add to the discussion that it would be really great to add the option for creating md, tex (pdf), and word files even if some chunks emmit html. One important use case is that one wants to create an interactive rmarkdown document with all sorts of interactive HTML but also wants to  create a Latex or Word article that is based on the same rmarkdown document, but needs some manual tweaking afterwards. With the current rmarkdown version an error is thrown and I am not able to get the latex or word skeleton. (Furthermore, for large documents it is quite hard to find which chunks exactly emmit HTML and cause the error).

Perhaps instead of an explicit option that allows to emmit HTML, wouldn't it even suffice to change the error:

Error: Functions that produce HTML output found in document targeting markdown_strict output.
Please change the output type of this document to HTML.

into a warning? For example, I forked rmarkdown and replaced the corresponding lines in `render.R` by

```
    # if this isn't html and there are html dependencies then flag an error
    if (!(is_pandoc_to_html(output_format$pandoc) ||
          identical(tolower(tools::file_ext(output_file)), "html")))  {
      if (has_html_dependencies(knit_meta)) {
        warning("Functions that produce HTML output found in document targeting ",
             pandoc_to, " output.\nBetter change the output type ",
             "of this document to HTML.", call. = FALSE)
      }
      if (!identical(runtime, "static")) {
        stop("Runtime '", runtime, "' is not supported for ",
             pandoc_to, " output.\nPlease change the output type ",
             "of this document to HTML.", call. = FALSE)
      }
    }
  }
```
I find this much more convenient, when creating word and latex files from my .Rmd file.

**Comment by jjallaire** [comment]
One possible solution is for your code to check the knitr option `
rmarkdown.pandoc.to` to see if the target is html or another format. This
would enable you to emit alternative static content when appropriate.

I hesitate to change this to a warning as it will mask this issue for many
users (most folks don't intuitively understand that some content can't be
represented in non-HTML formats).

**Comment by skranz** [comment]
Thanks a lot for the quick reply. I understand that generally replacing the error with a warning could be undesirable. But perhaps an option to disable the error would give more advanced users more flexibility, while not masking the issue for other users?

The problem with `rmarkdown.pandoc.to` is that one has to manually check and adapt every chunk that possibly emmits html, which is quite tedious if the goal is to just quickly create a Latex or Word file.

If one wants to manually adapt chunks that emmit HTML, it can be difficult in large .Rmd files, to find all chunks that emmit HTML. Would it perhaps be easily possible to augment the error message with a  list of which chunks have emmited HTML and caused the error?

**Comment by jjallaire** [comment]
Agreed on all of your points.

Something like this might work:

1. A global option which conditions whether an error or warning is produced

2. The error message could include a reference to the option so that users
know how to change the error to a warning.

We'd definitely entertain a pull request along those lines.

**Comment by skranz** [comment]
Great, I will modify the code and create a pull request. 

I just have one question: is there a natural place to specify the option? I first thought, of putting an `allow_html` option it in the .rmd yaml section as follows
```
  ---
  output: 
    pdf_document: 
      keep_tex: yes
      allow_html: yes
  ---
```
But the presence of the option causes an error when running Rmarkdown. If I understand correctly, at this position there should be only output options that are passed to knitr and which are known by knitr. So modifying the code such that the non-knitr `allow_html` options is understood, is probably a larger intervention and probably makes the rmarkdown code base less nice. Therefore, I think to implement it simply as an global R option, that can be enabled with a call like
```
options(allow_html_in_all_outputs=TRUE)
```
Not super elegant, but it would do the job, for an advanced user that likes to emmit html. Or do you have a better suggestion where to specify the option?

**Comment by jjallaire** [comment]
You could actually have the option at the very top level of the YAML and
then render could pick it up there generically for all formats (this would
be more self contained than the global option). Something like:

---
title: "foo"
always_allow_html: yes
output:
   pdf_document:
      keep_tex: yes
---

You could check for this value in render via
isTRUE(yaml_front_matter$always_allow_html)

**Comment by skranz** [comment]
Thanks, that is a much better solution. I implemented it and created a pull request.
