### ISSUE TITLE
ioslides doesn´t show R codes when using 2 columns in a slide

### ISSUE THREAD

**Issue by melina-leite** [rstudio/rmarkdown#520]
Hi,
when I try to use 2 columns in a ioslides Rmd presentation, the html output of a the code doesn´t show the first lines of the code and I don´t know why. I´ve tryed many different ways, browsers, computers... 

As an example, I used this:
![script](https://cloud.githubusercontent.com/assets/8095675/10114890/b9776ee6-63cf-11e5-8041-37a207906a3c.jpg)

And the output for the second and third slides:
![error](https://cloud.githubusercontent.com/assets/8095675/10114821/7f381952-63ce-11e5-8c5f-a1b169ec3c33.jpg)

I´m using
Rstudio version  0.99.484
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

Could someone help me?

(sorry for my poor English and if it´s a dumb question - I´m also not good with programming stuff)

**Comment by yihui** [comment]
Not sure what the problem was there, but you may try the [xaringan](/yihui/xaringan) package, which is based on remark.js and also supports two-column layouts, e.g. you can see page 12 and 23 in the documentation: https://slides.yihui.name/xaringan/ (the source document can be found at https://github.com/yihui/xaringan/blame/master/inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd)
