### ISSUE TITLE
Figure captions for R Chunks

### ISSUE THREAD

**Issue by orschiro** [rstudio/rmarkdown#522]
Dear all, 

I am very grateful for your work on rmarkdown and rstudio which I am currently setting up for my research and I am very pleased by it!

I have one question concerning figure captions. 

For tables the following code works to add a caption:

```
| A | B | C | D | E |
|---|---|---|---|---|
| 1 | 2 | 3 | 4 | 5 |

Table: This is the caption.
```

For interactive figures, this does not seem to work when rendering the file using `Knit HTML`:

![image](https://cloud.githubusercontent.com/assets/170947/10119443/144fcf4a-6496-11e5-9f73-8d56b0420da0.png)

Could anyone please give me a hint how to use figure captions with r chunks?

Thankfully,

Robert

**Comment by dmenne** [comment]
Use the following in css:

```
body{
  counter-reset:table figure;
}
.table{
  width:auto;
}

caption::before{
  counter-increment: table;
  content: "Table " counter(table) ": ";
}

.caption::before{
  counter-increment: figure;
  content: "Figure " counter(figure) ": ";
}

caption, .caption{
  font-style:italic;
  margin-top:0.5em;
  margin-bottom:0.5em;
  width:80%;
  text-align: left;
}

```

**Comment by orschiro** [comment]
Dear @dmenne,

Thank you for providing a solution to this!

Warmly,

~Robert

**Comment by dmenne** [comment]
It helps a bit, but you cannot create cross-references to the figures and table, becaus pandoc does not support this. It has been discussed on the pandoc pages, and the syntax is settled, but for unclear reasons it is low on the priority list.

**Comment by yihui** [comment]
This is not an official announcement, but just FYI, we have actually solved these problems a couple of months ago in bookdown: https://github.com/rstudio/bookdown Please help us test it if you are interested but do not spread the link for now.

**Comment by orschiro** [comment]
Dear Yihui,

This looks promising.

Thanks for the hint which I will keep secret!

Warmly,

~Robert

**Comment by antagomir** [comment]
How to enable figure captions in html_notebook format? Setting fig_caption: TRUE in YAML does not help. For docx and pdf the captions do work OK.

**Comment by yihui** [comment]
@antagomir I'd say notebooks are primarily for preview/pedagogical purposes (see what the text/graphics output roughly looks like). If you want a sophisticated output document, you have to compile it using specific output formats like `pdf_document`/`html_document`.

To all: I'm closing this issue, since the answer to the original question is simple: the chunk option `fig.cap` can be used to add a caption to a plot, and you have to specify `fig_caption: yes` in YAML to enable caption support in Pandoc. A brief example:

    ---
    title: "Untitled"
    author: "Frida Gomam"
    output: 
      html_document: 
        fig_caption: yes
    ---
    
    ```{r fig.cap="My figure caption."}
    plot(cars)
    ```

And one answer to @dmenne's question (figure numbering/cross-referencing) is to use the [bookdown](https://bookdown.org/yihui/bookdown) package. A minimal example:

    ---
    title: "Untitled"
    author: "Frida Gomam"
    output: 
      bookdown::html_document2: 
        fig_caption: yes
    ---
    
    See Figure \@ref(fig:mycap).
    
    ```{r mycap, fig.cap="My figure caption."}
    plot(cars)
    ```
