### ISSUE TITLE
unexpected results when rendering html_vignette() output via "Knit HTML" button

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#530]
If I have a vignette `foo.Rmd` with YAML like so:

```
---
title: "Whatever"
date: "`r Sys.Date()`"
author: "Jenny Bryan"
output:
  rmarkdown::html_vignette:
    keep_md: true
vignette: >
  %\VignetteIndexEntry{Whatever}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

and I render via the "Knit HTML" button, no files are created within the package's `vignettes` subdirectory. No `foo.md`, `foo.html`, etc. Yet I get an HTML preview. I gather it's *all* being placed in a temporary directory?

The only way to get the expected files to appear locally appears to be via *Build > Document* or `devtools::document(roclets = "vignette")`.

[The documentation](http://rmarkdown.rstudio.com/package_vignette_format.html) says that "All options support for `html_document` also work for `html_vignette` so I guess I expect it to function like all other Rmd files destined for HTML. I can't figure out why "Knit HTML" would work differently when output is `html_vignette`.

If you alternate between these two ways of rendering the vignette, this makes it really easy to commit and push out-of-date `.md`, `.html` and figs.

**Comment by jjallaire** [comment]
Yes, we do all rendering for Rmd files contianed within the `vignettes` directory of a package in a temporary location. This was a feature requested by @hadley to not pollute the vignettes directory with preview side effects which then might get inadvertently included in the package. However it seems like this too might have some undesirable effects -- @hadley What's your thought here? Should we:

a) Keep the current behavior and document it better;

b) Make it an option for those that don't like it; or

c) Revert and do  no special treatment for previewing Rmds in the `vignettes` directory

**Comment by hadley** [comment]
I think now that I understand better c is probably the right choice. But @jennybc has thought about this much more than me, so I'd do whatever she thinks is best.

**Comment by jennybc** [comment]
I like c!

Normal preview behavior puts the files in the same place that *Build > Document* and `devtools::document(roclets = "vignette")` put them, so feels like nothing is lost. And it's less puzzling.

**Comment by yihui** [comment]
I guess c is not a good idea at least last year. I vaguely remember `R CMD check` might warn against pre-built vignette output in the `vignettes/` directory (the vignette output will be automatically generated to `inst/doc` during `R CMD build`). The other problem is that `R CMD build` will not rebuild the vignette if it has been built under `vignettes/` by the package author. This is pretty bad because you may have updated Rmd but forgot to rebuild html. I'm not sure if these two reasons are still true for the current version of R.

@jennybc Why do you want the HTML output file? You will get it in the tarball from `R CMD build`. BTW, I'm not sure if you have tried `servr::vign(daemon = TRUE)` :) Normally I just write in Rmd, see the preview in RStudio viewer, and `R CMD build` when I feel the vignette is complete. I don't see the value of the HTML output file under `vignettes/`.

**Comment by jennybc** [comment]
I haven't submitted to CRAN many times, so I certainly defer to you on what causes trouble. I think I've also always done so via `devtools`, which might be finessing some of the stuff @yihui points out?

I actually don't want the HTML. I have become Our Lady of the Intermediate Markdown and that's what I want to be available in a package on GitHub. Either before it goes to CRAN or in the months between CRAN versions. It's nice to be able to read current vignettes for packages without necessarily having to install or update. So it's not about me, it's about making it easier for a potential user to see a rendered vignette.

**Comment by yihui** [comment]
@jennybc I see. Nowadays I tend to build the HTML vignettes on Travis and deploy them to the gh-pages branch automatically, so I don't need to worry about these intermediate files (e.g. http://yihui.name/formatR/ and http://yihui.name/printr/). I think that is even easier for a user to see the actual rendered vignette. It may take you a while to set it up, though, but once it is set up, all you have to do is push to Github.

**Comment by jennybc** [comment]
Those `.travis.yml` files are definitely more interesting than mine :)

**Comment by jjallaire** [comment]
So sounds like we should leave the behavior as is in order to not provoke R CMD check or have potentially out of date vignettes published to CRAN.

@jennybc I think for the scenario of publishing vignettes on GitHub via .md you might just want to do something special (e.g. build them within another directory that you exclude from the package proper via .Rbuildignore)

**Comment by hadley** [comment]
I'm pretty sure I checked the vignette behaviour recently and didn't see the problem that @yihui saw. But it would be worth further investigation.

**Comment by jjallaire** [comment]
Even in the absence of R CMD check problems the issue of an out of date
html file masking an Rmd source file seems somewhat problematic (but
perhaps CRAN no longer accepts pre-built html vignettes?). The fact that
we've got hundreds of folks using the tools to create packages without
reported problems makes me feel conservative about any changes (especially
at the end of a release cycle where time for testing/feedback is more
limited).

My instinct is that if the goal is the creation of an .md file in the
vignettes directory for browsing on GitHub that perhaps a script dedicated
to making this happen is the right approach for now (e.g. when ready to
formally updated the GitHub published version just run a render creating
all the right files and pushing them into a directory within the repo that
is .Rbuildignored).
