### ISSUE TITLE
Rmarkdown Snippets not available

### ISSUE THREAD

**Issue by Nicktz** [rstudio/rmarkdown#535]
Hi, awesome package!

One small comment, the Rmd snippets are not yet available or is there a way to activate it?

I ask particularly as there is not shortcut key for comments using Rstudio?

**Comment by yihui** [comment]
I don't remember in which exact version RStudio added Markdown snippets, but at least they are available in the current preview version https://www.rstudio.com/products/rstudio/download/preview/

**Comment by ha0ye** [comment]
It seems that outside of code chunks in Rmarkdown files, the normal *Tab* keyboard shortcut (or 250ms delay) for code completion doesn't work, but the *Shift+Tab* to insert manually does.

**Comment by Nicktz** [comment]
@ha0ye Thanks, it now works!

Also, it might be useful to add that one needs to indent the second line for it to work as well. I added it as follows:

    snippet zz

**Comment by nathancarter** [comment]
Is @ha0ye's comment not considered a bug?  Should I start a separate issue for it?  Note that people are asking about it:  http://stackoverflow.com/questions/37748516/rstudio-snippet-not-working#comment65682879_37748516

**Comment by kevinushey** [comment]
The completion popup (which includes snippets) only shows within R code chunks; we don't currently display a completion popup within the markdown sections of an R Markdown documents. (we figured nagging the user with completion popups while writing Markdown prose would be counter-productive, more-so since it's likely the user would like to insert literal tabs in many cases rather than request completions).

This implies that, right now, the only way to execute snippets within the markdown sections of an R Markdown document is through Shift+Tab, and that's been the behavior since the feature was introduced.

**Comment by nathancarter** [comment]
Is it documented anywhere?  Otherwise it's natural to assume it's just not functioning.  If I hadn't explicitly searched GitHub issues for RStudio, I would have assumed it was a mistake, not an intentional design decision.  (And I wouldn't have known how to use it!)

**Comment by kevinushey** [comment]
The article is [here](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets), but you're correct that this behavior is not documented. We should make that change.

**Comment by ha0ye** [comment]
Yeah, I didn't think it was possible until I saw @yihui's comment, which caused me to play around with different keyboard shortcuts. Documenting it in the article on snippets would be good.

**Comment by nathancarter** [comment]
Yes.  I had certainly found and read the article on snippets, which had me all excited, until they failed to work in Markdown mode (I thought).  In other words, that article is the first place most people will look, so it's the right place to document it.  (I would have seen it.)
