### ISSUE TITLE
R inliners with special characters (ampersand) inside LaTeX environment not escaped automatically

### ISSUE THREAD

**Issue by danielkrizian** [rstudio/rmarkdown#553]
R string containing ampersand (&) displays correctly when used outside LaTeX environment, such as `\begin{itemize}`

This works and ampersand is automatically escaped by `pandoc` (or `knitr`?):
```
---
output:
  pdf_document
---

`r "Guns & Roses"`
```
Now, when the R inliner with ampersand string is specified inside LaTeX environment, following error is thrown: 
`! Misplaced alignment tab character &.`:

```
---
output:
  pdf_document
---

\begin{itemize}
\item `r "Guns & Roses"`
\end{itemize}
```

The `R` inliner must be wrapped in the `\verb`, when inside any LaTeX environment. That works:

```
---
output:
  pdf_document
---

\begin{itemize}
\item \verb| `r "Guns & Roses"`|
\end{itemize}
```
It would be great to have the same/consistent behaviour inside and outside the environment, i.e. without the need for the user to manually insert `\verb`

**Comment by yihui** [comment]
I remember you also asked this question on StackOverflow, but I cannot find the link now.

In short, power comes with responsibility: when you decide to use the LaTeX magic in Markdown, you are responsible for everything in the LaTeX environments/commands, including escaping special characters by yourself. It makes sense for Pandoc not to escape the ampersand in this case, because some user may actually want to include a table in the itemize environment. Pandoc should not shut the door for these users.

Isn't it possible to use pure Markdown that looks simple and elegant? e.g.

    ---
    output:
      pdf_document
    ---
    
    - `r "Guns & Roses"`

Of course, you can escape the ampersand as well:

    ---
    output:
      pdf_document
    ---
    
    \begin{itemize}
    \item `r "Guns \\& Roses"`
    \end{itemize}

**Comment by danielkrizian** [comment]
Thanks for insight, in the end I've decided to source the content from YAML not via R. 
YAML having the advantage to accept both markdown and LaTeX markup as is.
https://raw.githubusercontent.com/danielkrizian/resume_template/master/skeleton.Rmd
