### ISSUE TITLE
Feature request: Placing bibliographies before the end of the document

### ISSUE THREAD

**Issue by richierocks** [rstudio/rmarkdown#556]
From the [R Markdown V2 documentation](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html):

> Bibliographies will be placed at the end of the document.

Some journals require articles to include figures or tables after the references.  At the moment, this means that you have to create a main document, then create a second document for the figures and tables, and manually stitch them together.

It would be nice to have a feature allowing you to override the position of the bibliography in an R Markdown document.

**Comment by yihui** [comment]
Two possible solutions:

1. Use `after_body` to specify a tex file to be included after the document body: http://rmarkdown.rstudio.com/pdf_document_format.html (See the section `Includes`);
2. Define your own LaTeX template, e.g. here is the default LaTeX template: https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/latex/default.tex

Other than these, we cannot do anything on our side because we rely on Pandoc to render Markdown and Pandoc does not have a way to specify where to put the bibliographies.
