### ISSUE TITLE
render pdf fails

### ISSUE THREAD

**Issue by stephenll** [rstudio/rmarkdown#6]
Hello,

I was able to use render to create an html document but failed on both windows and osx when trying to create a PDF.  I have texlive installed and use it regularly to compile documents using pdflatex.

in R studio I selected new markdown document.  Saved it to a local directory.  Then ran the following code:

```
render('test1.Rmd',pdf_document())
```

On OSX I received an error about needing to install X11.  RStudio crashed at that point.

On windows I was able to get an error message in the console.

```
processing file: test1.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: unnamed-chunk-1
  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-2 (with options) 
List of 2
 $ fig.width : num 7
 $ fig.height: num 6

  |.................................................................| 100%
  ordinary text without R code


output file: test1.knit.md

C:/Users/stephen/AppData/Local/Pandoc/pandoc test1.knit.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-markdown_in_html_blocks --output test1.pdf --filter C:/Users/stephen/AppData/Local/Pandoc/pandoc-citeproc --template C:/Users/stephen/R/win-library/3.0/rmarkdown/rmd/latex/default.tex --highlight-style tango --latex-engine pdflatex --variable geometry:margin=1in 
pandoc.exe: Error producing PDF from TeX source.
! LaTeX Error: File `article.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 

l.2 \usepackage

Error: pandoc document conversion failed
In addition: Warning message:
running command 'C:/Users/stephen/AppData/Local/Pandoc/pandoc test1.knit.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-markdown_in_html_blocks --output test1.pdf --filter C:/Users/stephen/AppData/Local/Pandoc/pandoc-citeproc --template C:/Users/stephen/R/win-library/3.0/rmarkdown/rmd/latex/default.tex --highlight-style tango --latex-engine pdflatex --variable geometry:margin=1in' had status 43 
```

**Comment by cmbarton** [comment]
This is a misdiagnosis on the Mac (I don't know about Windows, but possibly the same). The problem is that RStudio does not have all the programs you need to convert RMarkdown script to PDF. This really needs to be updated in the docs. 

So here is what you need:

1. Pandoc (this may come with RStudio now, but I installed a new version from http://pandoc.org/installing.html

2. LaTex. This does not come on a Mac nor does it come with RStudio. But you must have it to convert to PDF. The standard MacTex download is enormous (over 2 GB), but you don't need that for making PDF's (or for a lot of other things using LaTex). So get BasicTex which weighs in at a featherweight 100 MB. You can get it at: https://tug.org/mactex/morepackages.html

3. You are not done yet. You now must install special "Titling" fonts or the conversion will still bomb. The easiest way to get those is through a command line utility for TexLive. But you have to install these as a system administrator. So open a terminal window and type the following and press return (you must be connected to the internet).

sudo tlmgr install titling

4. Then restart RStudio and you can now get very nice PDF's

**Comment by BusyStas** [comment]
is there a way to check whether *pandoc* is installed or not?

**Comment by jjallaire** [comment]
Try the pandoc_available function

**Comment by ablazko** [comment]
@cmbarton Hi Michael, I executed the procedures that you provided and everything was fine during installation (steps 1, 2 and 3), but still getting the error message in rstudio after restarting! I'm just trying to create a .pdf from default version of RStudio (new file > r markdon > pdf).

```
! LaTeX Error: File `framed.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.39 \definecolor

pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted
```

These are my session infos:
```
> R.version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree  
```

Do you (or anyone) have any idea on how to solve this? This problem happens only for .pdf. generation.
Thanks in advance.

**Comment by cmbarton** [comment]
Glad you solved it. I'm traveling with intermittent email.
