### ISSUE TITLE
Resolving HTML dependencies with the same name but requiring different files

### ISSUE THREAD

**Issue by yihui** [rstudio/rmarkdown#645]
I just ran into a situation where a certain dependency object may point to different files depending on the actually required files, e.g.,

```r
fooDependency = function(modules = c('a', 'b')) {
  htmlDependency(
    script = c(if ('a' %in% modules) 'a.js', if ('b' %in% modules) c('b1.js', 'b2.js'))
  )
}
```

For example, users may only want to use the module `a`, in which case I only need to load `a.js`.

rmarkdown seems to be ignoring later dependency objects with the same name as a previous dependency object, so if I have two HTML widgets using different modules of a library, the second widget will not render correctly because its JS dependencies are not included in the HTML head.

I feel the dependency objects in knitr metadata should be merged in this case, instead of using the first one to override all following ones.

**Comment by jjallaire** [comment]
We debated this when designing the system, but thought that merging could
be dangerous because e.g. you might have two mutually exclusive modules
loaded by two different components and then the page is broken. I guess we
are implicitly requiring that dependencies include all possible
sub-dependencies, which I agree could get a bit heavyweight. I wonder if
attachments or extra_dependencies could be used to work around this?

**Comment by yihui** [comment]
Okay, my usual philosophy again: if we are not sure about the right decision, just provide an option and let the package authors make the decision. They should know their JS libraries better than us, and they can decide whether the dependencies are mergeable. Something like `htmlDependency(mergeable = TRUE)`. I can submit a PR to htmltools if this sounds okay.

**Comment by jcheng5** [comment]
Sub-dependencies should just be separate dependencies, that's always been my position.

The only case I know we don't handle are like jQueryUI, where sub-dependencies are handled not with additional .js files, but with custom builds--I don't have a solution for that yet.

**Comment by yihui** [comment]
But sub-dependencies are not necessarily mutually exclusive, e.g. module A may require a.js and b.js, and module C in the same library requires b.js and c.js. If I make them sub-dependencies, I will have

```html
<script src="A-version/a.js"></script>
<script src="A-version/b.js"></script>
<script src="C-version/b.js"></script>
<script src="C-version/c.js"></script>
```

That is probably not harmful, but b.js is copied and loaded twice. To solve that problem, I can certainly factor out b.js into yet another sub-dependency, so now I have three sub-dependencies.

```html
<script src="A-version/a.js"></script>
<script src="B-version/b.js"></script>
<script src="C-version/c.js"></script>
```

This sounds cumbersome and the number of sub-dependencies quickly grows when the number of modules is moderately large and have inter-dependencies.

I'm making the assumption that the package author knows that the modules are mergeable. Under this assumption, I think the approach I proposed is much cleaner and efficient.

Here is the basic structure of the DataTables library:

- DataTables
    - Core
    - Extensions
        - AutoFill
        - Buttons
            - copy
            - excel
            - ....
        - ....
    - Plugins

If I make a separate sub-dependency for every single bottom-level module, I will have a lot of them.

The jQueryUI issue could have been solved by this approach, because we know the jQueryUI modules should be mergeable. We could have a package that ships the full jQueryUI package, and let users choose which modules to use, e.g.

```r
jQueryUI = function(modules = c('Accordion', 'Autocomplete', ...)) {
  htmlDependency('jqueryui', x.x.x, scripts = if (fooModule) 'foo.js' else ..., mergeable = TRUE)
}
```

Then other package developers can just call this function and select the modules that they want. This basically brings the custom download builder into R, and we do not need to worry about this person's custom jQueryUI will completely override the other person's custom jQueryUI. Everybody just gets the modules that they actually need.

**Comment by jcheng5** [comment]
The problem with mergeable is that it won't work for client side dependency rendering, which is needed for these things to work with Shiny. https://github.com/rstudio/shiny/blob/d63dd6086a6776ec30cdd0b395c76593c9ebcb00/inst/www/shared/shiny.js#L2821

You should have a separate dependency for every single bottom-level module, yes. It's just code that generates dependencies, so you can write a function to make this clean and efficient. The source code would look little different between one solution and the other (akin to the difference between `[a], [b], [c]` and `[a, b, c]`), but the many dependency solution would work properly with client side dependency rendering.

The jQueryUI approach depends on the individual files being broken out, if we had that then we could also do individual dependencies as well--the problem is we don't have the individual files. (Although it looks like there's hope as [since 1.11 jQueryUI supports AMD](https://learn.jquery.com/jquery-ui/environments/amd/))

**Comment by jjallaire** [comment]
I do something like this for flexdashboard. Depending on what icon
libraries are referenced and whether the user chooses to embed source code
I dynamically compose a list of dependencies:

https://github.com/rstudio/flexdashboard/blob/master/R/flex_dashboard.R#L267-L277

**Comment by yihui** [comment]
I still feel this is not a very sustainable approach since 1) I will have to figure out the relationships among all modules (do intersection and complement on sets); 2) As a new module comes into the system, I need to figure out its relationship with existing modules as well (e.g. existing dependencies may have to be broken further into multiple sub-dependencies).

On the other hand, I feel the client-side rendering problem is solvable. I guess the reason that it does not work currently is this:

```js
  if (htmlDependencies.hasOwnProperty(dep.name))
    return false;
```

i.e. it is based on the assumption that the dependency name completely identifies a dependency object. We can change that and render the set difference instead when `mergeable = TRUE`, e.g. if a.js is already rendered and the new dependency has both a.js and b.js, we just render b.js.

**Comment by jcheng5** [comment]
1) These relationships already need to be mapped somewhere in your source code (regardless of which solution you choose). Once you've done that, either approach is trivial to implement with equal ease. 2) Make every file its own dependency if that is how deep the relationships go. There's almost no downside I can think of to having a single dependency with two script files, or two dependencies each with one script file. It doesn't even have to be harder to manage in the code.

On the other hand, the client-side rendering problem is harder than you think. The htmlDependencies object doesn't have access to all the dependency info, only the names and versions. The dependencies can be rendered in two ways: as the page is generated, and after the page is generated. In the former case, a special tag is emitted into the page that indicates what dep names and versions have already been included in the page. So to make this work with mergeable, you'd have to change this so that the entire htmlDependency object is serialized to the page. And then you'd also need to depend on a new version of Shiny.

Maybe I'm not being clear on what I'm proposing. The code should literally end up looking almost the same other than maybe a new helper function or two. If that's not what you're picturing then maybe we should vchat about it.

**Comment by jcheng5** [comment]
Here's my translation of the code example in your first post. You don't have to do it this way but my point is that the code for expressing the relationships will effectively be the same.

```r
#' @param ... Names of JS files to include
makeDeps <- function(names) {
  lapply(names, function(name) {
    htmlDependency(
      name = paste0("DT-plugin-", name), # maybe strip .js?
      script = name, ...
    )
  })
}

fooDependency = function(modules = c('a', 'b')) {
  makeDeps(c(
    if ('a' %in% modules) 'a.js',
    if ('b' %in% modules) c('b1.js', 'b2.js')
  ))
}
```

**Comment by yihui** [comment]
Okay, let me think more about it and try what you suggested. Thanks for all the explanations!
