### ISSUE TITLE
Floating Table of Contents Doesn't Work if Browser Window is Narrow

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#665]
If the web browser is resized to be narrow enough so that the table of contents moves to the top of the document, rather than in a column at the left of the document, it doesn't float when the document is scrolled down.

**Comment by jmcphers** [comment]
That's currently by design; what behavior would you expect here? If it floated, it'd consume almost all the real estate on small devices (which is largely the target of the narrow view). 

Ideally for small devices we'd put the ToC into a "hamburger menu" or sidebar menu, although that'd require a lot more styling and script than than the feature currently consumes.
