### ISSUE TITLE
Why do vertical spaces appear in tables in tufte-handout?

### ISSUE THREAD

**Issue by puterleat** [rstudio/rmarkdown#714]
I'm struggling to understand why the following code produces a pdf where the table has additional space between the 2nd and 3rd rows. This is a minimal example of a larger table where the pander() function was used to generate the markdown. I thought at first old style numbers might be to blame, but turning these off does not solve the issue.

```

---
title: Summaries for 2015
output: rmarkdown::tufte_handout

---

----------------------------------------------------------
  Module   Element   Submitted   Not Submitted   Mean   SD 
-------- --------- ----------- --------------- ------ ----
555        1         18             1          57   9.6 

556        1         35             2          64   10.6

556        2         35             2          61   16.6
----------------------------------------------------------

  Table: Submissions and grades by module and element.

```

**Comment by yihui** [comment]
Sorry I have no idea. I don't see the same problem with `knitr::kable()`.

**Comment by yihui** [comment]
Since this looks like a question instead of a bug report or feature request, please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead with a minimal reproducible example. Let me know if you need help on creating a minimal reproducible example. I think the example does not need to involve rmarkdown. A pure LaTeX example should demonstrate the issue. Thanks!
