### ISSUE TITLE
within doc links does not change tabs

### ISSUE THREAD

**Issue by fhoces** [rstudio/rmarkdown#718]
Not sure if this is a bug but when I create a link referencing a different section in the my markdown doc, it doesn't jump to the correspoing tab

```
# Section 1 {.tabset}

## Sub section 1

go to [link1](#sub-sub-section-2) in sub section 2. 

##Sub section 2

### Sub sub section 2


```

**Comment by jjallaire** [comment]
That's correct, tabs are indeed not addressable by anchor links.

**Comment by fhoces** [comment]
Thanks for confirming JJ. Any chance this issue will be addressed in the near future?

**Comment by tvarju** [comment]
This also kills Table of Contents:

- just add toc to the above example you will see section 1 only
- add floating toc you will see sub sub section 2 additionally, but nothing else, and clicking this sub sub section 2 will also not send you there

Shall I open a new issue with this, type the example, any other way I can help?

**Comment by psychelzh** [comment]
I found that all the `implicit_header_references` do not work when tabs are used. Is it right?

**Comment by yihui** [comment]
I tend to say this is by design, and is unlikely to change in the future. You can only click a tab title to see the tab content. It may well be possible to solve the problem using JavaScript, but I don't think we will ever have the bandwidth to fix an issue from an upstream library (Bootstrap).

**Comment by brooklyOPC** [comment]
Is there any bandwidth now to make this update? 

It makes the TOC look broken when you click and it doesn't take you to the correct tab. I've made a work around by just adding a superfluous section around it so it doesn't show up in the TOC (raising the TOC level wouldn't be compatible with the rest of the document) but it just looks clunky.

It feels off to say that something requiring a work around to be presentable is by design...

**Comment by cderv** [comment]
I think some features from boostrap are still missing to make this possible more easily 
https://github.com/twbs/bootstrap/issues/25220
