### ISSUE TITLE
Message handling in R Notebooks

### ISSUE THREAD

**Issue by tklebel** [rstudio/rmarkdown#734]
Thanks a lot for the new R Notebooks, the new possibilities are really exciting!

I encountered two issues with messages, which work fine in a standard `html_document`:

1. In this case I use `message` inside the function to display the variable which is plotted.
In contrast to a standard `html_document`, the output of `message` is placed  on top of 
the graphs, not in between them.

```r
{r, message=TRUE}
message("hi")

library(ggplot2)
vars <- names(mtcars)

plots <- function(var) {
  p <- ggplot(mtcars, aes_string("mpg", var)) + geom_point()
  print(p)
  message(var)
}

purrr::walk(vars[1:3], plots)
```

(2) It is not possible to surpress messages via chunk options, neither inside the chunk, nor one level deeper inside the function:

```r
{r, message=FALSE}
message("hi")

library(ggplot2)
vars <- names(mtcars)

plots <- function(var) {
  p <- ggplot(mtcars, aes_string("mpg", var)) + geom_point()
  print(p)
  message(var)
}

purrr::walk(vars[1:3], plots)
```

**Comment by jjallaire** [comment]
@jmcphers Just making sure you see this.

**Comment by jmcphers** [comment]
We are indeed tracking both of these issues already. We've got a good start on the first one and hope to have a fix merged soon. As regards to the second one we're evaluating options as some of the fixes have unpleasant side effects but we're hopeful we can get it working smoothly soon!

Most notebook execution issues (including these) are bugs in RStudio rather than in rmarkdown, so I'm closing this issue; I've added your notes and examples to the bugs on our end. Thanks for reporting this w/ reproducible examples!

**Comment by tklebel** [comment]
@jmcphers Thanks for the heads up! I guess there is no way to track your progress, since there is no public issue tracker either on https://github.com/rstudio/rstudio or on https://support.rstudio.com/hc/en-us/community/topics?

Anyways, if I had a further issue about the behaviour of RStudio previewing the R Notebooks, where should I post it? Over on https://support.rstudio.com?

**Comment by jmcphers** [comment]
Yes, the support site is the best place to go right now (we don't have feature-specific issue trackers right now). Thanks!
