### ISSUE TITLE
indent for r chunk

### ISSUE THREAD

**Issue by earthcli** [rstudio/rmarkdown#802]
I have set a text-indent wishing to only  indent for text in the  html of rmarkdown output,  like:

``` css
<style type="text/css">
p{
  text-indent: 2em;
}
</style>
```

it does works for text paragraphs, but it also works for images in  r chunks, which is not what I want.

``````
``` {r rbody,fig.align='default',fig.show='hold',out.width='48.5%'}
imagepaths=list.files(pattern="png");
include_graphics(imagepaths)
```
``````

in which I have insert four local images by include_graphics(), and I want to layout them as two image on each row, and no indent. 
But now the first row and second row is not in alignment, because theres is two indent for the first row, so how can the r chunk ignore the indent style?

**Comment by yihui** [comment]
These images are contained in `<p>`, so they are indented, too. I won't say this issue is impossible to solve, but it will require JavaScript, and I don't have time to go into the details. It is probably easier if you don't indent by 2 characters (which used to be common in Chinese typesetting).

If you really want the JS solution, I recommend you to ask on StackOverflow instead. This issue does not really belong to the rmarkdown package. It is more of a CSS question.
