### ISSUE TITLE
Set standard size for all tabs in tabset

### ISSUE THREAD

**Issue by dkyleward** [rstudio/rmarkdown#896]
I have 5-6 tabbed sections with varying amounts of information in them followed by a new section.  Currently, when you change tabs, the information underneath moves up and down the page.  It would be excellent to have an attribute to set all tabs equal in length to the largest tab.  Shorter tabs would just have white space to fill the difference.  If it's easier/quicker to just have a .tablength attribute and set it manually, that would be fine, too.  (If I'm missing something that already exists, can you point me to it?)

Thanks!

**Comment by yihui** [comment]
You can solve this issue using CSS, e.g. assign an additional class `fixed-height` to the tabset:

```markdown
## Quarterly Results {.tabset .fixed-height}

### By Product

(tab content)

### By Region

(tab content)

(more tab content)

## Another Section
```

Then include a CSS stylesheet and define the desired common height of the tabs, e..g

```css
.fixed-height .tab-content {
  height: 5em;
}
```

Since this looks like a question instead of a bug report or feature request, so please do us a favor to [post on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead in the future, and let us know the link if you don't get an answer in a few days. That way, you may not need to wait for a year to get an answer. Thanks!

**Comment by dkyleward** [comment]
Thanks. Didn't realize it was so easy!
