### ISSUE TITLE
pandoc document conversion failed with error 67

### ISSUE THREAD

**Issue by yli74** [rstudio/rmarkdown#925]
I'm using R 3.3.2 and Rstudio Version 1.0.44, here's the format of my RMarkdown file

```
---
title: "Sentiment Analysis"
output: 
   rmdformats::material:
    highlight: kate
---
```
When I try to knit, I got the following error

pandoc: Could not fetch /tabsets.js /tabsets.js: openBinaryFile: does not exist (No such file or directory) Error: pandoc document conversion failed with error 67 In addition: Warning messages: 1: In sink() : no sink to remove 2: In sink() : no sink to remove 3: MathJax doesn't work with self_contained when not using the rmarkdown "default" template. Execution halted

I read some questions on Stack Overflow and added `self contained: no`. I was able to knit the file and everything looks good on RStudio, but now I have new problems.

1. When I publish it on RPubs, all the images were gone.
2. When I click on knit button, I'm only give the option to knit to material... is there a way for me to knit it to pdf?

I'm a little desperate to fix this problem, any tips/advice is greatly appreciated.

**Comment by yihui** [comment]
I'm sorry but `rmdformats::material` is not an output format in the rmarkdown package, so your best bet is to ask the author of the rmdformats package. 

To answer your last two questions:

1. That is expected. If your HTML output is not self-contained, none of the external resources will be published to RPubs;

1. If you want PDF output, you need to explicitly list it in `output`, e.g.

```
output:
  rmdformats::material:
    highlight: kate
  pdf_document: default
```

For questions instead of bug reports or feature requests, so please do us a favor to [ask them on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead in the future and let us know the link if you don't get an answer in a few days. Thanks!
