### ISSUE TITLE
`df_print: paged` options not working?

### ISSUE THREAD

**Issue by nachocab** [rstudio/rmarkdown#962]
I have `df_print: paged` and then on a chunk that prints a 25-row table I have ` ```r{name, rows.print=5}...``` ` However, it doesn't seem to have an effect: 10 rows are printed and split into 3 pages. Am I missing something?

**Comment by stevekm** [comment]
Can you post the R Markdown you are using? I don't have a solution, I cannot even get `df_print: paged` to work at all and I am wondering what you did to get any output from it.

**Comment by nachocab** [comment]
Hi @stevekm I don't have an example handy, but basically, I just have an `_output.yaml` file with:

```
html_document:
    df_print: paged
```

Then, in the same folder as the yaml file, an Rmd file with:

```
---
output: html_document
---

```{r my_table}
cbind(iris,iris,iris) 
\``` (I don't know how to escape the backticks)

```

And then I generate the html by calling:

```
rmarkdown::render(input = my_report.Rmd, output_file = my_output.html, envir = globalenv())
```

**Comment by yihui** [comment]
This issue is not reproducible to me. Here is the minimal example I used: [test.zip](https://github.com/rstudio/rmarkdown/files/1383229/test.zip)

Please make sure [everything is up-to-date](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`. And report `devtools::session_info("rmarkdown")` next time. Thanks!
