### ISSUE TITLE
python interpreter path

### ISSUE THREAD

**Issue by jtian0** [rstudio/rmarkdown#985]
Hi, 

According to [knitr Language Engines](http://rmarkdown.rstudio.com/authoring_knitr_engines.html),

> The python engine enables execution of python code via an external python interpreter (the interpreter returned by `Sys.which("python")` is used to execute the code). 

However, the system-specified Python interpreter is not a very good choice on macOS and it is ubiquitous to use package manager (e.g. anaconda) instead. In fact, `Sys.which("python")` does not agree with shell returned `which python`. In my case it is
```
# Sys.which('python')
"/usr/bin/python"

# zsh, bash or any other shell interpreter 
/Users/username/anaconda/bin//python
```

**Comment by jjallaire** [comment]
That's because for bash sessions `.bashrc` is read and manipulates the PATH (this doesn't occur for GUI applications like RStudio). If you want to use a different python you can either manipulate your PATH (several ways to do that including .Rprofile or /etc/paths, /etc/paths.d or you can actually specify an alternate Python binary in the chunk options (@jmcphers I forget how to do that, we should probably add that to the R Markdown docs in any case).

**Comment by jmcphers** [comment]
I've updated the R Markdown docs to include instructions for specifying an alternate Python interpreter: https://github.com/rstudio/rmarkdown/commit/a497f037bbf545ad1e34a3735f755fd3eac3abe5

**Comment by jtian0** [comment]
Hi, 

This really works! Many thanks.

p.s. 
`~/.bashrc` (or `~/.zshrc`) does not necessarily caused the issue (it doesn't even exist in my case); as is configured and shown in `/usr/bin/env` (macOS), `anaconda python` is of higher priority to execute, so it should be global. Anyway, it works by specifying external interpreter.

**Comment by yihui** [comment]
You can, and probably should, set it as a global chunk option, if you are going to use the Anaconda python throughout the document. The relevant knitr doc is here: https://yihui.name/knitr/options/#language-engines
