### ISSUE TITLE
feature request: ability to include or remove "Code" button from .nb.html file generated from rnotebook

### ISSUE THREAD

**Issue by tshicelg** [rstudio/rmarkdown#989]
When a .nb.html file is generated from a R notebook, by default there is always a button called "Code" on the upper-right corner with pull down options such as "show all code", "hide all code" and "download rmd".  Is there anyway to get rid of that?  Basically decouple the code from the .nb.html report.

I know knitting .rmd file into a html report is one way to do it, but the .html file looses many nice features that .nb.html offers such as nice html tables, or interactive plots etc.

Thanks!

**Comment by yihui** [comment]
Could you show an example of the "nice html tables / interactive plots" you mentioned? I'm asking because I feel knitting to .html is the right way to go.

**Comment by mindymallory** [comment]
I have an example. https://github.com/mindymallory/ForwardCurves (run the forward.RMD document) Its a shiny app in an rmarkdown notebook. I prefer to embed the shiny app in the rmarkdown document because I can more easily add explanations to the document (still working on that stuff). Its more cumbersome to add explanitory text to a straight up shiny app.  

Old version is live at https://mindymallory.shinyapps.io/ForwardCurves/ which is simply a shiny app not in an rmarkdown document.

**Comment by mindymallory** [comment]
Though I just realized that in this case I can still create .html instead of nb.html. I didn't realize I could do that with an embedded shiny app for some reason.

**Comment by tshicelg** [comment]
Thank you Yihui for looking into this and Mindy for providing the example!  

The specific examples I had in mind for "nice table" is really just for displaying a data.frame.   nb.html automatically renders a data.frame into a nice html table, but the same code in html shows only simple text output.  For the "interactive plot", I was plotting a network graph using simpleNetwor funcition from networkD3, in html, the graph becomes static.  

For me, this is really about convenience.  For the two examples above, I understand you probably can code around them, but if there is one option can let you hide the code, I would just use the nb.html file as my final report.  Also, often time, rendering into html file requires re-run all the code which often takes a long time.  nb.html is much easier to work with.  I can fixed whatever texts/figures I want to fix, once I'm done, the report is already done.   

p.s. originally I posted this on the Rstudio support site and Kevin Ushey suggested that I file an issue here.

btw, don't want to digress here, but it would be nice to offer more themes for nb.html rendering.  I've seen people asked this before and just want to echo that.

**Comment by yihui** [comment]
For the nice tables, you can use the option `df_print: paged` for the `html_document` format:

```
output:
  html_document:
    df_print: paged
```

For interactive plots, HTML widgets work for `html_document`, too. There is nothing you will lose by generating .html output instead of .nb.html.

So basically this issue boils down to one thing: you don't want to re-run certain code chunks. I'm not sure if you understand the possible drawback of using notebooks: you may lose reproducibility. I feel many users miss this point: notebooks are great for random and exploratory work, but to make sure you get a reproducible report, you ought to recompile the document in a new R session, where all code chunks have to be re-executed. It can be dangerous to believe this:

> once I'm done, the report is already done

There is a good chance that you may really have done it, but there is no guarantee, since you are not working in a clean environment in notebooks (e.g., a later code chunk may affect results in a previous code chunk, depending on the order of execution).

The more reliable way is to turn on caching for time-consuming code chunks using the chunk option `cache = TRUE`.

I guess that is enough digression for this issue now :) Back to your original issue: you can use CSS to hide the Code button.

```css
#header .btn-group {
    display: none;
}
```

**Comment by tshicelg** [comment]
Thank you very much, Yihui!  Your points are well taken.
