### ISSUE TITLE
Rmarkdown does not produce valid XHTML

### ISSUE THREAD

**Issue by spgarbet** [rstudio/rmarkdown#995]
Attached is an example markdown file.  

```r
rmarkdown::render("xhtml.Rmd", output_file = "xhtml.html", output_format = "html_document")
```

Note that line 3 of the generated output is:

```html
<html xmlns="http://www.w3.org/1999/xhtml">
```

Which declares the html to be xhtml compliant--it's not and once notified correctly of the MIME type a browser will not render generated code. Much simpler to change this to &lt;html&gt;, and let the browser use it's fallbacks.
[xhtml.zip](https://github.com/rstudio/rmarkdown/files/835202/xhtml.zip)

**Comment by yihui** [comment]
I'm not sure what to do with this issue. If I remove the `xmlns` attribute, the [w3c validator](https://validator.w3.org/) will show the error below:

![image](https://user-images.githubusercontent.com/163582/29989654-f1fbf312-8f39-11e7-8ee8-0ae48bd42002.png)

I'm not an expert on this, but your issue may be due to the filename extension `.xhtml`. I wonder why `.html` cannot be used.

**Comment by yihui** [comment]
I have removed the `xmlns` attribute: https://github.com/rstudio/rmarkdown/issues/1640#issuecomment-558736407 Thank you!
