### ISSUE TITLE
Indent of wraped line h1 heading (floating toc)

### ISSUE THREAD

**Issue by sammerk** [rstudio/rmarkdown#997]
Out of aesthetic reasons I would prefer the same indent in all lines of a level 1 heading entry in the floating toc (see screenshot). This was fixed for higher level headings already ...

![grafik](https://cloud.githubusercontent.com/assets/7669803/23890763/7cd7a928-0893-11e7-8ae4-95ce053d018a.png)

Thank's
Samuel

**Comment by yihui** [comment]
This is caused by 
https://github.com/rstudio/rmarkdown/blob/d31ec87679571a84092b5bec4f7de6f42511e9a4/inst/rmd/h/tocify-1.9.1/jquery.tocify.css#L28-L31

You can specify your custom CSS to override it, e.g.,

```css
.tocify-header {
    text-indent: initial;
}
```

http://rmarkdown.rstudio.com/html_document_format.html#custom_css

In the future you can try to [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) first, where you might be quicker responses. Thanks!

**Comment by jstover79** [comment]
I this has been closed, but it would be nice to be able to apply this solution to sub-sub-header as well (and possible further down the toc hierarchy. Thanks! It would be great to have this built into the Rmarkdown toc functionality, to have some kind of padding/margin/wrapping option for the toc display.

**Comment by cderv** [comment]
> It would be great to have this built into the Rmarkdown toc functionality, to have some kind of padding/margin/wrapping option for the toc display.

@jstover79 Can you open a new issue about this Feature request if non already exists ? Without it, it won't be in the backlog to even been consider because closed issue won't often be noticed.
